/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_uri.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_uri.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct uri184012 uri184012;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct TY13406 TY13406;
typedef struct slice84662 slice84662;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  uri184012  {
NimStringDesc* Scheme;
NimStringDesc* Username;
NimStringDesc* Password;
NimStringDesc* Hostname;
NimStringDesc* Port;
NimStringDesc* Path;
NimStringDesc* Query;
NimStringDesc* Anchor;
};
typedef NU8 TY76268[32];
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
struct  slice84662  {
NI A;
NI B;
};
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY13406 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, HEX24_184029)(NimStringDesc* url);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, HEX2F_184040)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, add_184054)(NimStringDesc** url, NimStringDesc* a);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, parseauthority_184065)(NimStringDesc* authority, uri184012* result);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, parsepath_184097)(NimStringDesc* uri, NI* i, uri184012* result);
static N_INLINE(NI, parseuntil_93058)(NimStringDesc* s, NimStringDesc** token, TY76268 until, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, inituri_184177)(uri184012* Result);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, parseuri_184187)(NimStringDesc* uri, uri184012* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NI, parsewhile_93142)(NimStringDesc* s, NimStringDesc** token, TY76268 validchars, NI start);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, removedotsegments_184313)(NimStringDesc* path);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(NimStringDesc*, pop_129510)(TY13406** s_129518);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep);
N_NIMCALL(NimStringDesc*, merge_184460)(uri184012* base, uri184012* reference);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NI, rfind_97982)(NimStringDesc* s, NimStringDesc* sub, NI start);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_84655)(NimStringDesc* s, slice84662 x);
static N_INLINE(slice84662, HEX2EHEX2E_93499)(NI a_93503, NI b_93505);
N_NIMCALL(void, combine_184483)(uri184012* base, uri184012* reference, uri184012* Result);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_NIMCALL(void, combine_184498)(uri184012* uris, NI urisLen0, uri184012* Result);
N_NIMCALL(void, HEX2F_184555)(uri184012* x, NimStringDesc* path, uri184012* Result);
N_NIMCALL(NimStringDesc*, HEX24_184577)(uri184012* u);
STRING_LITERAL(TMP567, "", 0);
static NIM_CONST TY76268 TMP570 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP572, "mailto", 6);
static NIM_CONST TY76268 TMP573 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST TY76268 TMP574 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST TY76268 TMP578 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x68, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST TY76268 TMP580 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x80, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP581, "Expected authority got nothing.", 31);
STRING_LITERAL(TMP590, "/", 1);
STRING_LITERAL(TMP598, "://", 3);
STRING_LITERAL(TMP599, ":", 1);
STRING_LITERAL(TMP600, "@", 1);
extern TFrame* frameptr_16442;
TNimType NTI184012; /* Uri */
extern TNimType NTI149; /* string */
extern TNimType NTI21801; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern tgcheap47416 gch_47444;
extern TNimType NTI13406; /* seq[string] */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

N_NIMCALL(NimStringDesc*, HEX24_184029)(NimStringDesc* url) {
	NimStringDesc* result;
	nimfr("$", "uri.nim")
	result = 0;
	nimln(24, "uri.nim");
	nimln(24, "uri.nim");
	result = copyString(url);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX2F_184040)(NimStringDesc* a, NimStringDesc* b) {
	NimStringDesc* result;
	NimStringDesc* urls;
	NimStringDesc* bs;
	nimfr("/", "uri.nim")
	result = 0;
	nimln(30, "uri.nim");
	urls = HEX24_184029(a);
	nimln(31, "uri.nim");
	bs = HEX24_184029(b);
	nimln(32, "uri.nim");
	{
		nimln(32, "uri.nim");
		if (!((urls) && (urls)->Sup.len == 0)) goto LA3;
		nimln(32, "uri.nim");
		nimln(32, "uri.nim");
		result = copyString(b);
		goto BeforeRet;
	}
	LA3: ;
	nimln(33, "uri.nim");
	{
		NI TMP566;
		nimln(33, "uri.nim");
		nimln(33, "uri.nim");
		nimln(33, "uri.nim");
		nimln(33, "uri.nim");
		TMP566 = subInt(urls->Sup.len, 1);
		if ((NU)((NI64)(TMP566)) > (NU)(urls->Sup.len)) raiseIndexError();
		if (!!(((NU8)(urls->data[(NI64)(TMP566)]) == (NU8)(47)))) goto LA7;
		nimln(34, "uri.nim");
		urls = addChar(urls, 47);
	}
	LA7: ;
	nimln(35, "uri.nim");
	{
		NimStringDesc* LOC13;
		nimln(35, "uri.nim");
		if ((NU)(0) > (NU)(bs->Sup.len)) raiseIndexError();
		if (!((NU8)(bs->data[0]) == (NU8)(47))) goto LA11;
		nimln(36, "uri.nim");
		nimln(36, "uri.nim");
		LOC13 = 0;
		LOC13 = copyStr(bs, 1);
		urls = resizeString(urls, LOC13->Sup.len + 0);
appendString(urls, LOC13);
	}
	goto LA9;
	LA11: ;
	{
		nimln(38, "uri.nim");
		urls = resizeString(urls, bs->Sup.len + 0);
appendString(urls, bs);
	}
	LA9: ;
	nimln(39, "uri.nim");
	result = copyString(urls);
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, add_184054)(NimStringDesc** url, NimStringDesc* a) {
	nimfr("add", "uri.nim")
	nimln(45, "uri.nim");
	unsureAsgnRef((void**) (&(*url)), HEX2F_184040((*url), a));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, parseauthority_184065)(NimStringDesc* authority, uri184012* result) {
	NI i;
	NIM_BOOL inport;
	nimfr("parseAuthority", "uri.nim")
	nimln(48, "uri.nim");
	i = 0;
	nimln(49, "uri.nim");
	inport = NIM_FALSE;
	{
		nimln(50, "uri.nim");
		while (1) {
			nimln(51, "uri.nim");
			if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
			switch (((NU8)(authority->data[i]))) {
			case 64:
			{
				nimln(53, "uri.nim");
				unsureAsgnRef((void**) (&(*result).Password), copyString((*result).Port));
				nimln(54, "uri.nim");
				unsureAsgnRef((void**) (&(*result).Port), copyString(((NimStringDesc*) &TMP567)));
				nimln(55, "uri.nim");
				unsureAsgnRef((void**) (&(*result).Username), copyString((*result).Hostname));
				nimln(56, "uri.nim");
				unsureAsgnRef((void**) (&(*result).Hostname), copyString(((NimStringDesc*) &TMP567)));
				nimln(57, "uri.nim");
				inport = NIM_FALSE;
			}
			break;
			case 58:
			{
				nimln(59, "uri.nim");
				inport = NIM_TRUE;
			}
			break;
			case 0:
			{
				nimln(60, "uri.nim");
				goto LA1;
			}
			break;
			default:
			{
				nimln(62, "uri.nim");
				{
					if (!inport) goto LA9;
					nimln(63, "uri.nim");
					if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
					(*result).Port = addChar((*result).Port, authority->data[i]);
				}
				goto LA7;
				LA9: ;
				{
					nimln(65, "uri.nim");
					if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
					(*result).Hostname = addChar((*result).Hostname, authority->data[i]);
				}
				LA7: ;
			}
			break;
			}
			nimln(66, "uri.nim");
			i = addInt(i, 1);
		}
	} LA1: ;
	popFrame();
}

static N_INLINE(NI, parseuntil_93058)(NimStringDesc* s, NimStringDesc** token, TY76268 until, NI start) {
	NI result;
	NI i;
	NI TMP568;
	NI TMP569;
	nimfr("parseUntil", "parseutils.nim")
	result = 0;
	nimln(158, "parseutils.nim");
	i = start;
	{
		nimln(159, "parseutils.nim");
		while (1) {
			NIM_BOOL LOC3;
			nimln(159, "parseutils.nim");
			LOC3 = 0;
			nimln(159, "parseutils.nim");
			nimln(159, "parseutils.nim");
			LOC3 = (i < s->Sup.len);
			if (!(LOC3)) goto LA4;
			nimln(159, "parseutils.nim");
			nimln(159, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			LOC3 = !(((until[((NU8)(s->data[i]))/8] &(1<<(((NU8)(s->data[i]))%8)))!=0));
			LA4: ;
			if (!LOC3) goto LA2;
			nimln(159, "parseutils.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	nimln(160, "parseutils.nim");
	nimln(160, "parseutils.nim");
	TMP568 = subInt(i, start);
	result = (NI64)(TMP568);
	nimln(161, "parseutils.nim");
	nimln(161, "parseutils.nim");
	nimln(161, "parseutils.nim");
	TMP569 = subInt(i, 1);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI64)(TMP569)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, parsepath_184097)(NimStringDesc* uri, NI* i, uri184012* result) {
	NI LOC1;
	nimfr("parsePath", "uri.nim")
	nimln(70, "uri.nim");
	nimln(70, "uri.nim");
	LOC1 = 0;
	LOC1 = parseuntil_93058(uri, (&(*result).Path), TMP570, (*i));
	(*i) = addInt((*i), LOC1);
	nimln(73, "uri.nim");
	{
		NimStringDesc* LOC4;
		nimln(73, "uri.nim");
		nimln(73, "uri.nim");
		LOC4 = 0;
		LOC4 = nsuToLowerStr((*result).Scheme);
		if (!eqStrings(LOC4, ((NimStringDesc*) &TMP572))) goto LA5;
		nimln(74, "uri.nim");
		parseauthority_184065((*result).Path, result);
		nimln(75, "uri.nim");
		unsureAsgnRef((void**) (&(*result).Path), copyString(((NimStringDesc*) &TMP567)));
	}
	LA5: ;
	nimln(77, "uri.nim");
	{
		NI LOC11;
		nimln(77, "uri.nim");
		if ((NU)((*i)) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!((NU8)(uri->data[(*i)]) == (NU8)(63))) goto LA9;
		nimln(78, "uri.nim");
		(*i) = addInt((*i), 1);
		nimln(79, "uri.nim");
		nimln(79, "uri.nim");
		LOC11 = 0;
		LOC11 = parseuntil_93058(uri, (&(*result).Query), TMP573, (*i));
		(*i) = addInt((*i), LOC11);
	}
	LA9: ;
	nimln(81, "uri.nim");
	{
		NI LOC16;
		nimln(81, "uri.nim");
		if ((NU)((*i)) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!((NU8)(uri->data[(*i)]) == (NU8)(35))) goto LA14;
		nimln(82, "uri.nim");
		(*i) = addInt((*i), 1);
		nimln(83, "uri.nim");
		nimln(83, "uri.nim");
		LOC16 = 0;
		LOC16 = parseuntil_93058(uri, (&(*result).Anchor), TMP574, (*i));
		(*i) = addInt((*i), LOC16);
	}
	LA14: ;
	popFrame();
}

N_NIMCALL(void, inituri_184177)(uri184012* Result) {
	uri184012 LOC1;
	nimfr("initUri", "uri.nim")
	nimln(86, "uri.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Scheme = copyString(((NimStringDesc*) &TMP567));
	LOC1.Username = copyString(((NimStringDesc*) &TMP567));
	LOC1.Password = copyString(((NimStringDesc*) &TMP567));
	LOC1.Hostname = copyString(((NimStringDesc*) &TMP567));
	LOC1.Port = copyString(((NimStringDesc*) &TMP567));
	LOC1.Path = copyString(((NimStringDesc*) &TMP567));
	LOC1.Query = copyString(((NimStringDesc*) &TMP567));
	LOC1.Anchor = copyString(((NimStringDesc*) &TMP567));
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI184012));
	popFrame();
}

static N_INLINE(NI, parsewhile_93142)(NimStringDesc* s, NimStringDesc** token, TY76268 validchars, NI start) {
	NI result;
	NI i;
	NI TMP576;
	NI TMP577;
	nimfr("parseWhile", "parseutils.nim")
	result = 0;
	nimln(178, "parseutils.nim");
	i = start;
	{
		nimln(179, "parseutils.nim");
		while (1) {
			nimln(179, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((validchars[((NU8)(s->data[i]))/8] &(1<<(((NU8)(s->data[i]))%8)))!=0)) goto LA2;
			nimln(179, "parseutils.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	nimln(180, "parseutils.nim");
	nimln(180, "parseutils.nim");
	TMP576 = subInt(i, start);
	result = (NI64)(TMP576);
	nimln(181, "parseutils.nim");
	nimln(181, "parseutils.nim");
	nimln(181, "parseutils.nim");
	TMP577 = subInt(i, 1);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI64)(TMP577)));
	popFrame();
	return result;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, parseuri_184187)(NimStringDesc* uri, uri184012* Result) {
	NI i;
	NI LOC5;
	nimfr("parseUri", "uri.nim")
	nimln(91, "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI184012));
	inituri_184177(Result);
	nimln(93, "uri.nim");
	i = 0;
	nimln(96, "uri.nim");
	{
		nimln(96, "uri.nim");
		if ((NU)(i) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!((NU8)(uri->data[i]) == (NU8)(47))) goto LA3;
		nimln(97, "uri.nim");
		parsepath_184097(uri, (&i), Result);
		nimln(98, "uri.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(101, "uri.nim");
	nimln(101, "uri.nim");
	LOC5 = 0;
	LOC5 = parsewhile_93142(uri, (&(*Result).Scheme), TMP578, i);
	i = addInt(i, LOC5);
	nimln(102, "uri.nim");
	{
		nimln(102, "uri.nim");
		nimln(102, "uri.nim");
		if ((NU)(i) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!!(((NU8)(uri->data[i]) == (NU8)(58)))) goto LA8;
		nimln(104, "uri.nim");
		i = 0;
		nimln(105, "uri.nim");
		unsureAsgnRef((void**) (&(*Result).Scheme), copyString(((NimStringDesc*) &TMP567)));
		nimln(106, "uri.nim");
		parsepath_184097(uri, (&i), Result);
		nimln(107, "uri.nim");
		goto BeforeRet;
	}
	LA8: ;
	nimln(108, "uri.nim");
	i = addInt(i, 1);
	nimln(111, "uri.nim");
	{
		NIM_BOOL LOC12;
		NI TMP579;
		NimStringDesc* authority;
		NI LOC16;
		nimln(111, "uri.nim");
		LOC12 = 0;
		nimln(111, "uri.nim");
		if ((NU)(i) > (NU)(uri->Sup.len)) raiseIndexError();
		LOC12 = ((NU8)(uri->data[i]) == (NU8)(47));
		if (!(LOC12)) goto LA13;
		nimln(111, "uri.nim");
		nimln(111, "uri.nim");
		TMP579 = addInt(i, 1);
		if ((NU)((NI64)(TMP579)) > (NU)(uri->Sup.len)) raiseIndexError();
		LOC12 = ((NU8)(uri->data[(NI64)(TMP579)]) == (NU8)(47));
		LA13: ;
		if (!LOC12) goto LA14;
		nimln(112, "uri.nim");
		i = addInt(i, 2);
		nimln(113, "uri.nim");
		authority = copyString(((NimStringDesc*) &TMP567));
		nimln(114, "uri.nim");
		nimln(114, "uri.nim");
		LOC16 = 0;
		LOC16 = parseuntil_93058(uri, (&authority), TMP580, i);
		i = addInt(i, LOC16);
		nimln(115, "uri.nim");
		{
			valueerror3249* e_184285;
			NimStringDesc* LOC21;
			nimln(115, "uri.nim");
			if (!((authority) && (authority)->Sup.len == 0)) goto LA19;
			e_184285 = 0;
			nimln(2149, "system.nim");
			e_184285 = (valueerror3249*) newObj((&NTI21801), sizeof(valueerror3249));
			(*e_184285).Sup.Sup.m_type = (&NTI3249);
			nimln(2150, "system.nim");
			LOC21 = 0;
			LOC21 = (*e_184285).Sup.message; (*e_184285).Sup.message = copyStringRC1(((NimStringDesc*) &TMP581));
			if (LOC21) nimGCunrefNoCycle(LOC21);
			nimln(116, "uri.nim");
			raiseException((Exception*)e_184285, "ValueError");
		}
		LA19: ;
		nimln(117, "uri.nim");
		parseauthority_184065(authority, Result);
	}
	LA14: ;
	nimln(120, "uri.nim");
	parsepath_184097(uri, (&i), Result);
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NimStringDesc*, pop_129510)(TY13406** s_129518) {
	NimStringDesc* result;
	NI l;
	NI TMP585;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	nimln(1810, "system.nim");
	TMP585 = subInt((*s_129518)->Sup.len, 1);
	l = (NI64)(TMP585);
	nimln(1811, "system.nim");
	if ((NU)(l) >= (NU)((*s_129518)->Sup.len)) raiseIndexError();
	result = copyString((*s_129518)->data[l]);
	nimln(1812, "system.nim");
	(*s_129518) = (TY13406*) setLengthSeq(&((*s_129518))->Sup, sizeof(NimStringDesc*), l);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, removedotsegments_184313)(NimStringDesc* path) {
	NimStringDesc* result;
	TY13406* collection;
	NIM_BOOL endswithslash;
	NI TMP582;
	NI i;
	NimStringDesc* currentsegment;
	nimfr("removeDotSegments", "uri.nim")
	result = 0;
	nimln(123, "uri.nim");
	collection = (TY13406*) newSeq((&NTI13406), 0);
	nimln(124, "uri.nim");
	nimln(124, "uri.nim");
	nimln(124, "uri.nim");
	nimln(124, "uri.nim");
	TMP582 = subInt(path->Sup.len, 1);
	if ((NU)((NI64)(TMP582)) > (NU)(path->Sup.len)) raiseIndexError();
	endswithslash = ((NU8)(path->data[(NI64)(TMP582)]) == (NU8)(47));
	nimln(125, "uri.nim");
	i = 0;
	nimln(126, "uri.nim");
	currentsegment = copyString(((NimStringDesc*) &TMP567));
	{
		nimln(127, "uri.nim");
		while (1) {
			{
				nimln(128, "uri.nim");
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				switch (((NU8)(path->data[i]))) {
				case 47:
				{
					NimStringDesc* LOC5;
					nimln(130, "uri.nim");
					collection = (TY13406*) incrSeq(&(collection)->Sup, sizeof(NimStringDesc*));
					LOC5 = 0;
					LOC5 = collection->data[collection->Sup.len-1]; collection->data[collection->Sup.len-1] = copyStringRC1(currentsegment);
					if (LOC5) nimGCunrefNoCycle(LOC5);
					nimln(131, "uri.nim");
					currentsegment = copyString(((NimStringDesc*) &TMP567));
				}
				break;
				case 46:
				{
					nimln(133, "uri.nim");
					{
						NIM_BOOL LOC9;
						NI TMP583;
						NI TMP584;
						nimln(133, "uri.nim");
						LOC9 = 0;
						nimln(133, "uri.nim");
						nimln(133, "uri.nim");
						TMP583 = addInt(i, 1);
						if ((NU)((NI64)(TMP583)) > (NU)(path->Sup.len)) raiseIndexError();
						LOC9 = ((NU8)(path->data[(NI64)(TMP583)]) == (NU8)(46));
						if (!(LOC9)) goto LA10;
						nimln(133, "uri.nim");
						nimln(133, "uri.nim");
						TMP584 = addInt(i, 2);
						if ((NU)((NI64)(TMP584)) > (NU)(path->Sup.len)) raiseIndexError();
						LOC9 = ((NU8)(path->data[(NI64)(TMP584)]) == (NU8)(47));
						LA10: ;
						if (!LOC9) goto LA11;
						nimln(134, "uri.nim");
						{
							NimStringDesc* LOC17;
							nimln(134, "uri.nim");
							nimln(134, "uri.nim");
							if (!(0 < collection->Sup.len)) goto LA15;
							nimln(135, "uri.nim");
							nimln(135, "uri.nim");
							LOC17 = 0;
							LOC17 = pop_129510((&collection));
							nimln(136, "uri.nim");
							i = addInt(i, 3);
							nimln(137, "uri.nim");
							goto LA3;
						}
						LA15: ;
					}
					goto LA7;
					LA11: ;
					{
						NI TMP586;
						nimln(138, "uri.nim");
						nimln(138, "uri.nim");
						TMP586 = addInt(i, 1);
						if ((NU)((NI64)(TMP586)) > (NU)(path->Sup.len)) raiseIndexError();
						if (!((NU8)(path->data[(NI64)(TMP586)]) == (NU8)(47))) goto LA19;
						nimln(139, "uri.nim");
						i = addInt(i, 2);
						nimln(140, "uri.nim");
						goto LA3;
					}
					goto LA7;
					LA19: ;
					LA7: ;
					nimln(141, "uri.nim");
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					currentsegment = addChar(currentsegment, path->data[i]);
				}
				break;
				case 0:
				{
					nimln(143, "uri.nim");
					{
						NimStringDesc* LOC26;
						nimln(143, "uri.nim");
						nimln(143, "uri.nim");
						if (!!(((currentsegment) && (currentsegment)->Sup.len == 0))) goto LA24;
						nimln(144, "uri.nim");
						collection = (TY13406*) incrSeq(&(collection)->Sup, sizeof(NimStringDesc*));
						LOC26 = 0;
						LOC26 = collection->data[collection->Sup.len-1]; collection->data[collection->Sup.len-1] = copyStringRC1(currentsegment);
						if (LOC26) nimGCunrefNoCycle(LOC26);
					}
					LA24: ;
					nimln(145, "uri.nim");
					goto LA1;
				}
				break;
				default:
				{
					nimln(147, "uri.nim");
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					currentsegment = addChar(currentsegment, path->data[i]);
				}
				break;
				}
				nimln(148, "uri.nim");
				i = addInt(i, 1);
			} LA3: ;
		}
	} LA1: ;
	nimln(150, "uri.nim");
	result = nsuJoinSep(collection->data, collection->Sup.len, ((NimStringDesc*) &TMP590));
	nimln(151, "uri.nim");
	{
		if (!endswithslash) goto LA30;
		nimln(151, "uri.nim");
		result = addChar(result, 47);
	}
	LA30: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_84655)(NimStringDesc* s, slice84662 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP594;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP594 = addInt(s->Sup.len, x.A);
		LOC1 = (NI64)(TMP594);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP595;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP595 = addInt(s->Sup.len, x.B);
		LOC7 = (NI64)(TMP595);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice84662, HEX2EHEX2E_93499)(NI a_93503, NI b_93505) {
	slice84662 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_93503;
	nimln(227, "system.nim");
	result.B = b_93505;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, merge_184460)(uri184012* base, uri184012* reference) {
	NimStringDesc* result;
	nimfr("merge", "uri.nim")
	result = 0;
	nimln(155, "uri.nim");
	nimln(155, "uri.nim");
	{
		NIM_BOOL LOC3;
		NimStringDesc* LOC7;
		nimln(155, "uri.nim");
		LOC3 = 0;
		nimln(155, "uri.nim");
		nimln(155, "uri.nim");
		LOC3 = !((((*base).Hostname) && ((*base).Hostname)->Sup.len == 0));
		if (!(LOC3)) goto LA4;
		nimln(155, "uri.nim");
		LOC3 = (((*base).Path) && ((*base).Path)->Sup.len == 0);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(156, "uri.nim");
		LOC7 = 0;
		LOC7 = rawNewString((*reference).Path->Sup.len + 1);
appendChar(LOC7, 47);
appendString(LOC7, (*reference).Path);
		result = LOC7;
	}
	goto LA1;
	LA5: ;
	{
		NI lastsegment;
		nimln(158, "uri.nim");
		lastsegment = rfind_97982((*base).Path, ((NimStringDesc*) &TMP590), -1);
		nimln(159, "uri.nim");
		{
			nimln(159, "uri.nim");
			if (!(lastsegment == -1)) goto LA11;
			result = copyString((*reference).Path);
		}
		goto LA9;
		LA11: ;
		{
			NimStringDesc* LOC14;
			slice84662 LOC15;
			NimStringDesc* LOC16;
			nimln(162, "uri.nim");
			LOC14 = 0;
			nimln(162, "uri.nim");
			nimln(162, "uri.nim");
			LOC15 = HEX2EHEX2E_93499(0, lastsegment);
			LOC16 = 0;
			LOC16 = HEX5BHEX5D_84655((*base).Path, LOC15);
			LOC14 = rawNewString(LOC16->Sup.len + (*reference).Path->Sup.len + 0);
appendString(LOC14, LOC16);
appendString(LOC14, (*reference).Path);
			result = LOC14;
		}
		LA9: ;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, combine_184483)(uri184012* base, uri184012* reference, uri184012* Result) {
	nimfr("combine", "uri.nim")
	nimln(193, "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI184012));
	inituri_184177(Result);
	nimln(194, "uri.nim");
	{
		NIM_BOOL LOC3;
		nimln(194, "uri.nim");
		LOC3 = 0;
		nimln(194, "uri.nim");
		nimln(194, "uri.nim");
		LOC3 = !(eqStrings((*reference).Scheme, (*base).Scheme));
		if (!(LOC3)) goto LA4;
		nimln(194, "uri.nim");
		nimln(194, "uri.nim");
		LOC3 = !((((*reference).Scheme) && ((*reference).Scheme)->Sup.len == 0));
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(195, "uri.nim");
		genericAssign((void*)Result, (void*)reference, (&NTI184012));
		nimln(196, "uri.nim");
		unsureAsgnRef((void**) (&(*Result).Path), removedotsegments_184313((*Result).Path));
	}
	goto LA1;
	LA5: ;
	{
		nimln(198, "uri.nim");
		{
			nimln(198, "uri.nim");
			nimln(198, "uri.nim");
			if (!!((((*reference).Hostname) && ((*reference).Hostname)->Sup.len == 0))) goto LA10;
			nimln(188, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Hostname), copyString((*reference).Hostname));
			nimln(189, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Username), copyString((*reference).Username));
			nimln(190, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Port), copyString((*reference).Port));
			nimln(191, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Password), copyString((*reference).Password));
			nimln(200, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Path), removedotsegments_184313((*reference).Path));
			nimln(201, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Query), copyString((*reference).Query));
		}
		goto LA8;
		LA10: ;
		{
			nimln(203, "uri.nim");
			{
				nimln(203, "uri.nim");
				if (!(((*reference).Path) && ((*reference).Path)->Sup.len == 0)) goto LA15;
				nimln(204, "uri.nim");
				unsureAsgnRef((void**) (&(*Result).Path), copyString((*base).Path));
				nimln(205, "uri.nim");
				{
					nimln(205, "uri.nim");
					nimln(205, "uri.nim");
					if (!!((((*reference).Query) && ((*reference).Query)->Sup.len == 0))) goto LA19;
					nimln(206, "uri.nim");
					unsureAsgnRef((void**) (&(*Result).Query), copyString((*reference).Query));
				}
				goto LA17;
				LA19: ;
				{
					nimln(208, "uri.nim");
					unsureAsgnRef((void**) (&(*Result).Query), copyString((*base).Query));
				}
				LA17: ;
			}
			goto LA13;
			LA15: ;
			{
				nimln(210, "uri.nim");
				{
					NIM_BOOL LOC25;
					nimln(210, "uri.nim");
					LOC25 = 0;
					LOC25 = nsuStartsWith((*reference).Path, ((NimStringDesc*) &TMP590));
					if (!LOC25) goto LA26;
					nimln(211, "uri.nim");
					unsureAsgnRef((void**) (&(*Result).Path), removedotsegments_184313((*reference).Path));
				}
				goto LA23;
				LA26: ;
				{
					NimStringDesc* LOC29;
					nimln(213, "uri.nim");
					nimln(213, "uri.nim");
					LOC29 = 0;
					LOC29 = merge_184460(base, reference);
					unsureAsgnRef((void**) (&(*Result).Path), removedotsegments_184313(LOC29));
				}
				LA23: ;
				nimln(214, "uri.nim");
				unsureAsgnRef((void**) (&(*Result).Query), copyString((*reference).Query));
			}
			LA13: ;
			nimln(188, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Hostname), copyString((*base).Hostname));
			nimln(189, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Username), copyString((*base).Username));
			nimln(190, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Port), copyString((*base).Port));
			nimln(191, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).Password), copyString((*base).Password));
		}
		LA8: ;
		nimln(216, "uri.nim");
		unsureAsgnRef((void**) (&(*Result).Scheme), copyString((*base).Scheme));
	}
	LA1: ;
	nimln(217, "uri.nim");
	unsureAsgnRef((void**) (&(*Result).Anchor), copyString((*reference).Anchor));
	popFrame();
}

N_NIMCALL(void, combine_184498)(uri184012* uris, NI urisLen0, uri184012* Result) {
	nimfr("combine", "uri.nim")
	nimln(221, "uri.nim");
	if ((NU)(0) >= (NU)(urisLen0)) raiseIndexError();
	genericAssign((void*)Result, (void*)(&uris[0]), (&NTI184012));
	{
		NI i_184531;
		NI HEX3Atmp_184535;
		NI res_184538;
		i_184531 = 0;
		HEX3Atmp_184535 = 0;
		nimln(222, "uri.nim");
		nimln(222, "uri.nim");
		nimln(222, "uri.nim");
		HEX3Atmp_184535 = subInt(urisLen0, 1);
		nimln(1576, "system.nim");
		res_184538 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				uri184012 LOC4;
				nimln(1577, "system.nim");
				if (!(res_184538 <= HEX3Atmp_184535)) goto LA3;
				nimln(1576, "system.nim");
				i_184531 = res_184538;
				nimln(223, "uri.nim");
				if ((NU)(i_184531) >= (NU)(urisLen0)) raiseIndexError();
				memset((void*)(&LOC4), 0, sizeof(LOC4));
				combine_184483(Result, (&uris[i_184531]), (&LOC4));
				genericShallowAssign((void*)Result, (void*)(&LOC4), (&NTI184012));
				nimln(1579, "system.nim");
				res_184538 = addInt(res_184538, 1);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX2F_184555)(uri184012* x, NimStringDesc* path, uri184012* Result) {
	nimfr("/", "uri.nim")
	nimln(243, "uri.nim");
	genericAssign((void*)Result, (void*)x, (&NTI184012));
	nimln(244, "uri.nim");
	{
		NI TMP596;
		nimln(244, "uri.nim");
		nimln(244, "uri.nim");
		nimln(244, "uri.nim");
		TMP596 = subInt((*Result).Path->Sup.len, 1);
		if ((NU)((NI64)(TMP596)) > (NU)((*Result).Path->Sup.len)) raiseIndexError();
		if (!((NU8)((*Result).Path->data[(NI64)(TMP596)]) == (NU8)(47))) goto LA3;
		nimln(245, "uri.nim");
		{
			NI TMP597;
			slice84662 LOC9;
			NimStringDesc* LOC10;
			nimln(245, "uri.nim");
			if ((NU)(0) > (NU)(path->Sup.len)) raiseIndexError();
			if (!((NU8)(path->data[0]) == (NU8)(47))) goto LA7;
			nimln(246, "uri.nim");
			nimln(246, "uri.nim");
			nimln(246, "uri.nim");
			nimln(246, "uri.nim");
			nimln(246, "uri.nim");
			TMP597 = subInt(path->Sup.len, 1);
			LOC9 = HEX2EHEX2E_93499(1, (NI64)(TMP597));
			LOC10 = 0;
			LOC10 = HEX5BHEX5D_84655(path, LOC9);
			(*Result).Path = resizeString((*Result).Path, LOC10->Sup.len + 0);
appendString((*Result).Path, LOC10);
		}
		goto LA5;
		LA7: ;
		{
			nimln(248, "uri.nim");
			(*Result).Path = resizeString((*Result).Path, path->Sup.len + 0);
appendString((*Result).Path, path);
		}
		LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		nimln(250, "uri.nim");
		{
			nimln(250, "uri.nim");
			nimln(250, "uri.nim");
			if ((NU)(0) > (NU)(path->Sup.len)) raiseIndexError();
			if (!!(((NU8)(path->data[0]) == (NU8)(47)))) goto LA15;
			nimln(251, "uri.nim");
			(*Result).Path = addChar((*Result).Path, 47);
		}
		LA15: ;
		nimln(252, "uri.nim");
		(*Result).Path = resizeString((*Result).Path, path->Sup.len + 0);
appendString((*Result).Path, path);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX24_184577)(uri184012* u) {
	NimStringDesc* result;
	nimfr("$", "uri.nim")
	result = 0;
	nimln(256, "uri.nim");
	result = copyString(((NimStringDesc*) &TMP567));
	nimln(257, "uri.nim");
	{
		nimln(257, "uri.nim");
		nimln(257, "uri.nim");
		if (!(0 < (*u).Scheme->Sup.len)) goto LA3;
		nimln(258, "uri.nim");
		result = resizeString(result, (*u).Scheme->Sup.len + 0);
appendString(result, (*u).Scheme);
		nimln(259, "uri.nim");
		result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TMP598));
	}
	LA3: ;
	nimln(260, "uri.nim");
	{
		nimln(260, "uri.nim");
		nimln(260, "uri.nim");
		if (!(0 < (*u).Username->Sup.len)) goto LA7;
		nimln(261, "uri.nim");
		result = resizeString(result, (*u).Username->Sup.len + 0);
appendString(result, (*u).Username);
		nimln(262, "uri.nim");
		{
			nimln(262, "uri.nim");
			nimln(262, "uri.nim");
			if (!(0 < (*u).Password->Sup.len)) goto LA11;
			nimln(263, "uri.nim");
			result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP599));
			nimln(264, "uri.nim");
			result = resizeString(result, (*u).Password->Sup.len + 0);
appendString(result, (*u).Password);
		}
		LA11: ;
		nimln(265, "uri.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP600));
	}
	LA7: ;
	nimln(266, "uri.nim");
	result = resizeString(result, (*u).Hostname->Sup.len + 0);
appendString(result, (*u).Hostname);
	nimln(267, "uri.nim");
	{
		nimln(267, "uri.nim");
		nimln(267, "uri.nim");
		if (!(0 < (*u).Port->Sup.len)) goto LA15;
		nimln(268, "uri.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP599));
		nimln(269, "uri.nim");
		result = resizeString(result, (*u).Port->Sup.len + 0);
appendString(result, (*u).Port);
	}
	LA15: ;
	nimln(270, "uri.nim");
	{
		nimln(270, "uri.nim");
		nimln(270, "uri.nim");
		if (!(0 < (*u).Path->Sup.len)) goto LA19;
		nimln(271, "uri.nim");
		{
			nimln(271, "uri.nim");
			nimln(271, "uri.nim");
			if ((NU)(0) > (NU)((*u).Path->Sup.len)) raiseIndexError();
			if (!!(((NU8)((*u).Path->data[0]) == (NU8)(47)))) goto LA23;
			nimln(271, "uri.nim");
			result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP590));
		}
		LA23: ;
		nimln(272, "uri.nim");
		result = resizeString(result, (*u).Path->Sup.len + 0);
appendString(result, (*u).Path);
	}
	LA19: ;
	nimln(273, "uri.nim");
	result = resizeString(result, (*u).Query->Sup.len + 0);
appendString(result, (*u).Query);
	nimln(274, "uri.nim");
	result = resizeString(result, (*u).Anchor->Sup.len + 0);
appendString(result, (*u).Anchor);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit)(void) {
	nimfr("uri", "uri.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit)(void) {
static TNimNode* TMP575[8];
static TNimNode TMP564[9];
NTI184012.size = sizeof(uri184012);
NTI184012.kind = 18;
NTI184012.base = 0;
NTI184012.flags = 2;
TMP575[0] = &TMP564[1];
TMP564[1].kind = 1;
TMP564[1].offset = offsetof(uri184012, Scheme);
TMP564[1].typ = (&NTI149);
TMP564[1].name = "scheme";
TMP575[1] = &TMP564[2];
TMP564[2].kind = 1;
TMP564[2].offset = offsetof(uri184012, Username);
TMP564[2].typ = (&NTI149);
TMP564[2].name = "username";
TMP575[2] = &TMP564[3];
TMP564[3].kind = 1;
TMP564[3].offset = offsetof(uri184012, Password);
TMP564[3].typ = (&NTI149);
TMP564[3].name = "password";
TMP575[3] = &TMP564[4];
TMP564[4].kind = 1;
TMP564[4].offset = offsetof(uri184012, Hostname);
TMP564[4].typ = (&NTI149);
TMP564[4].name = "hostname";
TMP575[4] = &TMP564[5];
TMP564[5].kind = 1;
TMP564[5].offset = offsetof(uri184012, Port);
TMP564[5].typ = (&NTI149);
TMP564[5].name = "port";
TMP575[5] = &TMP564[6];
TMP564[6].kind = 1;
TMP564[6].offset = offsetof(uri184012, Path);
TMP564[6].typ = (&NTI149);
TMP564[6].name = "path";
TMP575[6] = &TMP564[7];
TMP564[7].kind = 1;
TMP564[7].offset = offsetof(uri184012, Query);
TMP564[7].typ = (&NTI149);
TMP564[7].name = "query";
TMP575[7] = &TMP564[8];
TMP564[8].kind = 1;
TMP564[8].offset = offsetof(uri184012, Anchor);
TMP564[8].typ = (&NTI149);
TMP564[8].name = "anchor";
TMP564[0].len = 8; TMP564[0].kind = 2; TMP564[0].sons = &TMP575[0];
NTI184012.node = &TMP564[0];
}

