/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_parseutils.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_parseutils.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct slice84662 slice84662;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct overflowerror3243 overflowerror3243;
typedef struct arithmeticerror3239 arithmeticerror3239;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
struct  slice84662  {
NI A;
NI B;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  arithmeticerror3239  {
  Exception Sup;
};
struct  overflowerror3243  {
  arithmeticerror3239 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
static N_INLINE(slice84662, HEX2EHEX2E_93499)(NI a_93503, NI b_93505);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_CHAR, tolower_92414)(NIM_CHAR c);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_NIMCALL(NI, rawparseint_93208)(NimStringDesc* s, NI64* b, NI start);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NI, skipuntil_92982)(NimStringDesc* s, NIM_CHAR until, NI start);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NI, parseuntil_93107)(NimStringDesc* s, NimStringDesc** token, NIM_CHAR until, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
STRING_LITERAL(TMP636, "overflow", 8);
STRING_LITERAL(TMP1861, "", 0);
extern TFrame* frameptr_16442;
extern TNimType NTI22601; /* ref OverflowError */
extern TNimType NTI3243; /* OverflowError */
extern tgcheap47416 gch_47444;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(slice84662, HEX2EHEX2E_93499)(NI a_93503, NI b_93505) {
	slice84662 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_93503;
	nimln(227, "system.nim");
	result.B = b_93505;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(NIM_CHAR, tolower_92414)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr("toLower", "parseutils.nim")
	result = 0;
	nimln(26, "parseutils.nim");
	nimln(26, "parseutils.nim");
	{
		NI TMP626;
		NI TMP627;
		nimln(26, "parseutils.nim");
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3;
		nimln(26, "parseutils.nim");
		nimln(26, "parseutils.nim");
		nimln(26, "parseutils.nim");
		nimln(26, "parseutils.nim");
		TMP626 = subInt(((NI) (((NU8)(c)))), 65);
		TMP627 = addInt(((NI) ((NI64)(TMP626))), 97);
		result = ((NIM_CHAR) (((NI)chckRange((NI64)(TMP627), 0, 255))));
	}
	goto LA1;
	LA3: ;
	{
		result = c;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, skipignorecase_92905)(NimStringDesc* s, NimStringDesc* token, NI start) {
	NI result;
	nimfr("skipIgnoreCase", "parseutils.nim")
	result = 0;
	{
		nimln(132, "parseutils.nim");
		while (1) {
			NIM_BOOL LOC3;
			NI TMP628;
			NIM_CHAR LOC5;
			NIM_CHAR LOC6;
			nimln(132, "parseutils.nim");
			LOC3 = 0;
			nimln(132, "parseutils.nim");
			nimln(132, "parseutils.nim");
			LOC3 = (result < token->Sup.len);
			if (!(LOC3)) goto LA4;
			nimln(133, "parseutils.nim");
			nimln(133, "parseutils.nim");
			nimln(133, "parseutils.nim");
			TMP628 = addInt(result, start);
			if ((NU)((NI64)(TMP628)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC5 = 0;
			LOC5 = tolower_92414(s->data[(NI64)(TMP628)]);
			nimln(133, "parseutils.nim");
			if ((NU)(result) > (NU)(token->Sup.len)) raiseIndexError();
			LOC6 = 0;
			LOC6 = tolower_92414(token->data[result]);
			LOC3 = ((NU8)(LOC5) == (NU8)(LOC6));
			LA4: ;
			if (!LOC3) goto LA2;
			nimln(133, "parseutils.nim");
			result = addInt(result, 1);
		} LA2: ;
	}
	nimln(134, "parseutils.nim");
	{
		nimln(134, "parseutils.nim");
		nimln(134, "parseutils.nim");
		nimln(134, "parseutils.nim");
		if (!!((result == token->Sup.len))) goto LA9;
		nimln(134, "parseutils.nim");
		result = 0;
	}
	LA9: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
	result = 0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (IL64(0) <= (NI64)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, rawparseint_93208)(NimStringDesc* s, NI64* b, NI start) {
	NI result;
	NI64 sign;
	NI i;
	nimfr("rawParseInt", "parseutils.nim")
	result = 0;
	nimln(194, "parseutils.nim");
	sign = IL64(-1);
	nimln(195, "parseutils.nim");
	i = start;
	nimln(196, "parseutils.nim");
	{
		nimln(196, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3;
		nimln(196, "parseutils.nim");
		i = addInt(i, 1);
	}
	goto LA1;
	LA3: ;
	{
		nimln(197, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(45))) goto LA6;
		nimln(198, "parseutils.nim");
		i = addInt(i, 1);
		nimln(199, "parseutils.nim");
		sign = IL64(1);
	}
	goto LA1;
	LA6: ;
	LA1: ;
	nimln(200, "parseutils.nim");
	{
		NI64 TMP634;
		NI TMP635;
		nimln(200, "parseutils.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;
		nimln(201, "parseutils.nim");
		(*b) = IL64(0);
		{
			nimln(202, "parseutils.nim");
			while (1) {
				NI64 TMP631;
				NI TMP632;
				NI64 TMP633;
				nimln(202, "parseutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA13;
				nimln(203, "parseutils.nim");
				nimln(203, "parseutils.nim");
				nimln(203, "parseutils.nim");
				TMP631 = mulInt64((*b), IL64(10));
				nimln(203, "parseutils.nim");
				nimln(203, "parseutils.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				TMP632 = subInt(((NI) (((NU8)(s->data[i])))), 48);
				TMP633 = subInt64((NI64)(TMP631), ((NI64) ((NI64)(TMP632))));
				(*b) = (NI64)(TMP633);
				nimln(204, "parseutils.nim");
				i = addInt(i, 1);
				{
					nimln(205, "parseutils.nim");
					while (1) {
						nimln(205, "parseutils.nim");
						if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
						if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA15;
						nimln(205, "parseutils.nim");
						i = addInt(i, 1);
					} LA15: ;
				}
			} LA13: ;
		}
		nimln(206, "parseutils.nim");
		nimln(206, "parseutils.nim");
		TMP634 = mulInt64((*b), sign);
		(*b) = (NI64)(TMP634);
		nimln(207, "parseutils.nim");
		nimln(207, "parseutils.nim");
		TMP635 = subInt(i, start);
		result = (NI64)(TMP635);
	}
	LA10: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start) {
	NI result;
	NI64 res;
	nimfr("parseBiggestInt", "parseutils.nim")
	result = 0;
	res = 0;
	nimln(218, "parseutils.nim");
	result = rawparseint_93208(s, (&res), start);
	nimln(219, "parseutils.nim");
	(*number) = res;
	popFrame();
	return result;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start) {
	NI result;
	NI64 res;
	nimfr("parseInt", "parseutils.nim")
	result = 0;
	res = 0;
	nimln(227, "parseutils.nim");
	result = npuParseBiggestInt(s, (&res), start);
	nimln(228, "parseutils.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		overflowerror3243* e_93369;
		NimStringDesc* LOC9;
		nimln(228, "parseutils.nim");
		LOC3 = 0;
		LOC3 = NIM_FALSE;
		if (!(LOC3)) goto LA4;
		nimln(229, "parseutils.nim");
		LOC5 = 0;
		nimln(229, "parseutils.nim");
		LOC5 = (res < (IL64(-9223372036854775807) - IL64(1)));
		if (LOC5) goto LA6;
		nimln(229, "parseutils.nim");
		LOC5 = (IL64(9223372036854775807) < res);
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		e_93369 = 0;
		nimln(2149, "system.nim");
		e_93369 = (overflowerror3243*) newObj((&NTI22601), sizeof(overflowerror3243));
		(*e_93369).Sup.Sup.Sup.m_type = (&NTI3243);
		nimln(2150, "system.nim");
		LOC9 = 0;
		LOC9 = (*e_93369).Sup.Sup.message; (*e_93369).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP636));
		if (LOC9) nimGCunrefNoCycle(LOC9);
		nimln(230, "parseutils.nim");
		raiseException((Exception*)e_93369, "OverflowError");
	}
	goto LA1;
	LA7: ;
	{
		nimln(232, "parseutils.nim");
		(*number) = ((NI) (res));
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(NI, skipuntil_92982)(NimStringDesc* s, NIM_CHAR until, NI start) {
	NI result;
	nimfr("skipUntil", "parseutils.nim")
	result = 0;
	{
		nimln(146, "parseutils.nim");
		while (1) {
			NIM_BOOL LOC3;
			NI TMP1857;
			NI TMP1858;
			nimln(146, "parseutils.nim");
			LOC3 = 0;
			nimln(146, "parseutils.nim");
			nimln(146, "parseutils.nim");
			nimln(146, "parseutils.nim");
			TMP1857 = addInt(result, start);
			if ((NU)((NI64)(TMP1857)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC3 = !(((NU8)(s->data[(NI64)(TMP1857)]) == (NU8)(until)));
			if (!(LOC3)) goto LA4;
			nimln(146, "parseutils.nim");
			nimln(146, "parseutils.nim");
			nimln(146, "parseutils.nim");
			TMP1858 = addInt(result, start);
			if ((NU)((NI64)(TMP1858)) > (NU)(s->Sup.len)) raiseIndexError();
			LOC3 = !(((NU8)(s->data[(NI64)(TMP1858)]) == (NU8)(0)));
			LA4: ;
			if (!LOC3) goto LA2;
			nimln(146, "parseutils.nim");
			result = addInt(result, 1);
		} LA2: ;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, parseuntil_93107)(NimStringDesc* s, NimStringDesc** token, NIM_CHAR until, NI start) {
	NI result;
	NI i;
	NI TMP1862;
	NI TMP1863;
	nimfr("parseUntil", "parseutils.nim")
	result = 0;
	nimln(168, "parseutils.nim");
	i = start;
	{
		nimln(169, "parseutils.nim");
		while (1) {
			NIM_BOOL LOC3;
			nimln(169, "parseutils.nim");
			LOC3 = 0;
			nimln(169, "parseutils.nim");
			nimln(169, "parseutils.nim");
			LOC3 = (i < s->Sup.len);
			if (!(LOC3)) goto LA4;
			nimln(169, "parseutils.nim");
			nimln(169, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			LOC3 = !(((NU8)(s->data[i]) == (NU8)(until)));
			LA4: ;
			if (!LOC3) goto LA2;
			nimln(169, "parseutils.nim");
			i = addInt(i, 1);
		} LA2: ;
	}
	nimln(170, "parseutils.nim");
	nimln(170, "parseutils.nim");
	TMP1862 = subInt(i, start);
	result = (NI64)(TMP1862);
	nimln(171, "parseutils.nim");
	nimln(171, "parseutils.nim");
	nimln(171, "parseutils.nim");
	TMP1863 = subInt(i, 1);
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI64)(TMP1863)));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, capturebetween_93190)(NimStringDesc* s, NIM_CHAR first, NIM_CHAR second, NI start) {
	NimStringDesc* result;
	NI i;
	NI LOC1;
	NI TMP1859;
	NI TMP1860;
	NIM_CHAR LOC2;
	NI LOC8;
	nimfr("captureBetween", "parseutils.nim")
	result = 0;
	nimln(186, "parseutils.nim");
	nimln(186, "parseutils.nim");
	nimln(186, "parseutils.nim");
	nimln(186, "parseutils.nim");
	LOC1 = 0;
	LOC1 = skipuntil_92982(s, first, start);
	TMP1859 = addInt(LOC1, 1);
	TMP1860 = addInt((NI64)(TMP1859), start);
	i = (NI64)(TMP1860);
	nimln(187, "parseutils.nim");
	result = copyString(((NimStringDesc*) &TMP1861));
	nimln(188, "parseutils.nim");
	nimln(188, "parseutils.nim");
	LOC2 = 0;
	nimln(188, "parseutils.nim");
	{
		nimln(188, "parseutils.nim");
		if (!((NU8)(second) == (NU8)(0))) goto LA5;
		LOC2 = first;
	}
	goto LA3;
	LA5: ;
	{
		LOC2 = second;
	}
	LA3: ;
	LOC8 = 0;
	LOC8 = parseuntil_93107(s, (&result), LOC2, i);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void) {
}

