/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_asyncio.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_asyncio.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <setjmp.h>

#include <sys/socket.h>

#include <sys/select.h>
typedef struct delegateobj207205 delegateobj207205;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct asyncsocketobj207215 asyncsocketobj207215;
typedef struct tsocketimpl193807 tsocketimpl193807;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY161264 TY161264;
typedef struct TY161267 TY161267;
typedef struct tcell45335 tcell45335;
typedef struct tcellset45347 tcellset45347;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct slice84662 slice84662;
typedef struct TY208642 TY208642;
typedef struct dispatcherobj207211 dispatcherobj207211;
typedef struct TY207242 TY207242;
typedef struct indexerror3255 indexerror3255;
typedef struct TY202215 TY202215;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
typedef N_NIMCALL_PTR(void, TY207220) (TNimObject* h);
typedef N_NIMCALL_PTR(void, TY207224) (TNimObject* h);
typedef N_NIMCALL_PTR(void, TY207228) (TNimObject* h);
typedef N_NIMCALL_PTR(NIM_BOOL, TY207232) (TNimObject* h);
typedef N_NIMCALL_PTR(void, TY207237) (TNimObject* h);
struct  delegateobj207205  {
int Fd;
TNimObject* Deleval;
TY207220 Handleread;
TY207224 Handlewrite;
TY207228 Handleerror;
TY207232 Hasdatabuffered;
NIM_BOOL Open;
TY207237 Task;
NU8 Mode;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (asyncsocketobj207215* s, void* ClEnv);
void* ClEnv;
} TY207246;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  asyncsocketobj207215  {
  TNimObject Sup;
tsocketimpl193807* Socket;
NU8 Info;
TY207246 Handleread;
TY207246 Handlewrite;
TY207246 Handleconnect;
TY207246 Handleaccept;
TY207246 Handletask;
NimStringDesc* Linebuffer;
NimStringDesc* Sendbuffer;
NIM_BOOL Sslneedaccept;
NU8 Proto;
delegateobj207205* Deleg;
};
struct TY161264 {
void* Field0;
TY161267* Field1;
};
typedef N_CLOSURE_PTR(void, TMP807) (asyncsocketobj207215* s, void* ClEnv);
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
typedef N_CLOSURE_PTR(void, TMP809) (asyncsocketobj207215* s, void* ClEnv);
typedef N_CLOSURE_PTR(void, TMP810) (asyncsocketobj207215* s, void* ClEnv);
typedef N_CLOSURE_PTR(void, TMP811) (asyncsocketobj207215* s, void* ClEnv);
typedef N_CLOSURE_PTR(void, TMP814) (asyncsocketobj207215* s);
typedef N_CLOSURE_PTR(void, TMP815) (asyncsocketobj207215* s);
typedef N_CLOSURE_PTR(void, TMP816) (asyncsocketobj207215* s);
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY15009;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY15009 raiseAction;
};
struct  slice84662  {
NI A;
NI B;
};
typedef N_CLOSURE_PTR(void, TMP820) (asyncsocketobj207215* s);
typedef N_CLOSURE_PTR(void, TMP821) (asyncsocketobj207215* s);
typedef N_CLOSURE_PTR(void, TMP822) (asyncsocketobj207215* s);
typedef NIM_CHAR TY175208[4001];
struct  tsocketimpl193807  {
int Fd;
NIM_BOOL Isbuffered;
union {
struct {TY175208 Buffer;
NI Currpos;
NI Buflen;
} S1;
} isbufferedU;
NIM_BOOL Nonblocking;
};
struct TY208642 {
asyncsocketobj207215* Field0;
NimStringDesc* Field1;
};
struct  dispatcherobj207211  {
TY207242* Delegates;
};
struct  indexerror3255  {
  Exception Sup;
};
typedef tsocketimpl193807* TY208923[1];
struct TY161267 {
char dummy;
};
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY207242 {
  TGenericSeq Sup;
  delegateobj207205* data[SEQ_DECL_SIZE];
};
struct TY202215 {
  TGenericSeq Sup;
  tsocketimpl193807* data[SEQ_DECL_SIZE];
};
N_NIMCALL(delegateobj207205*, newdelegate_207290)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP794)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, HEX3Aanonymous_207309)(TNimObject* h);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, HEX3Aanonymous_207312)(TNimObject* h);
N_NIMCALL(void, HEX3Aanonymous_207315)(TNimObject* h);
N_NIMCALL(NIM_BOOL, HEX3Aanonymous_207318)(TNimObject* h);
N_NIMCALL(void, HEX3Aanonymous_207322)(TNimObject* h);
N_NIMCALL(asyncsocketobj207215*, newasyncsocket_207346)(void);
N_NIMCALL(void, TMP806)(void* p, NI op);
N_NIMCALL(void, HEX3Aanonymous_207365)(asyncsocketobj207215* s);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51425)(tcell45335* c);
static N_INLINE(NIM_BOOL, canbecycleroot_49067)(tcell45335* c);
static N_INLINE(void, rtladdcycleroot_49829)(tcell45335* c);
N_NOINLINE(void, incl_46071)(tcellset45347* s, tcell45335* cell);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, decref_51004)(tcell45335* c);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, HEX3Aanonymous_207368)(asyncsocketobj207215* s);
N_NIMCALL(void, HEX3Aanonymous_207371)(asyncsocketobj207215* s);
N_NIMCALL(void, HEX3Aanonymous_207374)(asyncsocketobj207215* s);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(asyncsocketobj207215*, asyncsocket_207400)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
N_NIMCALL(tsocketimpl193807*, socket_194804)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseoserror_123009)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_123041)(void);
N_NIMCALL(void, setblocking_197411)(tsocketimpl193807* s, NIM_BOOL blocking);
N_NIMCALL(asyncsocketobj207215*, toasyncsocket_207429)(tsocketimpl193807* sock, NU8 state);
N_NIMCALL(void, asyncsockhandleread_207449)(TNimObject* h);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, asyncsockhandlewrite_207631)(TNimObject* h);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NI, sendasync_204229)(tsocketimpl193807* socket, NimStringDesc* data);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_84655)(NimStringDesc* s, slice84662 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(slice84662, HEX2EHEX2E_93499)(NI a_93503, NI b_93505);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, asyncsocktask_208001)(TNimObject* h);
N_NIMCALL(delegateobj207205*, todelegate_208207)(asyncsocketobj207215* sock);
N_NIMCALL(int, getfd_205419)(tsocketimpl193807* socket);
N_NIMCALL(NIM_BOOL, HEX3Aanonymous_208211)(TNimObject* h);
N_NIMCALL(NIM_BOOL, hasdatabuffered_200939)(tsocketimpl193807* s);
N_NIMCALL(void, connect_208238)(asyncsocketobj207215* sock, NimStringDesc* name, NU16 port, NU8 af);
N_NIMCALL(void, connectasync_199823)(tsocketimpl193807* socket, NimStringDesc* name, NU16 port, NU8 af);
N_NIMCALL(void, close_207625)(asyncsocketobj207215* sock);
N_NIMCALL(void, close_197678)(tsocketimpl193807* socket);
N_NIMCALL(void, bindaddr_208293)(asyncsocketobj207215* sock, NU16 port, NimStringDesc* address);
N_NIMCALL(void, bindaddr_195974)(tsocketimpl193807* socket, NU16 port, NimStringDesc* address);
N_NIMCALL(void, listen_208330)(asyncsocketobj207215* sock);
N_NIMCALL(void, listen_195809)(tsocketimpl193807* socket, int backlog);
N_NIMCALL(void, acceptaddr_208356)(asyncsocketobj207215* server, asyncsocketobj207215** client, NimStringDesc** address);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, acceptaddr_196448)(tsocketimpl193807* server, tsocketimpl193807** client, NimStringDesc** address);
N_NIMCALL(void, raisesocketerror_195201)(tsocketimpl193807* socket, NI err, NIM_BOOL async);
N_NIMCALL(void, accept_208626)(asyncsocketobj207215* server, asyncsocketobj207215** client);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, acceptaddr_208639)(asyncsocketobj207215* server, TY208642* Result);
N_NIMCALL(asyncsocketobj207215*, accept_208658)(asyncsocketobj207215* server);
N_NIMCALL(dispatcherobj207211*, newdispatcher_208687)(void);
N_NIMCALL(void, TMP827)(void* p, NI op);
N_NIMCALL(void, TMP828)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, register_208732)(dispatcherobj207211* d, delegateobj207205* deleg);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(delegateobj207205*, register_208760)(dispatcherobj207211* d, asyncsocketobj207215* sock);
N_NIMCALL(void, del_208816)(TY207242** x_208824, NI i_208828);
N_NIMCALL(void, unregister_208771)(dispatcherobj207211* d, delegateobj207205* deleg);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NIM_BOOL, contains_208929)(tsocketimpl193807** a_208935, NI a_208935Len0, tsocketimpl193807* item_208938);
static N_INLINE(NI, find_208941)(tsocketimpl193807** a_208946, NI a_208946Len0, tsocketimpl193807* item_208948);
N_NIMCALL(NIM_BOOL, iswriteable_208903)(asyncsocketobj207215* s);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NI, selectwrite_201244)(TY202215** writefds, NI timeout);
N_NIMCALL(tsocketimpl193807*, getsocket_209046)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, isconnected_209056)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, islistening_209075)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, isconnecting_209094)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, isclosed_209113)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, issenddatabuffered_209132)(asyncsocketobj207215* s);
N_NIMCALL(void, sethandlewrite_209142)(asyncsocketobj207215* s, TY207246 handlewrite);
N_NIMCALL(void, delhandlewrite_209155)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, recvline_209167)(asyncsocketobj207215* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NU8, recvlineasync_202685)(tsocketimpl193807* socket, NimStringDesc** line);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NIM_BOOL, readline_209197)(asyncsocketobj207215* s, NimStringDesc** line);
N_NIMCALL(NU8, readlineasync_202714)(tsocketimpl193807* socket, NimStringDesc** line);
N_NIMCALL(void, send_209224)(asyncsocketobj207215* sock, NimStringDesc* data);
N_NIMCALL(struct timeval, timevalfrommilliseconds_209418)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void, createfdset_209433)(fd_set* fd, TY207242* s, NI* m);
N_NIMCALL(void, prunesocketset_209656)(TY207242** s, fd_set* fd);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NI, select_209739)(TY207242** readfds, TY207242** writefds, TY207242** exceptfds, NI timeout);
static N_INLINE(NIM_BOOL, contains_210085)(delegateobj207205** a_210091, NI a_210091Len0, delegateobj207205* item_210094);
static N_INLINE(NI, find_210097)(delegateobj207205** a_210102, NI a_210102Len0, delegateobj207205* item_210104);
N_NIMCALL(NIM_BOOL, poll_209812)(dispatcherobj207211* d, NI timeout);
N_NIMCALL(NI, len_210311)(dispatcherobj207211* disp);
static NIM_CONST TY207246 TMP808 = {NIM_NIL,NIM_NIL};
STRING_LITERAL(TMP812, "", 0);
STRING_LITERAL(TMP824, "client != nil ", 14);
STRING_LITERAL(TMP832, "Could not find delegate.", 24);
STRING_LITERAL(TMP846, "\015\012", 2);
STRING_LITERAL(TMP847, "bytesSent >= 0 ", 15);
STRING_LITERAL(TMP852, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
TNimType NTI207205; /* DelegateObj */
extern TNimType NTI5611; /* cint */
extern TNimType NTI3213; /* RootRef */
TNimType NTI207220; /* proc (RootRef){.gcsafe.} */
TNimType NTI207224; /* proc (RootRef){.gcsafe.} */
TNimType NTI207228; /* proc (RootRef){.gcsafe.} */
TNimType NTI207232; /* proc (RootRef): bool{.gcsafe.} */
extern TNimType NTI138; /* bool */
TNimType NTI207237; /* proc (RootRef){.gcsafe.} */
extern TNimType NTI12606; /* FileMode */
TNimType NTI207207; /* Delegate */
extern TFrame* frameptr_16442;
extern TNimType NTI3211; /* RootObj */
TNimType NTI207215; /* AsyncSocketObj */
extern TNimType NTI193809; /* Socket */
TNimType NTI207217; /* SocketStatus */
TNimType NTI207246; /* tuple[pointer, ref tuple[]] */
extern TNimType NTI153; /* pointer */
extern TNimType NTI161266; /* ref tuple[] */
extern TNimType NTI149; /* string */
extern TNimType NTI193817; /* Protocol */
TNimType NTI207213; /* AsyncSocket */
extern tgcheap47416 gch_47444;
extern TSafePoint* exchandler_16443;
extern TNimType NTI3233; /* OSError */
extern Exception* currexception_16445;
TNimType NTI207211; /* DispatcherObj */
TNimType NTI207242; /* seq[Delegate] */
TNimType NTI207209; /* Dispatcher */
extern TNimType NTI21001; /* ref IndexError */
extern TNimType NTI3255; /* IndexError */
extern TNimType NTI202215; /* seq[Socket] */
N_NIMCALL(void, TMP794)(void* p, NI op) {
	delegateobj207205* a;
	a = (delegateobj207205*)p;
	nimGCvisit((void*)(*a).Deleval, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

N_NIMCALL(void, HEX3Aanonymous_207309)(TNimObject* h) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

N_NIMCALL(void, HEX3Aanonymous_207312)(TNimObject* h) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

N_NIMCALL(void, HEX3Aanonymous_207315)(TNimObject* h) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

N_NIMCALL(NIM_BOOL, HEX3Aanonymous_207318)(TNimObject* h) {
	NIM_BOOL result;
	nimfr(":anonymous", "asyncio.nim")
	result = 0;
	nimln(162, "asyncio.nim");
	nimln(162, "asyncio.nim");
	result = NIM_FALSE;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, HEX3Aanonymous_207322)(TNimObject* h) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

N_NIMCALL(delegateobj207205*, newdelegate_207290)(void) {
	delegateobj207205* result;
	nimfr("newDelegate", "asyncio.nim")
	result = 0;
	nimln(158, "asyncio.nim");
	result = (delegateobj207205*) newObj((&NTI207207), sizeof(delegateobj207205));
	nimln(159, "asyncio.nim");
	(*result).Handleread = HEX3Aanonymous_207309;
	nimln(160, "asyncio.nim");
	(*result).Handlewrite = HEX3Aanonymous_207312;
	nimln(161, "asyncio.nim");
	(*result).Handleerror = HEX3Aanonymous_207315;
	nimln(162, "asyncio.nim");
	(*result).Hasdatabuffered = HEX3Aanonymous_207318;
	nimln(163, "asyncio.nim");
	(*result).Task = HEX3Aanonymous_207322;
	nimln(164, "asyncio.nim");
	(*result).Mode = ((NU8) 0);
	popFrame();
	return result;
}
N_NIMCALL(void, TMP806)(void* p, NI op) {
	asyncsocketobj207215* a;
	a = (asyncsocketobj207215*)p;
	nimGCvisit((void*)(*a).Socket, op);
	nimGCvisit((void*)(*a).Handleread.ClEnv, op);
	nimGCvisit((void*)(*a).Handlewrite.ClEnv, op);
	nimGCvisit((void*)(*a).Handleconnect.ClEnv, op);
	nimGCvisit((void*)(*a).Handleaccept.ClEnv, op);
	nimGCvisit((void*)(*a).Handletask.ClEnv, op);
	nimGCvisit((void*)(*a).Linebuffer, op);
	nimGCvisit((void*)(*a).Sendbuffer, op);
	nimGCvisit((void*)(*a).Deleg, op);
}

N_NIMCALL(void, HEX3Aanonymous_207365)(asyncsocketobj207215* s) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_49067)(tcell45335* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49829)(tcell45335* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_46071((&gch_47444.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51425)(tcell45335* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_49067(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49829(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, decref_51004)(tcell45335* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_49067(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49829(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45335* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_49046(src);
		incref_51425(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45335* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_49046((*dest));
		decref_51004(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, HEX3Aanonymous_207368)(asyncsocketobj207215* s) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

N_NIMCALL(void, HEX3Aanonymous_207371)(asyncsocketobj207215* s) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

N_NIMCALL(void, HEX3Aanonymous_207374)(asyncsocketobj207215* s) {
	nimfr(":anonymous", "asyncio.nim")
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(asyncsocketobj207215*, newasyncsocket_207346)(void) {
	asyncsocketobj207215* result;
	TY207246 LOC1;
	TY207246 LOC2;
	TY207246 LOC3;
	TY207246 LOC4;
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	nimfr("newAsyncSocket", "asyncio.nim")
	result = 0;
	nimln(167, "asyncio.nim");
	result = (asyncsocketobj207215*) newObj((&NTI207213), sizeof(asyncsocketobj207215));
	(*result).Sup.m_type = (&NTI207215);
	nimln(168, "asyncio.nim");
	(*result).Info = ((NU8) 0);
	nimln(170, "asyncio.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((TMP807) (HEX3Aanonymous_207365)); LOC1.ClEnv = NIM_NIL;
	asgnRef((void**) (&(*result).Handleread.ClEnv), LOC1.ClEnv);
	(*result).Handleread.ClPrc = LOC1.ClPrc;
	nimln(171, "asyncio.nim");
	asgnRef((void**) (&(*result).Handlewrite.ClEnv), TMP808.ClEnv);
	(*result).Handlewrite.ClPrc = TMP808.ClPrc;
	nimln(172, "asyncio.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = ((TMP809) (HEX3Aanonymous_207368)); LOC2.ClEnv = NIM_NIL;
	asgnRef((void**) (&(*result).Handleconnect.ClEnv), LOC2.ClEnv);
	(*result).Handleconnect.ClPrc = LOC2.ClPrc;
	nimln(173, "asyncio.nim");
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.ClPrc = ((TMP810) (HEX3Aanonymous_207371)); LOC3.ClEnv = NIM_NIL;
	asgnRef((void**) (&(*result).Handleaccept.ClEnv), LOC3.ClEnv);
	(*result).Handleaccept.ClPrc = LOC3.ClPrc;
	nimln(174, "asyncio.nim");
	memset((void*)(&LOC4), 0, sizeof(LOC4));
	LOC4.ClPrc = ((TMP811) (HEX3Aanonymous_207374)); LOC4.ClEnv = NIM_NIL;
	asgnRef((void**) (&(*result).Handletask.ClEnv), LOC4.ClEnv);
	(*result).Handletask.ClPrc = LOC4.ClPrc;
	nimln(176, "asyncio.nim");
	LOC5 = 0;
	LOC5 = (*result).Linebuffer; (*result).Linebuffer = copyStringRC1(((NimStringDesc*) &TMP812));
	if (LOC5) nimGCunrefNoCycle(LOC5);
	nimln(177, "asyncio.nim");
	LOC6 = 0;
	LOC6 = (*result).Sendbuffer; (*result).Sendbuffer = copyStringRC1(((NimStringDesc*) &TMP812));
	if (LOC6) nimGCunrefNoCycle(LOC6);
	popFrame();
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(asyncsocketobj207215*, asyncsocket_207400)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered) {
	asyncsocketobj207215* result;
	nimfr("asyncSocket", "asyncio.nim")
	result = 0;
	nimln(184, "asyncio.nim");
	result = newasyncsocket_207346();
	nimln(185, "asyncio.nim");
	asgnRefNoCycle((void**) (&(*result).Socket), socket_194804(domain, typ, protocol, buffered));
	nimln(186, "asyncio.nim");
	(*result).Proto = protocol;
	nimln(187, "asyncio.nim");
	{
		NI32 LOC5;
		nimln(187, "asyncio.nim");
		if (!((*result).Socket == NIM_NIL)) goto LA3;
		nimln(187, "asyncio.nim");
		nimln(187, "asyncio.nim");
		LOC5 = 0;
		LOC5 = oslasterror_123041();
		raiseoserror_123009(LOC5);
	}
	LA3: ;
	nimln(188, "asyncio.nim");
	setblocking_197411((*result).Socket, NIM_FALSE);
	popFrame();
	return result;
}

N_NIMCALL(asyncsocketobj207215*, toasyncsocket_207429)(tsocketimpl193807* sock, NU8 state) {
	asyncsocketobj207215* result;
	nimfr("toAsyncSocket", "asyncio.nim")
	result = 0;
	nimln(215, "asyncio.nim");
	result = newasyncsocket_207346();
	nimln(216, "asyncio.nim");
	asgnRefNoCycle((void**) (&(*result).Socket), sock);
	nimln(217, "asyncio.nim");
	nimln(217, "asyncio.nim");
	{
		nimln(217, "asyncio.nim");
		if (!(state == ((NU8) 5))) goto LA3;
		(*result).Proto = ((NU8) 17);
	}
	goto LA1;
	LA3: ;
	{
		(*result).Proto = ((NU8) 6);
	}
	LA1: ;
	nimln(218, "asyncio.nim");
	setblocking_197411((*result).Socket, NIM_FALSE);
	nimln(219, "asyncio.nim");
	(*result).Info = state;
	popFrame();
	return result;
}

N_NIMCALL(void, asyncsockhandleread_207449)(TNimObject* h) {
	nimfr("asyncSockHandleRead", "asyncio.nim")
	nimln(227, "asyncio.nim");
	{
		nimln(227, "asyncio.nim");
		nimln(227, "asyncio.nim");
		if (h) chckObj((*h).m_type, (&NTI207215));
		if (!!(((*((asyncsocketobj207215*) (h))).Info == ((NU8) 3)))) goto LA3;
		nimln(228, "asyncio.nim");
		{
			nimln(228, "asyncio.nim");
			nimln(228, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			if (!!(((*((asyncsocketobj207215*) (h))).Info == ((NU8) 1)))) goto LA7;
			nimln(229, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			if (h) chckObj((*h).m_type, (&NTI207215));
			(*((asyncsocketobj207215*) (h))).Handleread.ClEnv? (*((asyncsocketobj207215*) (h))).Handleread.ClPrc(((asyncsocketobj207215*) (h)), (*((asyncsocketobj207215*) (h))).Handleread.ClEnv):((TMP814)((*((asyncsocketobj207215*) (h))).Handleread.ClPrc))(((asyncsocketobj207215*) (h)));
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		nimln(231, "asyncio.nim");
		if (h) chckObj((*h).m_type, (&NTI207215));
		if (h) chckObj((*h).m_type, (&NTI207215));
		(*((asyncsocketobj207215*) (h))).Handleaccept.ClEnv? (*((asyncsocketobj207215*) (h))).Handleaccept.ClPrc(((asyncsocketobj207215*) (h)), (*((asyncsocketobj207215*) (h))).Handleaccept.ClEnv):((TMP815)((*((asyncsocketobj207215*) (h))).Handleaccept.ClPrc))(((asyncsocketobj207215*) (h)));
	}
	LA1: ;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_16443;
	exchandler_16443 = s;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_84655)(NimStringDesc* s, slice84662 x) {
	NimStringDesc* result;
	NI LOC1;
	NI LOC7;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2773, "system.nim");
	nimln(2773, "system.nim");
	LOC1 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.A)) goto LA4;
		LOC1 = x.A;
	}
	goto LA2;
	LA4: ;
	{
		NI TMP818;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP818 = addInt(s->Sup.len, x.A);
		LOC1 = (NI64)(TMP818);
	}
	LA2: ;
	LOC7 = 0;
	nimln(2752, "system.nim");
	{
		nimln(2752, "system.nim");
		if (!(0 <= x.B)) goto LA10;
		LOC7 = x.B;
	}
	goto LA8;
	LA10: ;
	{
		NI TMP819;
		nimln(2752, "system.nim");
		nimln(2752, "system.nim");
		TMP819 = addInt(s->Sup.len, x.B);
		LOC7 = (NI64)(TMP819);
	}
	LA8: ;
	result = copyStrLast(s, LOC1, LOC7);
	popFrame();
	return result;
}

static N_INLINE(slice84662, HEX2EHEX2E_93499)(NI a_93503, NI b_93505) {
	slice84662 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(226, "system.nim");
	result.A = a_93503;
	nimln(227, "system.nim");
	result.B = b_93505;
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_16443 = (*exchandler_16443).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_16442 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2619, "system.nim");
	result = currexception_16445;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_16445), (*currexception_16445).parent);
}

N_NIMCALL(void, asyncsockhandlewrite_207631)(TNimObject* h) {
	nimfr("asyncSockHandleWrite", "asyncio.nim")
	nimln(240, "asyncio.nim");
	{
		nimln(240, "asyncio.nim");
		if (h) chckObj((*h).m_type, (&NTI207215));
		if (!((*((asyncsocketobj207215*) (h))).Info == ((NU8) 1))) goto LA3;
		nimln(241, "asyncio.nim");
		if (h) chckObj((*h).m_type, (&NTI207215));
		if (h) chckObj((*h).m_type, (&NTI207215));
		(*((asyncsocketobj207215*) (h))).Handleconnect.ClEnv? (*((asyncsocketobj207215*) (h))).Handleconnect.ClPrc(((asyncsocketobj207215*) (h)), (*((asyncsocketobj207215*) (h))).Handleconnect.ClEnv):((TMP816)((*((asyncsocketobj207215*) (h))).Handleconnect.ClPrc))(((asyncsocketobj207215*) (h)));
		nimln(242, "asyncio.nim");
		if (h) chckObj((*h).m_type, (&NTI207215));
		(*((asyncsocketobj207215*) (h))).Info = ((NU8) 2);
		nimln(244, "asyncio.nim");
		{
			nimln(244, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			if (!((*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc == TMP808.ClPrc && (*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv == TMP808.ClEnv)) goto LA7;
			nimln(245, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			(*(*((asyncsocketobj207215*) (h))).Deleg).Mode = ((NU8) 0);
		}
		goto LA5;
		LA7: ;
		{
			nimln(247, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			(*(*((asyncsocketobj207215*) (h))).Deleg).Mode = ((NU8) 2);
		}
		LA5: ;
	}
	goto LA1;
	LA3: ;
	{
		nimln(249, "asyncio.nim");
		{
			asyncsocketobj207215* sock;
			TSafePoint TMP817;
			nimln(249, "asyncio.nim");
			nimln(249, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			if (!!((((*((asyncsocketobj207215*) (h))).Sendbuffer) && ((*((asyncsocketobj207215*) (h))).Sendbuffer)->Sup.len == 0))) goto LA13;
			nimln(250, "asyncio.nim");
			if (h) chckObj((*h).m_type, (&NTI207215));
			sock = ((asyncsocketobj207215*) (h));
			nimln(251, "asyncio.nim");
			pushSafePoint(&TMP817);
			TMP817.status = _setjmp(TMP817.context);
			if (TMP817.status == 0) {
				NI bytessent;
				nimln(252, "asyncio.nim");
				bytessent = sendasync_204229((*sock).Socket, (*sock).Sendbuffer);
				nimln(253, "asyncio.nim");
				{
					nimln(253, "asyncio.nim");
					if (!(bytessent == 0)) goto LA18;
				}
				goto LA16;
				LA18: ;
				{
					slice84662 LOC23;
					nimln(258, "asyncio.nim");
					nimln(258, "asyncio.nim");
					nimln(258, "asyncio.nim");
					if (!!((bytessent == (*sock).Sendbuffer->Sup.len))) goto LA21;
					nimln(259, "asyncio.nim");
					nimln(259, "asyncio.nim");
					LOC23 = HEX2EHEX2E_93499(bytessent, -1);
					asgnRefNoCycle((void**) (&(*sock).Sendbuffer), HEX5BHEX5D_84655((*sock).Sendbuffer, LOC23));
				}
				goto LA16;
				LA21: ;
				{
					NimStringDesc* LOC27;
					nimln(260, "asyncio.nim");
					nimln(260, "asyncio.nim");
					if (!(bytessent == (*sock).Sendbuffer->Sup.len)) goto LA25;
					nimln(261, "asyncio.nim");
					LOC27 = 0;
					LOC27 = (*sock).Sendbuffer; (*sock).Sendbuffer = copyStringRC1(((NimStringDesc*) &TMP812));
					if (LOC27) nimGCunrefNoCycle(LOC27);
				}
				goto LA16;
				LA25: ;
				LA16: ;
				nimln(263, "asyncio.nim");
				{
					nimln(263, "asyncio.nim");
					nimln(263, "asyncio.nim");
					if (h) chckObj((*h).m_type, (&NTI207215));
					if (!!(((*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc == TMP808.ClPrc && (*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv == TMP808.ClEnv))) goto LA30;
					nimln(264, "asyncio.nim");
					if (h) chckObj((*h).m_type, (&NTI207215));
					if (h) chckObj((*h).m_type, (&NTI207215));
					(*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv? (*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc(((asyncsocketobj207215*) (h)), (*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv):((TMP820)((*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc))(((asyncsocketobj207215*) (h)));
				}
				LA30: ;
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&F);
				if (isObj(getCurrentException()->Sup.m_type, (&NTI3233))) {
					TMP817.status = 0;
					nimln(267, "asyncio.nim");
					close_207625(sock);
					popCurrentException();
				}
			}
			if (TMP817.status != 0) reraiseException();
		}
		goto LA11;
		LA13: ;
		{
			nimln(269, "asyncio.nim");
			{
				nimln(269, "asyncio.nim");
				nimln(269, "asyncio.nim");
				if (h) chckObj((*h).m_type, (&NTI207215));
				if (!!(((*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc == TMP808.ClPrc && (*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv == TMP808.ClEnv))) goto LA37;
				nimln(270, "asyncio.nim");
				if (h) chckObj((*h).m_type, (&NTI207215));
				if (h) chckObj((*h).m_type, (&NTI207215));
				(*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv? (*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc(((asyncsocketobj207215*) (h)), (*((asyncsocketobj207215*) (h))).Handlewrite.ClEnv):((TMP821)((*((asyncsocketobj207215*) (h))).Handlewrite.ClPrc))(((asyncsocketobj207215*) (h)));
			}
			goto LA35;
			LA37: ;
			{
				nimln(272, "asyncio.nim");
				if (h) chckObj((*h).m_type, (&NTI207215));
				(*(*((asyncsocketobj207215*) (h))).Deleg).Mode = ((NU8) 0);
			}
			LA35: ;
		}
		LA11: ;
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, asyncsocktask_208001)(TNimObject* h) {
	nimfr("asyncSockTask", "asyncio.nim")
	nimln(293, "asyncio.nim");
	if (h) chckObj((*h).m_type, (&NTI207215));
	if (h) chckObj((*h).m_type, (&NTI207215));
	(*((asyncsocketobj207215*) (h))).Handletask.ClEnv? (*((asyncsocketobj207215*) (h))).Handletask.ClPrc(((asyncsocketobj207215*) (h)), (*((asyncsocketobj207215*) (h))).Handletask.ClEnv):((TMP822)((*((asyncsocketobj207215*) (h))).Handletask.ClPrc))(((asyncsocketobj207215*) (h)));
	popFrame();
}

N_NIMCALL(NIM_BOOL, HEX3Aanonymous_208211)(TNimObject* h) {
	NIM_BOOL result;
	nimfr(":anonymous", "asyncio.nim")
	result = 0;
	nimln(309, "asyncio.nim");
	nimln(309, "asyncio.nim");
	if (h) chckObj((*h).m_type, (&NTI207215));
	result = hasdatabuffered_200939((*((asyncsocketobj207215*) (h))).Socket);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(delegateobj207205*, todelegate_208207)(asyncsocketobj207215* sock) {
	delegateobj207205* result;
	nimfr("toDelegate", "asyncio.nim")
	result = 0;
	nimln(296, "asyncio.nim");
	result = newdelegate_207290();
	nimln(297, "asyncio.nim");
	asgnRef((void**) (&(*result).Deleval), &sock->Sup);
	nimln(298, "asyncio.nim");
	(*result).Fd = getfd_205419((*sock).Socket);
	nimln(300, "asyncio.nim");
	(*result).Mode = ((NU8) 2);
	nimln(301, "asyncio.nim");
	(*result).Handleread = asyncsockhandleread_207449;
	nimln(302, "asyncio.nim");
	(*result).Handlewrite = asyncsockhandlewrite_207631;
	nimln(303, "asyncio.nim");
	(*result).Task = asyncsocktask_208001;
	nimln(307, "asyncio.nim");
	(*result).Hasdatabuffered = HEX3Aanonymous_208211;
	nimln(311, "asyncio.nim");
	asgnRef((void**) (&(*sock).Deleg), result);
	nimln(312, "asyncio.nim");
	{
		nimln(312, "asyncio.nim");
		nimln(312, "asyncio.nim");
		if (!!(((17 &(1<<(((*sock).Info)&7)))!=0))) goto LA3;
		nimln(313, "asyncio.nim");
		(*(*sock).Deleg).Open = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		nimln(315, "asyncio.nim");
		(*(*sock).Deleg).Open = NIM_FALSE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, connect_208238)(asyncsocketobj207215* sock, NimStringDesc* name, NU16 port, NU8 af) {
	nimfr("connect", "asyncio.nim")
	nimln(320, "asyncio.nim");
	connectasync_199823((*sock).Socket, name, port, af);
	nimln(321, "asyncio.nim");
	(*sock).Info = ((NU8) 1);
	nimln(322, "asyncio.nim");
	{
		nimln(322, "asyncio.nim");
		nimln(322, "asyncio.nim");
		if (!!(((*sock).Deleg == NIM_NIL))) goto LA3;
		nimln(323, "asyncio.nim");
		(*(*sock).Deleg).Open = NIM_TRUE;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_207625)(asyncsocketobj207215* sock) {
	nimfr("close", "asyncio.nim")
	nimln(327, "asyncio.nim");
	close_197678((*sock).Socket);
	nimln(328, "asyncio.nim");
	(*sock).Info = ((NU8) 4);
	nimln(329, "asyncio.nim");
	{
		nimln(329, "asyncio.nim");
		nimln(329, "asyncio.nim");
		if (!!(((*sock).Deleg == NIM_NIL))) goto LA3;
		nimln(330, "asyncio.nim");
		(*(*sock).Deleg).Open = NIM_FALSE;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, bindaddr_208293)(asyncsocketobj207215* sock, NU16 port, NimStringDesc* address) {
	nimfr("bindAddr", "asyncio.nim")
	nimln(334, "asyncio.nim");
	bindaddr_195974((*sock).Socket, port, address);
	nimln(335, "asyncio.nim");
	{
		nimln(335, "asyncio.nim");
		if (!((*sock).Proto == ((NU8) 17))) goto LA3;
		nimln(336, "asyncio.nim");
		(*sock).Info = ((NU8) 5);
		nimln(337, "asyncio.nim");
		{
			nimln(337, "asyncio.nim");
			nimln(337, "asyncio.nim");
			if (!!(((*sock).Deleg == NIM_NIL))) goto LA7;
			nimln(338, "asyncio.nim");
			(*(*sock).Deleg).Open = NIM_TRUE;
		}
		LA7: ;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, listen_208330)(asyncsocketobj207215* sock) {
	nimfr("listen", "asyncio.nim")
	nimln(342, "asyncio.nim");
	listen_195809((*sock).Socket, SOMAXCONN);
	nimln(343, "asyncio.nim");
	(*sock).Info = ((NU8) 3);
	nimln(344, "asyncio.nim");
	{
		nimln(344, "asyncio.nim");
		nimln(344, "asyncio.nim");
		if (!!(((*sock).Deleg == NIM_NIL))) goto LA3;
		nimln(345, "asyncio.nim");
		(*(*sock).Deleg).Open = NIM_TRUE;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, acceptaddr_208356)(asyncsocketobj207215* server, asyncsocketobj207215** client, NimStringDesc** address) {
	tsocketimpl193807* c;
	NimStringDesc* LOC9;
	NimStringDesc* LOC10;
	nimfr("acceptAddr", "asyncio.nim")
	nimln(353, "asyncio.nim");
	{
		nimln(353, "asyncio.nim");
		nimln(353, "asyncio.nim");
		nimln(353, "asyncio.nim");
		if (!!(!(((*client) == NIM_NIL)))) goto LA3;
		nimln(353, "asyncio.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP824));
	}
	LA3: ;
	nimln(354, "asyncio.nim");
	unsureAsgnRef((void**) (&(*client)), newasyncsocket_207346());
	c = 0;
	nimln(356, "asyncio.nim");
	c = (tsocketimpl193807*) newObj((&NTI193809), sizeof(tsocketimpl193807));
	nimln(374, "asyncio.nim");
	acceptaddr_196448((*server).Socket, &c, address);
	nimln(375, "asyncio.nim");
	(*(*client)).Sslneedaccept = NIM_FALSE;
	nimln(376, "asyncio.nim");
	(*(*client)).Info = ((NU8) 2);
	nimln(378, "asyncio.nim");
	{
		nimln(378, "asyncio.nim");
		if (!(c == NIM_NIL)) goto LA7;
		nimln(378, "asyncio.nim");
		raisesocketerror_195201((*server).Socket, -1, NIM_FALSE);
	}
	LA7: ;
	nimln(379, "asyncio.nim");
	setblocking_197411(c, NIM_FALSE);
	nimln(383, "asyncio.nim");
	asgnRefNoCycle((void**) (&(*(*client)).Socket), c);
	nimln(384, "asyncio.nim");
	LOC9 = 0;
	LOC9 = (*(*client)).Linebuffer; (*(*client)).Linebuffer = copyStringRC1(((NimStringDesc*) &TMP812));
	if (LOC9) nimGCunrefNoCycle(LOC9);
	nimln(385, "asyncio.nim");
	LOC10 = 0;
	LOC10 = (*(*client)).Sendbuffer; (*(*client)).Sendbuffer = copyStringRC1(((NimStringDesc*) &TMP812));
	if (LOC10) nimGCunrefNoCycle(LOC10);
	nimln(386, "asyncio.nim");
	(*(*client)).Info = ((NU8) 2);
	popFrame();
}

N_NIMCALL(void, accept_208626)(asyncsocketobj207215* server, asyncsocketobj207215** client) {
	NimStringDesc* dummyaddr;
	nimfr("accept", "asyncio.nim")
	nimln(390, "asyncio.nim");
	dummyaddr = copyString(((NimStringDesc*) &TMP812));
	nimln(391, "asyncio.nim");
	acceptaddr_208356(server, client, (&dummyaddr));
	popFrame();
}

N_NIMCALL(void, acceptaddr_208639)(asyncsocketobj207215* server, TY208642* Result) {
	asyncsocketobj207215* client;
	NimStringDesc* address;
	nimfr("acceptAddr", "asyncio.nim")
	nimln(398, "asyncio.nim");
	client = newasyncsocket_207346();
	nimln(399, "asyncio.nim");
	address = copyString(((NimStringDesc*) &TMP812));
	nimln(400, "asyncio.nim");
	acceptaddr_208356(server, &client, (&address));
	nimln(401, "asyncio.nim");
	nimln(401, "asyncio.nim");
	unsureAsgnRef((void**) (&(*Result).Field0), client);
	unsureAsgnRef((void**) (&(*Result).Field1), copyString(address));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(asyncsocketobj207215*, accept_208658)(asyncsocketobj207215* server) {
	asyncsocketobj207215* result;
	NimStringDesc* address;
	nimfr("accept", "asyncio.nim")
	result = 0;
	nimln(407, "asyncio.nim");
	result = (asyncsocketobj207215*) newObj((&NTI207213), sizeof(asyncsocketobj207215));
	(*result).Sup.m_type = (&NTI207215);
	nimln(408, "asyncio.nim");
	address = copyString(((NimStringDesc*) &TMP812));
	nimln(409, "asyncio.nim");
	acceptaddr_208356(server, &result, (&address));
	popFrame();
	return result;
}
N_NIMCALL(void, TMP827)(void* p, NI op) {
	TY207242* a;
	NI LOC1;
	a = (TY207242*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP828)(void* p, NI op) {
	dispatcherobj207211* a;
	a = (dispatcherobj207211*)p;
	nimGCvisit((void*)(*a).Delegates, op);
}

static N_INLINE(void, nimGCunref)(void* p) {
	tcell45335* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(223, "gc.nim");
	nimln(223, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_49046(p);
	decref_51004(LOC1);
	popFrame();
}

N_NIMCALL(dispatcherobj207211*, newdispatcher_208687)(void) {
	dispatcherobj207211* result;
	nimfr("newDispatcher", "asyncio.nim")
	result = 0;
	nimln(412, "asyncio.nim");
	result = (dispatcherobj207211*) newObj((&NTI207209), sizeof(dispatcherobj207211));
	nimln(413, "asyncio.nim");
	if ((*result).Delegates) nimGCunref((*result).Delegates);
	(*result).Delegates = (TY207242*) newSeqRC1((&NTI207242), 0);
	popFrame();
	return result;
}

N_NIMCALL(void, register_208732)(dispatcherobj207211* d, delegateobj207205* deleg) {
	nimfr("register", "asyncio.nim")
	nimln(417, "asyncio.nim");
	(*d).Delegates = (TY207242*) incrSeq(&((*d).Delegates)->Sup, sizeof(delegateobj207205*));
	asgnRef((void**) (&(*d).Delegates->data[(*d).Delegates->Sup.len-1]), deleg);
	popFrame();
}

N_NIMCALL(delegateobj207205*, register_208760)(dispatcherobj207211* d, asyncsocketobj207215* sock) {
	delegateobj207205* result;
	nimfr("register", "asyncio.nim")
	result = 0;
	nimln(421, "asyncio.nim");
	result = todelegate_208207(sock);
	nimln(422, "asyncio.nim");
	register_208732(d, result);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, unregister_208771)(dispatcherobj207211* d, delegateobj207205* deleg) {
	indexerror3255* e_208863;
	NimStringDesc* LOC8;
	nimfr("unregister", "asyncio.nim")
	{
		NI i_208796;
		NI HEX3Atmp_208882;
		NI TMP831;
		NI res_208885;
		i_208796 = 0;
		HEX3Atmp_208882 = 0;
		nimln(426, "asyncio.nim");
		nimln(426, "asyncio.nim");
		nimln(426, "asyncio.nim");
		TMP831 = subInt((*d).Delegates->Sup.len, 1);
		HEX3Atmp_208882 = (NI64)(TMP831);
		nimln(1576, "system.nim");
		res_208885 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_208885 <= HEX3Atmp_208882)) goto LA3;
				nimln(1576, "system.nim");
				i_208796 = res_208885;
				nimln(427, "asyncio.nim");
				{
					nimln(427, "asyncio.nim");
					if ((NU)(i_208796) >= (NU)((*d).Delegates->Sup.len)) raiseIndexError();
					if (!((*d).Delegates->data[i_208796] == deleg)) goto LA6;
					nimln(428, "asyncio.nim");
					del_208816((&(*d).Delegates), i_208796);
					nimln(429, "asyncio.nim");
					goto BeforeRet;
				}
				LA6: ;
				nimln(1579, "system.nim");
				res_208885 = addInt(res_208885, 1);
			} LA3: ;
		}
	}
	e_208863 = 0;
	nimln(2149, "system.nim");
	e_208863 = (indexerror3255*) newObj((&NTI21001), sizeof(indexerror3255));
	(*e_208863).Sup.Sup.m_type = (&NTI3255);
	nimln(2150, "system.nim");
	LOC8 = 0;
	LOC8 = (*e_208863).Sup.message; (*e_208863).Sup.message = copyStringRC1(((NimStringDesc*) &TMP832));
	if (LOC8) nimGCunrefNoCycle(LOC8);
	nimln(430, "asyncio.nim");
	raiseException((Exception*)e_208863, "IndexError");
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NI, find_208941)(tsocketimpl193807** a_208946, NI a_208946Len0, tsocketimpl193807* item_208948) {
	NI result;
	nimfr("find", "system.nim")
	result = 0;
	{
		tsocketimpl193807* i_208992;
		NI i_209024;
		i_208992 = 0;
		nimln(1649, "system.nim");
		i_209024 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_209024 < a_208946Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_209024) >= (NU)(a_208946Len0)) raiseIndexError();
				i_208992 = a_208946[i_209024];
				nimln(1798, "system.nim");
				{
					nimln(1798, "system.nim");
					if (!(i_208992 == item_208948)) goto LA6;
					nimln(1798, "system.nim");
					goto BeforeRet;
				}
				LA6: ;
				nimln(1799, "system.nim");
				result = addInt(result, 1);
				nimln(1652, "system.nim");
				i_209024 = addInt(i_209024, 1);
			} LA3: ;
		}
	}
	nimln(1800, "system.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_208929)(tsocketimpl193807** a_208935, NI a_208935Len0, tsocketimpl193807* item_208938) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "system.nim")
	result = 0;
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	LOC1 = 0;
	LOC1 = find_208941(a_208935, a_208935Len0, item_208938);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, iswriteable_208903)(asyncsocketobj207215* s) {
	NIM_BOOL result;
	TY202215* writesock;
	TY208923 LOC1;
	NIM_BOOL LOC2;
	NI LOC3;
	NIM_BOOL LOC5;
	nimfr("isWriteable", "asyncio.nim")
	result = 0;
	nimln(434, "asyncio.nim");
	nimln(434, "asyncio.nim");
	writesock = (TY202215*) newSeq((&NTI202215), 1);
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = (*s).Socket;
	asgnRefNoCycle((void**) (&writesock->data[0]), LOC1[0]);
	nimln(435, "asyncio.nim");
	nimln(435, "asyncio.nim");
	nimln(435, "asyncio.nim");
	LOC2 = 0;
	nimln(435, "asyncio.nim");
	nimln(435, "asyncio.nim");
	nimln(435, "asyncio.nim");
	LOC3 = 0;
	LOC3 = selectwrite_201244((&writesock), 1);
	LOC2 = !((LOC3 == 0));
	if (!(LOC2)) goto LA4;
	nimln(435, "asyncio.nim");
	nimln(435, "asyncio.nim");
	LOC5 = 0;
	LOC5 = contains_208929(writesock->data, writesock->Sup.len, (*s).Socket);
	LOC2 = !(LOC5);
	LA4: ;
	result = LOC2;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(tsocketimpl193807*, getsocket_209046)(asyncsocketobj207215* s) {
	tsocketimpl193807* result;
	nimfr("getSocket", "asyncio.nim")
	result = 0;
	nimln(438, "asyncio.nim");
	nimln(438, "asyncio.nim");
	result = (*s).Socket;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isconnected_209056)(asyncsocketobj207215* s) {
	NIM_BOOL result;
	nimfr("isConnected", "asyncio.nim")
	result = 0;
	nimln(442, "asyncio.nim");
	nimln(442, "asyncio.nim");
	nimln(442, "asyncio.nim");
	result = ((*s).Info == ((NU8) 2));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, islistening_209075)(asyncsocketobj207215* s) {
	NIM_BOOL result;
	nimfr("isListening", "asyncio.nim")
	result = 0;
	nimln(445, "asyncio.nim");
	nimln(445, "asyncio.nim");
	nimln(445, "asyncio.nim");
	result = ((*s).Info == ((NU8) 3));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isconnecting_209094)(asyncsocketobj207215* s) {
	NIM_BOOL result;
	nimfr("isConnecting", "asyncio.nim")
	result = 0;
	nimln(448, "asyncio.nim");
	nimln(448, "asyncio.nim");
	nimln(448, "asyncio.nim");
	result = ((*s).Info == ((NU8) 1));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isclosed_209113)(asyncsocketobj207215* s) {
	NIM_BOOL result;
	nimfr("isClosed", "asyncio.nim")
	result = 0;
	nimln(451, "asyncio.nim");
	nimln(451, "asyncio.nim");
	nimln(451, "asyncio.nim");
	result = ((*s).Info == ((NU8) 4));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, issenddatabuffered_209132)(asyncsocketobj207215* s) {
	NIM_BOOL result;
	nimfr("isSendDataBuffered", "asyncio.nim")
	result = 0;
	nimln(455, "asyncio.nim");
	nimln(455, "asyncio.nim");
	nimln(455, "asyncio.nim");
	nimln(455, "asyncio.nim");
	nimln(455, "asyncio.nim");
	result = !(((*s).Sendbuffer->Sup.len == 0));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sethandlewrite_209142)(asyncsocketobj207215* s, TY207246 handlewrite) {
	nimfr("setHandleWrite", "asyncio.nim")
	nimln(465, "asyncio.nim");
	(*(*s).Deleg).Mode = ((NU8) 2);
	nimln(466, "asyncio.nim");
	asgnRef((void**) (&(*s).Handlewrite.ClEnv), handlewrite.ClEnv);
	(*s).Handlewrite.ClPrc = handlewrite.ClPrc;
	popFrame();
}

N_NIMCALL(void, delhandlewrite_209155)(asyncsocketobj207215* s) {
	nimfr("delHandleWrite", "asyncio.nim")
	nimln(470, "asyncio.nim");
	asgnRef((void**) (&(*s).Handlewrite.ClEnv), TMP808.ClEnv);
	(*s).Handlewrite.ClPrc = TMP808.ClPrc;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NIM_BOOL, recvline_209167)(asyncsocketobj207215* s, NimStringDesc** line) {
	NIM_BOOL result;
	NimStringDesc* datareceived;
	NU8 ret;
	nimfr("recvLine", "asyncio.nim")
	result = 0;
	nimln(484, "asyncio.nim");
	(*line) = setLengthStr((*line), 0);
	nimln(485, "asyncio.nim");
	datareceived = copyString(((NimStringDesc*) &TMP812));
	nimln(486, "asyncio.nim");
	ret = recvlineasync_202685((*s).Socket, (&datareceived));
	nimln(487, "asyncio.nim");
	switch (ret) {
	case ((NU8) 0):
	{
		nimln(489, "asyncio.nim");
		{
			nimln(489, "asyncio.nim");
			nimln(489, "asyncio.nim");
			if (!(0 < (*s).Linebuffer->Sup.len)) goto LA4;
			nimln(490, "asyncio.nim");
			(*line) = resizeString((*line), (*s).Linebuffer->Sup.len + 0);
appendString((*line), (*s).Linebuffer);
			nimln(491, "asyncio.nim");
			(*s).Linebuffer = setLengthStr((*s).Linebuffer, 0);
		}
		LA4: ;
		nimln(492, "asyncio.nim");
		(*line) = resizeString((*line), datareceived->Sup.len + 0);
appendString((*line), datareceived);
		nimln(493, "asyncio.nim");
		{
			nimln(493, "asyncio.nim");
			if (!(((*line)) && ((*line))->Sup.len == 0)) goto LA8;
			nimln(494, "asyncio.nim");
			unsureAsgnRef((void**) (&(*line)), copyString(((NimStringDesc*) &TMP846)));
		}
		LA8: ;
		nimln(495, "asyncio.nim");
		result = NIM_TRUE;
	}
	break;
	case ((NU8) 1):
	{
		nimln(497, "asyncio.nim");
		(*s).Linebuffer = resizeString((*s).Linebuffer, datareceived->Sup.len + 0);
appendString((*s).Linebuffer, datareceived);
		nimln(498, "asyncio.nim");
		result = NIM_FALSE;
	}
	break;
	case ((NU8) 2):
	{
		nimln(500, "asyncio.nim");
		result = NIM_TRUE;
	}
	break;
	case ((NU8) 3):
	{
		tsocketimpl193807* LOC13;
		nimln(502, "asyncio.nim");
		nimln(502, "asyncio.nim");
		LOC13 = 0;
		LOC13 = getsocket_209046(s);
		raisesocketerror_195201(LOC13, -1, NIM_TRUE);
		nimln(503, "asyncio.nim");
		result = NIM_FALSE;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_209197)(asyncsocketobj207215* s, NimStringDesc** line) {
	NIM_BOOL result;
	NimStringDesc* datareceived;
	NU8 ret;
	nimfr("readLine", "asyncio.nim")
	result = 0;
	nimln(516, "asyncio.nim");
	(*line) = setLengthStr((*line), 0);
	nimln(517, "asyncio.nim");
	datareceived = copyString(((NimStringDesc*) &TMP812));
	nimln(518, "asyncio.nim");
	ret = readlineasync_202714((*s).Socket, (&datareceived));
	nimln(519, "asyncio.nim");
	switch (ret) {
	case ((NU8) 0):
	{
		nimln(521, "asyncio.nim");
		{
			nimln(521, "asyncio.nim");
			nimln(521, "asyncio.nim");
			if (!(0 < (*s).Linebuffer->Sup.len)) goto LA4;
			nimln(522, "asyncio.nim");
			(*line) = resizeString((*line), (*s).Linebuffer->Sup.len + 0);
appendString((*line), (*s).Linebuffer);
			nimln(523, "asyncio.nim");
			(*s).Linebuffer = setLengthStr((*s).Linebuffer, 0);
		}
		LA4: ;
		nimln(524, "asyncio.nim");
		(*line) = resizeString((*line), datareceived->Sup.len + 0);
appendString((*line), datareceived);
		nimln(525, "asyncio.nim");
		{
			nimln(525, "asyncio.nim");
			if (!(((*line)) && ((*line))->Sup.len == 0)) goto LA8;
			nimln(526, "asyncio.nim");
			unsureAsgnRef((void**) (&(*line)), copyString(((NimStringDesc*) &TMP846)));
		}
		LA8: ;
		nimln(527, "asyncio.nim");
		result = NIM_TRUE;
	}
	break;
	case ((NU8) 1):
	{
		nimln(529, "asyncio.nim");
		(*s).Linebuffer = resizeString((*s).Linebuffer, datareceived->Sup.len + 0);
appendString((*s).Linebuffer, datareceived);
		nimln(530, "asyncio.nim");
		result = NIM_FALSE;
	}
	break;
	case ((NU8) 3):
	{
		nimln(532, "asyncio.nim");
		result = NIM_FALSE;
	}
	break;
	case ((NU8) 2):
	{
		nimln(534, "asyncio.nim");
		result = NIM_TRUE;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, send_209224)(asyncsocketobj207215* sock, NimStringDesc* data) {
	NI bytessent;
	nimfr("send", "asyncio.nim")
	nimln(544, "asyncio.nim");
	{
		nimln(544, "asyncio.nim");
		nimln(544, "asyncio.nim");
		nimln(544, "asyncio.nim");
		if (!!(((*sock).Sendbuffer->Sup.len == 0))) goto LA3;
		nimln(545, "asyncio.nim");
		(*sock).Sendbuffer = resizeString((*sock).Sendbuffer, data->Sup.len + 0);
appendString((*sock).Sendbuffer, data);
		nimln(546, "asyncio.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(547, "asyncio.nim");
	bytessent = sendasync_204229((*sock).Socket, data);
	nimln(548, "asyncio.nim");
	{
		nimln(548, "asyncio.nim");
		nimln(548, "asyncio.nim");
		if (!!((0 <= bytessent))) goto LA7;
		nimln(548, "asyncio.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP847));
	}
	LA7: ;
	nimln(549, "asyncio.nim");
	{
		nimln(549, "asyncio.nim");
		if (!(bytessent == 0)) goto LA11;
		nimln(550, "asyncio.nim");
		(*sock).Sendbuffer = resizeString((*sock).Sendbuffer, data->Sup.len + 0);
appendString((*sock).Sendbuffer, data);
		nimln(551, "asyncio.nim");
		(*(*sock).Deleg).Mode = ((NU8) 2);
	}
	goto LA9;
	LA11: ;
	{
		slice84662 LOC16;
		NimStringDesc* LOC17;
		nimln(552, "asyncio.nim");
		nimln(552, "asyncio.nim");
		nimln(552, "asyncio.nim");
		if (!!((bytessent == data->Sup.len))) goto LA14;
		nimln(553, "asyncio.nim");
		nimln(553, "asyncio.nim");
		nimln(553, "asyncio.nim");
		LOC16 = HEX2EHEX2E_93499(bytessent, -1);
		LOC17 = 0;
		LOC17 = HEX5BHEX5D_84655(data, LOC16);
		(*sock).Sendbuffer = resizeString((*sock).Sendbuffer, LOC17->Sup.len + 0);
appendString((*sock).Sendbuffer, LOC17);
		nimln(554, "asyncio.nim");
		(*(*sock).Deleg).Mode = ((NU8) 2);
	}
	goto LA9;
	LA14: ;
	LA9: ;
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(struct timeval, timevalfrommilliseconds_209418)(NI timeout) {
	struct timeval result;
	nimfr("timeValFromMilliseconds", "asyncio.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(557, "asyncio.nim");
	{
		NI seconds;
		NI TMP848;
		NI TMP849;
		NI TMP850;
		NI TMP851;
		nimln(557, "asyncio.nim");
		nimln(557, "asyncio.nim");
		if (!!((timeout == -1))) goto LA3;
		nimln(558, "asyncio.nim");
		nimln(558, "asyncio.nim");
		TMP848 = divInt(timeout, 1000);
		seconds = (NI64)(TMP848);
		nimln(559, "asyncio.nim");
		result.tv_sec = ((NI) (((NI32)chckRange(seconds, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
		nimln(560, "asyncio.nim");
		nimln(560, "asyncio.nim");
		nimln(560, "asyncio.nim");
		nimln(560, "asyncio.nim");
		TMP849 = mulInt(seconds, 1000);
		TMP850 = subInt(timeout, (NI64)(TMP849));
		TMP851 = mulInt((NI64)(TMP850), 1000);
		result.tv_usec = ((NI) (((NI32)chckRange((NI64)(TMP851), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, createfdset_209433)(fd_set* fd, TY207242* s, NI* m) {
	nimfr("createFdSet", "asyncio.nim")
	nimln(563, "asyncio.nim");
	FD_ZERO(fd);
	{
		delegateobj207205* i_209622;
		NI i_209638;
		NI l_209640;
		i_209622 = 0;
		nimln(2986, "system.nim");
		i_209638 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_209640 = s->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_209638 < l_209640)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_209638) >= (NU)(s->Sup.len)) raiseIndexError();
				i_209622 = s->data[i_209638];
				nimln(565, "asyncio.nim");
				nimln(565, "asyncio.nim");
				(*m) = (((*m) >= ((NI) ((*i_209622).Fd))) ? (*m) : ((NI) ((*i_209622).Fd)));
				nimln(566, "asyncio.nim");
				FD_SET((*i_209622).Fd, fd);
				nimln(2990, "system.nim");
				i_209638 = addInt(i_209638, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((s->Sup.len == l_209640))) goto LA6;
					nimln(2991, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP852));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, prunesocketset_209656)(TY207242** s, fd_set* fd) {
	NI i;
	NI l;
	nimfr("pruneSocketSet", "asyncio.nim")
	nimln(569, "asyncio.nim");
	i = 0;
	nimln(570, "asyncio.nim");
	nimln(570, "asyncio.nim");
	l = (*s)->Sup.len;
	{
		nimln(571, "asyncio.nim");
		while (1) {
			nimln(571, "asyncio.nim");
			if (!(i < l)) goto LA2;
			nimln(572, "asyncio.nim");
			{
				int LOC5;
				NI TMP853;
				nimln(572, "asyncio.nim");
				nimln(572, "asyncio.nim");
				nimln(572, "asyncio.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				LOC5 = 0;
				LOC5 = FD_ISSET((*(*s)->data[i]).Fd, fd);
				if (!!((LOC5 == ((NI32) 0)))) goto LA6;
				nimln(573, "asyncio.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				nimln(573, "asyncio.nim");
				TMP853 = subInt(l, 1);
				if ((NU)((NI64)(TMP853)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				asgnRef((void**) (&(*s)->data[i]), (*s)->data[(NI64)(TMP853)]);
				nimln(574, "asyncio.nim");
				l = subInt(l, 1);
			}
			goto LA3;
			LA6: ;
			{
				nimln(576, "asyncio.nim");
				i = addInt(i, 1);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(577, "asyncio.nim");
	(*s) = (TY207242*) setLengthSeq(&((*s))->Sup, sizeof(delegateobj207205*), l);
	popFrame();
}

N_NIMCALL(NI, select_209739)(TY207242** readfds, TY207242** writefds, TY207242** exceptfds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set rd;
	fd_set wr;
	fd_set ex;
	NI m;
	nimfr("select", "asyncio.nim")
	result = 0;
	nimln(581, "asyncio.nim");
	tv = timevalfrommilliseconds_209418(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	memset((void*)(&wr), 0, sizeof(wr));
	memset((void*)(&ex), 0, sizeof(ex));
	nimln(584, "asyncio.nim");
	m = 0;
	nimln(585, "asyncio.nim");
	createfdset_209433((&rd), (*readfds), (&m));
	nimln(586, "asyncio.nim");
	createfdset_209433((&wr), (*writefds), (&m));
	nimln(587, "asyncio.nim");
	createfdset_209433((&ex), (*exceptfds), (&m));
	nimln(589, "asyncio.nim");
	{
		NI TMP854;
		int LOC5;
		nimln(589, "asyncio.nim");
		nimln(589, "asyncio.nim");
		if (!!((timeout == -1))) goto LA3;
		nimln(590, "asyncio.nim");
		nimln(590, "asyncio.nim");
		nimln(590, "asyncio.nim");
		TMP854 = addInt(m, 1);
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI64)(TMP854), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), (&wr), (&ex), (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP855;
		int LOC7;
		nimln(592, "asyncio.nim");
		nimln(592, "asyncio.nim");
		nimln(592, "asyncio.nim");
		TMP855 = addInt(m, 1);
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI64)(TMP855), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), (&wr), (&ex), NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(594, "asyncio.nim");
	prunesocketset_209656(readfds, (&rd));
	nimln(595, "asyncio.nim");
	prunesocketset_209656(writefds, (&wr));
	nimln(596, "asyncio.nim");
	prunesocketset_209656(exceptfds, (&ex));
	popFrame();
	return result;
}

static N_INLINE(NI, find_210097)(delegateobj207205** a_210102, NI a_210102Len0, delegateobj207205* item_210104) {
	NI result;
	nimfr("find", "system.nim")
	result = 0;
	{
		delegateobj207205* i_210148;
		NI i_210180;
		i_210148 = 0;
		nimln(1649, "system.nim");
		i_210180 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_210180 < a_210102Len0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_210180) >= (NU)(a_210102Len0)) raiseIndexError();
				i_210148 = a_210102[i_210180];
				nimln(1798, "system.nim");
				{
					nimln(1798, "system.nim");
					if (!(i_210148 == item_210104)) goto LA6;
					nimln(1798, "system.nim");
					goto BeforeRet;
				}
				LA6: ;
				nimln(1799, "system.nim");
				result = addInt(result, 1);
				nimln(1652, "system.nim");
				i_210180 = addInt(i_210180, 1);
			} LA3: ;
		}
	}
	nimln(1800, "system.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_210085)(delegateobj207205** a_210091, NI a_210091Len0, delegateobj207205* item_210094) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "system.nim")
	result = 0;
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	nimln(1805, "system.nim");
	LOC1 = 0;
	LOC1 = find_210097(a_210091, a_210091Len0, item_210094);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, poll_209812)(dispatcherobj207211* d, NI timeout) {
	NIM_BOOL result;
	TY207242* readdg;
	TY207242* writedg;
	TY207242* errordg;
	NI len;
	NI dc;
	NI hasdatabufferedcount;
	nimfr("poll", "asyncio.nim")
	result = 0;
	nimln(610, "asyncio.nim");
	result = NIM_TRUE;
	nimln(611, "asyncio.nim");
	readdg = (TY207242*) newSeq((&NTI207242), 0);
	nimln(611, "asyncio.nim");
	writedg = (TY207242*) newSeq((&NTI207242), 0);
	nimln(611, "asyncio.nim");
	errordg = (TY207242*) newSeq((&NTI207242), 0);
	nimln(612, "asyncio.nim");
	nimln(612, "asyncio.nim");
	len = (*d).Delegates->Sup.len;
	nimln(613, "asyncio.nim");
	dc = 0;
	{
		nimln(615, "asyncio.nim");
		while (1) {
			delegateobj207205* deleg;
			nimln(615, "asyncio.nim");
			if (!(dc < len)) goto LA2;
			nimln(616, "asyncio.nim");
			if ((NU)(dc) >= (NU)((*d).Delegates->Sup.len)) raiseIndexError();
			deleg = (*d).Delegates->data[dc];
			nimln(617, "asyncio.nim");
			{
				NIM_BOOL LOC5;
				NIM_BOOL LOC6;
				nimln(617, "asyncio.nim");
				LOC5 = 0;
				nimln(617, "asyncio.nim");
				LOC6 = 0;
				nimln(617, "asyncio.nim");
				nimln(617, "asyncio.nim");
				LOC6 = !(((*deleg).Mode == ((NU8) 1)));
				if (LOC6) goto LA7;
				nimln(617, "asyncio.nim");
				nimln(617, "asyncio.nim");
				LOC6 = !(((*deleg).Mode == ((NU8) 4)));
				LA7: ;
				LOC5 = LOC6;
				if (!(LOC5)) goto LA8;
				LOC5 = (*deleg).Open;
				LA8: ;
				if (!LOC5) goto LA9;
				nimln(618, "asyncio.nim");
				readdg = (TY207242*) incrSeq(&(readdg)->Sup, sizeof(delegateobj207205*));
				asgnRef((void**) (&readdg->data[readdg->Sup.len-1]), deleg);
			}
			LA9: ;
			nimln(619, "asyncio.nim");
			{
				NIM_BOOL LOC13;
				nimln(619, "asyncio.nim");
				LOC13 = 0;
				nimln(619, "asyncio.nim");
				nimln(619, "asyncio.nim");
				LOC13 = !(((*deleg).Mode == ((NU8) 0)));
				if (!(LOC13)) goto LA14;
				LOC13 = (*deleg).Open;
				LA14: ;
				if (!LOC13) goto LA15;
				nimln(620, "asyncio.nim");
				writedg = (TY207242*) incrSeq(&(writedg)->Sup, sizeof(delegateobj207205*));
				asgnRef((void**) (&writedg->data[writedg->Sup.len-1]), deleg);
			}
			LA15: ;
			nimln(621, "asyncio.nim");
			{
				if (!(*deleg).Open) goto LA19;
				nimln(622, "asyncio.nim");
				errordg = (TY207242*) incrSeq(&(errordg)->Sup, sizeof(delegateobj207205*));
				asgnRef((void**) (&errordg->data[errordg->Sup.len-1]), deleg);
				nimln(623, "asyncio.nim");
				dc = addInt(dc, 1);
			}
			goto LA17;
			LA19: ;
			{
				NI TMP856;
				nimln(626, "asyncio.nim");
				if ((NU)(dc) >= (NU)((*d).Delegates->Sup.len)) raiseIndexError();
				nimln(626, "asyncio.nim");
				TMP856 = subInt(len, 1);
				if ((NU)((NI64)(TMP856)) >= (NU)((*d).Delegates->Sup.len)) raiseIndexError();
				asgnRef((void**) (&(*d).Delegates->data[dc]), (*d).Delegates->data[(NI64)(TMP856)]);
				nimln(627, "asyncio.nim");
				len = subInt(len, 1);
			}
			LA17: ;
		} LA2: ;
	}
	nimln(629, "asyncio.nim");
	(*d).Delegates = (TY207242*) setLengthSeq(&((*d).Delegates)->Sup, sizeof(delegateobj207205*), len);
	nimln(631, "asyncio.nim");
	hasdatabufferedcount = 0;
	{
		delegateobj207205* d_209991;
		TY207242* HEX3Atmp_210249;
		NI i_210252;
		NI l_210254;
		d_209991 = 0;
		HEX3Atmp_210249 = 0;
		nimln(632, "asyncio.nim");
		HEX3Atmp_210249 = (*d).Delegates;
		nimln(2986, "system.nim");
		i_210252 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_210254 = HEX3Atmp_210249->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_210252 < l_210254)) goto LA24;
				nimln(2989, "system.nim");
				if ((NU)(i_210252) >= (NU)(HEX3Atmp_210249->Sup.len)) raiseIndexError();
				d_209991 = HEX3Atmp_210249->data[i_210252];
				nimln(633, "asyncio.nim");
				{
					NIM_BOOL LOC27;
					nimln(633, "asyncio.nim");
					LOC27 = 0;
					LOC27 = (*d_209991).Hasdatabuffered((*d_209991).Deleval);
					if (!LOC27) goto LA28;
					nimln(634, "asyncio.nim");
					hasdatabufferedcount = addInt(hasdatabufferedcount, 1);
					nimln(635, "asyncio.nim");
					(*d_209991).Handleread((*d_209991).Deleval);
				}
				LA28: ;
				nimln(2990, "system.nim");
				i_210252 = addInt(i_210252, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((HEX3Atmp_210249->Sup.len == l_210254))) goto LA32;
					nimln(2991, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP852));
				}
				LA32: ;
			} LA24: ;
		}
	}
	nimln(636, "asyncio.nim");
	{
		nimln(636, "asyncio.nim");
		if (!(0 < hasdatabufferedcount)) goto LA36;
		nimln(636, "asyncio.nim");
		nimln(636, "asyncio.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA36: ;
	nimln(638, "asyncio.nim");
	{
		NIM_BOOL LOC40;
		nimln(638, "asyncio.nim");
		LOC40 = 0;
		nimln(638, "asyncio.nim");
		nimln(638, "asyncio.nim");
		LOC40 = (readdg->Sup.len == 0);
		if (!(LOC40)) goto LA41;
		nimln(638, "asyncio.nim");
		nimln(638, "asyncio.nim");
		LOC40 = (writedg->Sup.len == 0);
		LA41: ;
		if (!LOC40) goto LA42;
		nimln(640, "asyncio.nim");
		nimln(640, "asyncio.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA42: ;
	nimln(642, "asyncio.nim");
	{
		NI LOC46;
		nimln(642, "asyncio.nim");
		nimln(642, "asyncio.nim");
		nimln(642, "asyncio.nim");
		LOC46 = 0;
		LOC46 = select_209739((&readdg), (&writedg), (&errordg), timeout);
		if (!!((LOC46 == 0))) goto LA47;
		{
			NI i_210051;
			NI HEX3Atmp_210257;
			NI TMP857;
			NI res_210260;
			i_210051 = 0;
			HEX3Atmp_210257 = 0;
			nimln(643, "asyncio.nim");
			nimln(643, "asyncio.nim");
			nimln(643, "asyncio.nim");
			TMP857 = subInt((*d).Delegates->Sup.len, 1);
			HEX3Atmp_210257 = (NI64)(TMP857);
			nimln(1576, "system.nim");
			res_210260 = 0;
			{
				nimln(1577, "system.nim");
				while (1) {
					nimln(1577, "system.nim");
					if (!(res_210260 <= HEX3Atmp_210257)) goto LA51;
					nimln(1576, "system.nim");
					i_210051 = res_210260;
					{
						delegateobj207205* deleg;
						nimln(644, "asyncio.nim");
						{
							NI TMP858;
							nimln(644, "asyncio.nim");
							nimln(644, "asyncio.nim");
							nimln(644, "asyncio.nim");
							TMP858 = subInt((*d).Delegates->Sup.len, 1);
							if (!((NI64)(TMP858) < i_210051)) goto LA55;
							nimln(644, "asyncio.nim");
							goto LA49;
						}
						LA55: ;
						nimln(645, "asyncio.nim");
						if ((NU)(i_210051) >= (NU)((*d).Delegates->Sup.len)) raiseIndexError();
						deleg = (*d).Delegates->data[i_210051];
						nimln(646, "asyncio.nim");
						{
							nimln(646, "asyncio.nim");
							if (!!((*deleg).Open)) goto LA59;
							nimln(646, "asyncio.nim");
							goto LA52;
						}
						LA59: ;
						nimln(647, "asyncio.nim");
						{
							NIM_BOOL LOC63;
							NIM_BOOL LOC64;
							NIM_BOOL LOC67;
							nimln(647, "asyncio.nim");
							LOC63 = 0;
							nimln(647, "asyncio.nim");
							LOC64 = 0;
							nimln(647, "asyncio.nim");
							nimln(647, "asyncio.nim");
							LOC64 = !(((*deleg).Mode == ((NU8) 1)));
							if (LOC64) goto LA65;
							nimln(647, "asyncio.nim");
							nimln(647, "asyncio.nim");
							LOC64 = !(((*deleg).Mode == ((NU8) 4)));
							LA65: ;
							LOC63 = LOC64;
							if (!(LOC63)) goto LA66;
							nimln(648, "asyncio.nim");
							nimln(648, "asyncio.nim");
							LOC67 = 0;
							LOC67 = contains_210085(readdg->data, readdg->Sup.len, deleg);
							LOC63 = !(LOC67);
							LA66: ;
							if (!LOC63) goto LA68;
							nimln(649, "asyncio.nim");
							(*deleg).Handleread((*deleg).Deleval);
						}
						LA68: ;
						nimln(650, "asyncio.nim");
						{
							NIM_BOOL LOC72;
							NIM_BOOL LOC74;
							nimln(650, "asyncio.nim");
							LOC72 = 0;
							nimln(650, "asyncio.nim");
							nimln(650, "asyncio.nim");
							LOC72 = !(((*deleg).Mode == ((NU8) 0)));
							if (!(LOC72)) goto LA73;
							nimln(650, "asyncio.nim");
							nimln(650, "asyncio.nim");
							LOC74 = 0;
							LOC74 = contains_210085(writedg->data, writedg->Sup.len, deleg);
							LOC72 = !(LOC74);
							LA73: ;
							if (!LOC72) goto LA75;
							nimln(651, "asyncio.nim");
							(*deleg).Handlewrite((*deleg).Deleval);
						}
						LA75: ;
						nimln(652, "asyncio.nim");
						{
							NIM_BOOL LOC79;
							nimln(652, "asyncio.nim");
							nimln(652, "asyncio.nim");
							LOC79 = 0;
							LOC79 = contains_210085(errordg->data, errordg->Sup.len, deleg);
							if (!!(LOC79)) goto LA80;
							nimln(653, "asyncio.nim");
							(*deleg).Handleerror((*deleg).Deleval);
						}
						LA80: ;
					} LA52: ;
					nimln(1579, "system.nim");
					res_210260 = addInt(res_210260, 1);
				} LA51: ;
			}
		} LA49: ;
	}
	LA47: ;
	{
		delegateobj207205* i_210243;
		TY207242* HEX3Atmp_210263;
		NI i_210266;
		NI l_210268;
		i_210243 = 0;
		HEX3Atmp_210263 = 0;
		nimln(656, "asyncio.nim");
		HEX3Atmp_210263 = (*d).Delegates;
		nimln(2986, "system.nim");
		i_210266 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_210268 = HEX3Atmp_210263->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_210266 < l_210268)) goto LA84;
				nimln(2989, "system.nim");
				if ((NU)(i_210266) >= (NU)(HEX3Atmp_210263->Sup.len)) raiseIndexError();
				i_210243 = HEX3Atmp_210263->data[i_210266];
				nimln(657, "asyncio.nim");
				(*i_210243).Task((*i_210243).Deleval);
				nimln(2990, "system.nim");
				i_210266 = addInt(i_210266, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((HEX3Atmp_210263->Sup.len == l_210268))) goto LA87;
					nimln(2991, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP852));
				}
				LA87: ;
			} LA84: ;
		}
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, len_210311)(dispatcherobj207211* disp) {
	NI result;
	nimfr("len", "asyncio.nim")
	result = 0;
	nimln(661, "asyncio.nim");
	nimln(661, "asyncio.nim");
	nimln(661, "asyncio.nim");
	result = (*disp).Delegates->Sup.len;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncioInit)(void) {
	nimfr("asyncio", "asyncio.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_asyncioDatInit)(void) {
static TNimNode* TMP790[9];
static TNimNode* TMP795[12];
static TNimNode* TMP799[6];
NI TMP801;
static char* NIM_CONST TMP800[6] = {
"SockIdle", 
"SockConnecting", 
"SockConnected", 
"SockListening", 
"SockClosed", 
"SockUDPBound"};
static TNimNode* TMP802[2];
static TNimNode TMP788[34];
NTI207205.size = sizeof(delegateobj207205);
NTI207205.kind = 18;
NTI207205.base = 0;
TMP790[0] = &TMP788[1];
TMP788[1].kind = 1;
TMP788[1].offset = offsetof(delegateobj207205, Fd);
TMP788[1].typ = (&NTI5611);
TMP788[1].name = "fd";
TMP790[1] = &TMP788[2];
TMP788[2].kind = 1;
TMP788[2].offset = offsetof(delegateobj207205, Deleval);
TMP788[2].typ = (&NTI3213);
TMP788[2].name = "deleVal";
TMP790[2] = &TMP788[3];
NTI207220.size = sizeof(TY207220);
NTI207220.kind = 25;
NTI207220.base = 0;
NTI207220.flags = 3;
TMP788[3].kind = 1;
TMP788[3].offset = offsetof(delegateobj207205, Handleread);
TMP788[3].typ = (&NTI207220);
TMP788[3].name = "handleRead";
TMP790[3] = &TMP788[4];
NTI207224.size = sizeof(TY207224);
NTI207224.kind = 25;
NTI207224.base = 0;
NTI207224.flags = 3;
TMP788[4].kind = 1;
TMP788[4].offset = offsetof(delegateobj207205, Handlewrite);
TMP788[4].typ = (&NTI207224);
TMP788[4].name = "handleWrite";
TMP790[4] = &TMP788[5];
NTI207228.size = sizeof(TY207228);
NTI207228.kind = 25;
NTI207228.base = 0;
NTI207228.flags = 3;
TMP788[5].kind = 1;
TMP788[5].offset = offsetof(delegateobj207205, Handleerror);
TMP788[5].typ = (&NTI207228);
TMP788[5].name = "handleError";
TMP790[5] = &TMP788[6];
NTI207232.size = sizeof(TY207232);
NTI207232.kind = 25;
NTI207232.base = 0;
NTI207232.flags = 3;
TMP788[6].kind = 1;
TMP788[6].offset = offsetof(delegateobj207205, Hasdatabuffered);
TMP788[6].typ = (&NTI207232);
TMP788[6].name = "hasDataBuffered";
TMP790[6] = &TMP788[7];
TMP788[7].kind = 1;
TMP788[7].offset = offsetof(delegateobj207205, Open);
TMP788[7].typ = (&NTI138);
TMP788[7].name = "open";
TMP790[7] = &TMP788[8];
NTI207237.size = sizeof(TY207237);
NTI207237.kind = 25;
NTI207237.base = 0;
NTI207237.flags = 3;
TMP788[8].kind = 1;
TMP788[8].offset = offsetof(delegateobj207205, Task);
TMP788[8].typ = (&NTI207237);
TMP788[8].name = "task";
TMP790[8] = &TMP788[9];
TMP788[9].kind = 1;
TMP788[9].offset = offsetof(delegateobj207205, Mode);
TMP788[9].typ = (&NTI12606);
TMP788[9].name = "mode";
TMP788[0].len = 9; TMP788[0].kind = 2; TMP788[0].sons = &TMP790[0];
NTI207205.node = &TMP788[0];
NTI207207.size = sizeof(delegateobj207205*);
NTI207207.kind = 22;
NTI207207.base = (&NTI207205);
NTI207207.marker = TMP794;
NTI207215.size = sizeof(asyncsocketobj207215);
NTI207215.kind = 17;
NTI207215.base = (&NTI3211);
TMP795[0] = &TMP788[11];
TMP788[11].kind = 1;
TMP788[11].offset = offsetof(asyncsocketobj207215, Socket);
TMP788[11].typ = (&NTI193809);
TMP788[11].name = "socket";
TMP795[1] = &TMP788[12];
NTI207217.size = sizeof(NU8);
NTI207217.kind = 14;
NTI207217.base = 0;
NTI207217.flags = 3;
for (TMP801 = 0; TMP801 < 6; TMP801++) {
TMP788[TMP801+13].kind = 1;
TMP788[TMP801+13].offset = TMP801;
TMP788[TMP801+13].name = TMP800[TMP801];
TMP799[TMP801] = &TMP788[TMP801+13];
}
TMP788[19].len = 6; TMP788[19].kind = 2; TMP788[19].sons = &TMP799[0];
NTI207217.node = &TMP788[19];
TMP788[12].kind = 1;
TMP788[12].offset = offsetof(asyncsocketobj207215, Info);
TMP788[12].typ = (&NTI207217);
TMP788[12].name = "info";
TMP795[2] = &TMP788[20];
NTI207246.size = sizeof(TY161264);
NTI207246.kind = 18;
NTI207246.base = 0;
NTI207246.flags = 2;
TMP802[0] = &TMP788[22];
TMP788[22].kind = 1;
TMP788[22].offset = offsetof(TY161264, Field0);
TMP788[22].typ = (&NTI153);
TMP788[22].name = "Field0";
TMP802[1] = &TMP788[23];
TMP788[23].kind = 1;
TMP788[23].offset = offsetof(TY161264, Field1);
TMP788[23].typ = (&NTI161266);
TMP788[23].name = "Field1";
TMP788[21].len = 2; TMP788[21].kind = 2; TMP788[21].sons = &TMP802[0];
NTI207246.node = &TMP788[21];
TMP788[20].kind = 1;
TMP788[20].offset = offsetof(asyncsocketobj207215, Handleread);
TMP788[20].typ = (&NTI207246);
TMP788[20].name = "handleRead";
TMP795[3] = &TMP788[24];
TMP788[24].kind = 1;
TMP788[24].offset = offsetof(asyncsocketobj207215, Handlewrite);
TMP788[24].typ = (&NTI207246);
TMP788[24].name = "handleWrite";
TMP795[4] = &TMP788[25];
TMP788[25].kind = 1;
TMP788[25].offset = offsetof(asyncsocketobj207215, Handleconnect);
TMP788[25].typ = (&NTI207246);
TMP788[25].name = "handleConnect";
TMP795[5] = &TMP788[26];
TMP788[26].kind = 1;
TMP788[26].offset = offsetof(asyncsocketobj207215, Handleaccept);
TMP788[26].typ = (&NTI207246);
TMP788[26].name = "handleAccept";
TMP795[6] = &TMP788[27];
TMP788[27].kind = 1;
TMP788[27].offset = offsetof(asyncsocketobj207215, Handletask);
TMP788[27].typ = (&NTI207246);
TMP788[27].name = "handleTask";
TMP795[7] = &TMP788[28];
TMP788[28].kind = 1;
TMP788[28].offset = offsetof(asyncsocketobj207215, Linebuffer);
TMP788[28].typ = (&NTI149);
TMP788[28].name = "lineBuffer";
TMP795[8] = &TMP788[29];
TMP788[29].kind = 1;
TMP788[29].offset = offsetof(asyncsocketobj207215, Sendbuffer);
TMP788[29].typ = (&NTI149);
TMP788[29].name = "sendBuffer";
TMP795[9] = &TMP788[30];
TMP788[30].kind = 1;
TMP788[30].offset = offsetof(asyncsocketobj207215, Sslneedaccept);
TMP788[30].typ = (&NTI138);
TMP788[30].name = "sslNeedAccept";
TMP795[10] = &TMP788[31];
TMP788[31].kind = 1;
TMP788[31].offset = offsetof(asyncsocketobj207215, Proto);
TMP788[31].typ = (&NTI193817);
TMP788[31].name = "proto";
TMP795[11] = &TMP788[32];
TMP788[32].kind = 1;
TMP788[32].offset = offsetof(asyncsocketobj207215, Deleg);
TMP788[32].typ = (&NTI207207);
TMP788[32].name = "deleg";
TMP788[10].len = 12; TMP788[10].kind = 2; TMP788[10].sons = &TMP795[0];
NTI207215.node = &TMP788[10];
NTI207213.size = sizeof(asyncsocketobj207215*);
NTI207213.kind = 22;
NTI207213.base = (&NTI207215);
NTI207213.marker = TMP806;
NTI207211.size = sizeof(dispatcherobj207211);
NTI207211.kind = 18;
NTI207211.base = 0;
NTI207242.size = sizeof(TY207242*);
NTI207242.kind = 24;
NTI207242.base = (&NTI207207);
NTI207242.marker = TMP827;
TMP788[33].kind = 1;
TMP788[33].offset = offsetof(dispatcherobj207211, Delegates);
TMP788[33].typ = (&NTI207242);
TMP788[33].name = "delegates";
NTI207211.node = &TMP788[33];
NTI207209.size = sizeof(dispatcherobj207211*);
NTI207209.kind = 22;
NTI207209.base = (&NTI207211);
NTI207209.marker = TMP828;
}

