/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_sockets.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_sockets.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <sys/socket.h>

#include <netinet/in.h>

#include <fcntl.h>

#include <errno.h>

#include <netdb.h>

#include <string.h>

#include <unistd.h>

#include <arpa/inet.h>

#include <sys/select.h>
typedef struct tsocketimpl193807 tsocketimpl193807;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct oserror3233 oserror3233;
typedef struct systemerror3229 systemerror3229;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct TY202215 TY202215;
typedef struct valueerror3249 valueerror3249;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
typedef NIM_CHAR TY175208[4001];
struct  tsocketimpl193807  {
int Fd;
NIM_BOOL Isbuffered;
union {
struct {TY175208 Buffer;
NI Currpos;
NI Buflen;
} S1;
} isbufferedU;
NIM_BOOL Nonblocking;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  systemerror3229  {
  Exception Sup;
};
struct  oserror3233  {
  systemerror3229 Sup;
NI32 Errorcode;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
struct  valueerror3249  {
  Exception Sup;
};
typedef NIM_CHAR TY113053[256];
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY202215 {
  TGenericSeq Sup;
  tsocketimpl193807* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, TMP798)(void* p, NI op);
N_NIMCALL(tsocketimpl193807*, newtsocket_194204)(int fd, NIM_BOOL isbuff);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, FieldDiscriminantCheck)(NI olddiscval, NI newdiscval, TNimNode** a, NI l);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, toint_194627)(NU8 domain);
N_NIMCALL(int, toint_194634)(NU8 typ);
N_NIMCALL(int, toint_194641)(NU8 p);
N_NIMCALL(void, raiseoserror_123009)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_123041)(void);
N_NIMCALL(NI, send_203664)(tsocketimpl193807* socket, void* data, NI size);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, HEX24_6201)(NU64 x);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI16, htons_194617)(NI16 x);
N_NIMCALL(NI16, ntohs_194407)(NI16 x);
N_NIMCALL(NI32, htonl_194607)(NI32 x);
N_NIMCALL(NI32, ntohl_194270)(NI32 x);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(struct timeval, timevalfrommilliseconds_200601)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, createfdset_200616)(fd_set* fd, TY202215* s, NI* m);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, prunesocketset_200856)(TY202215** s, fd_set* fd);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NI, recv_201502)(tsocketimpl193807* socket, void* data, NI size);
N_NIMCALL(NI, readintobuf_201360)(tsocketimpl193807* socket, NI32 flags);
N_NIMCALL(NI, peekchar_202338)(tsocketimpl193807* socket, NIM_CHAR* c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, raisesocketerror_195201)(tsocketimpl193807* socket, NI err, NIM_BOOL async);
N_NIMCALL(int, tocint_199263)(NU8 opt);
N_NIMCALL(NI, checkbuffer_201007)(TY202215** readfds);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NIM_BOOL, hasdatabuffered_200939)(tsocketimpl193807* s);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_80004, TNimType* mt);
N_NIMCALL(void, acceptaddr_196448)(tsocketimpl193807* server, tsocketimpl193807** client, NimStringDesc** address);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
TNimNode* NimDT_193807_isbuffered[3];
STRING_LITERAL(TMP813, "currPos", 7);
STRING_LITERAL(TMP823, "bufLen", 6);
STRING_LITERAL(TMP825, "client != nil ", 14);
STRING_LITERAL(TMP826, "", 0);
STRING_LITERAL(TMP838, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
STRING_LITERAL(TMP842, "buffer", 6);
STRING_LITERAL(TMP878, "This function cannot be used on non-blocking sockets.", 53);
STRING_LITERAL(TMP879, "Could not send all data.", 24);
int osinvalidsocket_194004;
TNimType NTI193807; /* TSocketImpl */
extern TNimType NTI5611; /* cint */
extern TNimType NTI138; /* bool */
extern TNimType NTI175208; /* array[0..4000, char] */
extern TNimType NTI108; /* int */
TNimType NTI193809; /* Socket */
TNimType NTI193817; /* Protocol */
extern TNimNode* NimDT_193807_isbuffered[3];
extern TFrame* frameptr_16442;
extern TNimType NTI148404; /* ref OSError */
extern TNimType NTI3233; /* OSError */
extern tgcheap47416 gch_47444;
extern TNimType NTI202215; /* seq[Socket] */
extern TNimType NTI21801; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
N_NIMCALL(void, TMP798)(void* p, NI op) {
	tsocketimpl193807* a;
	NI LOC1;
	a = (tsocketimpl193807*)p;
	switch ((*a).Isbuffered) {
	case NIM_TRUE:
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 4001; LOC1++) {
	}
	break;
	case NIM_FALSE:
	break;
	} 
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

N_NIMCALL(tsocketimpl193807*, newtsocket_194204)(int fd, NIM_BOOL isbuff) {
	tsocketimpl193807* result;
	NIM_BOOL LOC5;
	nimfr("newTSocket", "sockets.nim")
	result = 0;
	nimln(165, "sockets.nim");
	{
		nimln(165, "sockets.nim");
		if (!(fd == osinvalidsocket_194004)) goto LA3;
		nimln(166, "sockets.nim");
		nimln(166, "sockets.nim");
		result = NIM_NIL;
		goto BeforeRet;
	}
	LA3: ;
	nimln(167, "sockets.nim");
	result = (tsocketimpl193807*) newObj((&NTI193809), sizeof(tsocketimpl193807));
	nimln(168, "sockets.nim");
	(*result).Fd = fd;
	nimln(169, "sockets.nim");
	LOC5 = 0;
	LOC5 = isbuff;
	FieldDiscriminantCheck((NI)(NU)((*result).Isbuffered), (NI)(NU)(LOC5), NimDT_193807_isbuffered, 3);
	(*result).Isbuffered = LOC5;
	nimln(170, "sockets.nim");
	{
		if (!isbuff) goto LA8;
		nimln(171, "sockets.nim");
		if (!(((2 &(1<<(((*result).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
		(*result).isbufferedU.S1.Currpos = 0;
	}
	LA8: ;
	nimln(172, "sockets.nim");
	(*result).Nonblocking = NIM_FALSE;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, toint_194627)(NU8 domain) {
	int result;
	nimfr("toInt", "sockets.nim")
	result = 0;
	nimln(211, "sockets.nim");
	switch (domain) {
	case ((NU8) 0):
	{
		nimln(212, "sockets.nim");
		result = AF_UNIX;
	}
	break;
	case ((NU8) 2):
	{
		nimln(213, "sockets.nim");
		result = AF_INET;
	}
	break;
	case ((NU8) 23):
	{
		nimln(214, "sockets.nim");
		result = AF_INET6;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, toint_194634)(NU8 typ) {
	int result;
	nimfr("toInt", "sockets.nim")
	result = 0;
	nimln(218, "sockets.nim");
	switch (typ) {
	case ((NU8) 1):
	{
		nimln(219, "sockets.nim");
		result = SOCK_STREAM;
	}
	break;
	case ((NU8) 2):
	{
		nimln(220, "sockets.nim");
		result = SOCK_DGRAM;
	}
	break;
	case ((NU8) 5):
	{
		nimln(221, "sockets.nim");
		result = SOCK_SEQPACKET;
	}
	break;
	case ((NU8) 3):
	{
		nimln(222, "sockets.nim");
		result = SOCK_RAW;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, toint_194641)(NU8 p) {
	int result;
	nimfr("toInt", "sockets.nim")
	result = 0;
	nimln(226, "sockets.nim");
	switch (p) {
	case ((NU8) 6):
	{
		nimln(227, "sockets.nim");
		result = IPPROTO_TCP;
	}
	break;
	case ((NU8) 17):
	{
		nimln(228, "sockets.nim");
		result = IPPROTO_UDP;
	}
	break;
	case ((NU8) 18):
	{
		nimln(229, "sockets.nim");
		result = IPPROTO_IP;
	}
	break;
	case ((NU8) 19):
	{
		nimln(230, "sockets.nim");
		result = IPPROTO_IPV6;
	}
	break;
	case ((NU8) 20):
	{
		nimln(231, "sockets.nim");
		result = IPPROTO_RAW;
	}
	break;
	case ((NU8) 21):
	{
		nimln(232, "sockets.nim");
		result = IPPROTO_ICMP;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(tsocketimpl193807*, socket_194804)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered) {
	tsocketimpl193807* result;
	int LOC1;
	int LOC2;
	int LOC3;
	int LOC4;
	nimfr("socket", "sockets.nim")
	result = 0;
	nimln(253, "sockets.nim");
	nimln(253, "sockets.nim");
	nimln(253, "sockets.nim");
	LOC1 = 0;
	LOC1 = toint_194627(domain);
	nimln(253, "sockets.nim");
	LOC2 = 0;
	LOC2 = toint_194634(typ);
	nimln(253, "sockets.nim");
	LOC3 = 0;
	LOC3 = toint_194641(protocol);
	LOC4 = 0;
	LOC4 = socket(LOC1, LOC2, LOC3);
	result = newtsocket_194204(LOC4, buffered);
	popFrame();
	return result;
}

N_NIMCALL(void, setblocking_197411)(tsocketimpl193807* s, NIM_BOOL blocking) {
	NI x;
	int LOC1;
	nimfr("setBlocking", "sockets.nim")
	nimln(1690, "sockets.nim");
	nimln(1690, "sockets.nim");
	LOC1 = 0;
	LOC1 = fcntl((*s).Fd, F_GETFL, 0);
	x = ((NI) (LOC1));
	nimln(1691, "sockets.nim");
	{
		NI32 LOC6;
		nimln(1691, "sockets.nim");
		if (!(x == -1)) goto LA4;
		nimln(1692, "sockets.nim");
		nimln(1692, "sockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_123041();
		raiseoserror_123009(LOC6);
	}
	goto LA2;
	LA4: ;
	{
		NI mode;
		nimln(1694, "sockets.nim");
		nimln(1694, "sockets.nim");
		{
			if (!blocking) goto LA10;
			nimln(1694, "sockets.nim");
			nimln(1694, "sockets.nim");
			mode = (NI)(x & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));
		}
		goto LA8;
		LA10: ;
		{
			nimln(1694, "sockets.nim");
			mode = (NI)(x | ((NI) (O_NONBLOCK)));
		}
		LA8: ;
		nimln(1695, "sockets.nim");
		{
			int LOC15;
			NI32 LOC18;
			nimln(1695, "sockets.nim");
			nimln(1695, "sockets.nim");
			LOC15 = 0;
			LOC15 = fcntl((*s).Fd, F_SETFL, mode);
			if (!(LOC15 == ((NI32) -1))) goto LA16;
			nimln(1696, "sockets.nim");
			nimln(1696, "sockets.nim");
			LOC18 = 0;
			LOC18 = oslasterror_123041();
			raiseoserror_123009(LOC18);
		}
		LA16: ;
	}
	LA2: ;
	nimln(1697, "sockets.nim");
	nimln(1697, "sockets.nim");
	(*s).Nonblocking = !(blocking);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, send_203664)(tsocketimpl193807* socket, void* data, NI size) {
	NI result;
	nimfr("send", "sockets.nim")
	result = 0;
	nimln(1575, "sockets.nim");
	result = send((*socket).Fd, data, ((NI) (((int)chckRange(size, ((int) (-2147483647 -1)), ((int) 2147483647))))), ((NI32) 0));
	popFrame();
	return result;
}

N_NIMCALL(NI, sendasync_204229)(tsocketimpl193807* socket, NimStringDesc* data) {
	NI result;
	nimfr("sendAsync", "sockets.nim")
	result = 0;
	nimln(1604, "sockets.nim");
	nimln(1604, "sockets.nim");
	result = send_203664(socket, ((void*) (data->data)), data->Sup.len);
	nimln(1623, "sockets.nim");
	{
		NI32 err;
		nimln(1623, "sockets.nim");
		if (!(result == -1)) goto LA3;
		nimln(1624, "sockets.nim");
		err = oslasterror_123041();
		nimln(1630, "sockets.nim");
		{
			NIM_BOOL LOC7;
			nimln(1630, "sockets.nim");
			LOC7 = 0;
			nimln(1630, "sockets.nim");
			LOC7 = (err == EAGAIN);
			if (LOC7) goto LA8;
			nimln(1630, "sockets.nim");
			LOC7 = (err == EWOULDBLOCK);
			LA8: ;
			if (!LOC7) goto LA9;
			nimln(1631, "sockets.nim");
			nimln(1631, "sockets.nim");
			result = 0;
			goto BeforeRet;
		}
		goto LA5;
		LA9: ;
		{
			nimln(1632, "sockets.nim");
			raiseoserror_123009(err);
		}
		LA5: ;
	}
	LA3: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, getfd_205419)(tsocketimpl193807* socket) {
	int result;
	nimfr("getFD", "sockets.nim")
	result = 0;
	nimln(1728, "sockets.nim");
	nimln(1728, "sockets.nim");
	result = (*socket).Fd;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, hasdatabuffered_200939)(tsocketimpl193807* s) {
	NIM_BOOL result;
	nimfr("hasDataBuffered", "sockets.nim")
	result = 0;
	nimln(962, "sockets.nim");
	result = NIM_FALSE;
	nimln(963, "sockets.nim");
	{
		NIM_BOOL LOC5;
		if (!(*s).Isbuffered) goto LA3;
		nimln(964, "sockets.nim");
		nimln(964, "sockets.nim");
		LOC5 = 0;
		nimln(964, "sockets.nim");
		if (!(((2 &(1<<(((*s).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
		LOC5 = (0 < (*s).isbufferedU.S1.Buflen);
		if (!(LOC5)) goto LA6;
		nimln(964, "sockets.nim");
		nimln(964, "sockets.nim");
		if (!(((2 &(1<<(((*s).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
		if (!(((2 &(1<<(((*s).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
		LOC5 = !(((*s).isbufferedU.S1.Currpos == (*s).isbufferedU.S1.Buflen));
		LA6: ;
		result = LOC5;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, connectasync_199823)(tsocketimpl193807* socket, NimStringDesc* name, NU16 port, NU8 af) {
	struct addrinfo hints;
	struct addrinfo* ailist;
	NIM_BOOL success;
	NI32 lasterror;
	struct addrinfo* it;
	nimfr("connectAsync", "sockets.nim")
	memset((void*)(&hints), 0, sizeof(hints));
	nimln(861, "sockets.nim");
	ailist = NIM_NIL;
	nimln(862, "sockets.nim");
	hints.ai_family = toint_194627(af);
	nimln(863, "sockets.nim");
	hints.ai_socktype = toint_194634(((NU8) 1));
	nimln(864, "sockets.nim");
	hints.ai_protocol = toint_194641(((NU8) 6));
	{
		int gairesult_199833;
		NimStringDesc* LOC2;
		nimln(438, "sockets.nim");
		nimln(438, "sockets.nim");
		LOC2 = 0;
		LOC2 = HEX24_6201(port);
		gairesult_199833 = getaddrinfo(name->data, LOC2->data, (&hints), &ailist);
		nimln(439, "sockets.nim");
		{
			oserror3233* e_200002;
			NCSTRING LOC7;
			nimln(439, "sockets.nim");
			nimln(439, "sockets.nim");
			if (!!((gairesult_199833 == ((NI32) 0)))) goto LA5;
			e_200002 = 0;
			nimln(2149, "system.nim");
			e_200002 = (oserror3233*) newObj((&NTI148404), sizeof(oserror3233));
			(*e_200002).Sup.Sup.Sup.m_type = (&NTI3233);
			nimln(2150, "system.nim");
			nimln(443, "sockets.nim");
			nimln(443, "sockets.nim");
			LOC7 = 0;
			LOC7 = gai_strerror(gairesult_199833);
			asgnRefNoCycle((void**) (&(*e_200002).Sup.Sup.message), cstrToNimstr(LOC7));
			nimln(443, "sockets.nim");
			raiseException((Exception*)e_200002, "OSError");
		}
		LA5: ;
	}
	nimln(867, "sockets.nim");
	success = NIM_FALSE;
	lasterror = 0;
	nimln(869, "sockets.nim");
	it = ailist;
	{
		nimln(870, "sockets.nim");
		while (1) {
			int ret;
			nimln(870, "sockets.nim");
			nimln(870, "sockets.nim");
			if (!!((it == NIM_NIL))) goto LA9;
			nimln(871, "sockets.nim");
			ret = connect((*socket).Fd, (*it).ai_addr, (*it).ai_addrlen);
			nimln(872, "sockets.nim");
			{
				nimln(872, "sockets.nim");
				if (!(ret == ((NI32) 0))) goto LA12;
				nimln(873, "sockets.nim");
				success = NIM_TRUE;
				nimln(874, "sockets.nim");
				goto LA8;
			}
			goto LA10;
			LA12: ;
			{
				nimln(876, "sockets.nim");
				lasterror = oslasterror_123041();
				nimln(883, "sockets.nim");
				{
					NIM_BOOL LOC17;
					nimln(883, "sockets.nim");
					LOC17 = 0;
					nimln(883, "sockets.nim");
					LOC17 = (lasterror == EINTR);
					if (LOC17) goto LA18;
					nimln(883, "sockets.nim");
					LOC17 = (lasterror == EINPROGRESS);
					LA18: ;
					if (!LOC17) goto LA19;
					nimln(884, "sockets.nim");
					success = NIM_TRUE;
					nimln(885, "sockets.nim");
					goto LA8;
				}
				LA19: ;
			}
			LA10: ;
			nimln(887, "sockets.nim");
			it = (*it).ai_next;
		} LA9: ;
	} LA8: ;
	nimln(889, "sockets.nim");
	freeaddrinfo(ailist);
	nimln(890, "sockets.nim");
	{
		nimln(890, "sockets.nim");
		if (!!(success)) goto LA23;
		nimln(890, "sockets.nim");
		raiseoserror_123009(lasterror);
	}
	LA23: ;
	popFrame();
}

N_NIMCALL(void, close_197678)(tsocketimpl193807* socket) {
	int LOC1;
	nimfr("close", "sockets.nim")
	nimln(654, "sockets.nim");
	nimln(654, "sockets.nim");
	LOC1 = 0;
	LOC1 = close((*socket).Fd);
	popFrame();
}

N_NIMCALL(NI16, ntohs_194407)(NI16 x) {
	NI16 result;
	nimfr("ntohs", "sockets.nim")
	result = 0;
	nimln(195, "sockets.nim");
	nimln(195, "sockets.nim");
	nimln(195, "sockets.nim");
	nimln(195, "sockets.nim");
	result = (NI16)((NI16)((NU16)(x) >> (NU16)(((NI16) 8))) | (NI16)((NU16)(x) << (NU16)(((NI16) 8))));
	popFrame();
	return result;
}

N_NIMCALL(NI16, htons_194617)(NI16 x) {
	NI16 result;
	nimfr("htons", "sockets.nim")
	result = 0;
	nimln(207, "sockets.nim");
	result = ntohs_194407(x);
	popFrame();
	return result;
}

N_NIMCALL(NI32, ntohl_194270)(NI32 x) {
	NI32 result;
	nimfr("ntohl", "sockets.nim")
	result = 0;
	nimln(185, "sockets.nim");
	nimln(187, "sockets.nim");
	nimln(186, "sockets.nim");
	nimln(185, "sockets.nim");
	nimln(185, "sockets.nim");
	nimln(186, "sockets.nim");
	nimln(186, "sockets.nim");
	nimln(187, "sockets.nim");
	nimln(187, "sockets.nim");
	nimln(188, "sockets.nim");
	result = (NI32)((NI32)((NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 24))) | (NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 8))) & ((NI32) 65280))) | (NI32)((NI32)((NU32)(x) << (NU32)(((NI32) 8))) & ((NI32) 16711680))) | (NI32)((NU32)(x) << (NU32)(((NI32) 24))));
	popFrame();
	return result;
}

N_NIMCALL(NI32, htonl_194607)(NI32 x) {
	NI32 result;
	nimfr("htonl", "sockets.nim")
	result = 0;
	nimln(201, "sockets.nim");
	result = ntohl_194270(x);
	popFrame();
	return result;
}

N_NIMCALL(void, bindaddr_195974)(tsocketimpl193807* socket, NU16 port, NimStringDesc* address) {
	nimfr("bindAddr", "sockets.nim")
	nimln(451, "sockets.nim");
	{
		struct sockaddr_in name;
		nimln(451, "sockets.nim");
		if (!((address) && (address)->Sup.len == 0)) goto LA3;
		memset((void*)(&name), 0, sizeof(name));
		nimln(456, "sockets.nim");
		name.sin_family = AF_INET;
		nimln(457, "sockets.nim");
		name.sin_port = htons_194617(((NI16)chckRange(port, ((NI16) -32768), ((NI16) 32767))));
		nimln(458, "sockets.nim");
		name.sin_addr.s_addr = htonl_194607(INADDR_ANY);
		nimln(459, "sockets.nim");
		{
			int LOC7;
			NI32 LOC10;
			nimln(460, "sockets.nim");
			nimln(459, "sockets.nim");
			nimln(460, "sockets.nim");
			LOC7 = 0;
			LOC7 = bind((*socket).Fd, ((struct sockaddr*) ((&name))), ((socklen_t) (((NI)sizeof(struct sockaddr_in)))));
			if (!(LOC7 < ((NI32) 0))) goto LA8;
			nimln(461, "sockets.nim");
			nimln(461, "sockets.nim");
			LOC10 = 0;
			LOC10 = oslasterror_123041();
			raiseoserror_123009(LOC10);
		}
		LA8: ;
	}
	goto LA1;
	LA3: ;
	{
		struct addrinfo hints;
		struct addrinfo* ailist;
		memset((void*)(&hints), 0, sizeof(hints));
		nimln(464, "sockets.nim");
		ailist = NIM_NIL;
		nimln(465, "sockets.nim");
		hints.ai_family = toint_194627(((NU8) 2));
		nimln(466, "sockets.nim");
		hints.ai_socktype = toint_194634(((NU8) 1));
		nimln(467, "sockets.nim");
		hints.ai_protocol = toint_194641(((NU8) 6));
		{
			int gairesult_196008;
			NimStringDesc* LOC13;
			nimln(438, "sockets.nim");
			nimln(438, "sockets.nim");
			LOC13 = 0;
			LOC13 = HEX24_6201(port);
			gairesult_196008 = getaddrinfo(address->data, LOC13->data, (&hints), &ailist);
			nimln(439, "sockets.nim");
			{
				oserror3233* e_196202;
				NCSTRING LOC18;
				nimln(439, "sockets.nim");
				nimln(439, "sockets.nim");
				if (!!((gairesult_196008 == ((NI32) 0)))) goto LA16;
				e_196202 = 0;
				nimln(2149, "system.nim");
				e_196202 = (oserror3233*) newObj((&NTI148404), sizeof(oserror3233));
				(*e_196202).Sup.Sup.Sup.m_type = (&NTI3233);
				nimln(2150, "system.nim");
				nimln(443, "sockets.nim");
				nimln(443, "sockets.nim");
				LOC18 = 0;
				LOC18 = gai_strerror(gairesult_196008);
				asgnRefNoCycle((void**) (&(*e_196202).Sup.Sup.message), cstrToNimstr(LOC18));
				nimln(443, "sockets.nim");
				raiseException((Exception*)e_196202, "OSError");
			}
			LA16: ;
		}
		nimln(469, "sockets.nim");
		{
			int LOC21;
			NI32 LOC24;
			nimln(469, "sockets.nim");
			nimln(469, "sockets.nim");
			LOC21 = 0;
			LOC21 = bind((*socket).Fd, (*ailist).ai_addr, (*ailist).ai_addrlen);
			if (!(LOC21 < ((NI32) 0))) goto LA22;
			nimln(470, "sockets.nim");
			nimln(470, "sockets.nim");
			LOC24 = 0;
			LOC24 = oslasterror_123041();
			raiseoserror_123009(LOC24);
		}
		LA22: ;
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, listen_195809)(tsocketimpl193807* socket, int backlog) {
	nimfr("listen", "sockets.nim")
	nimln(402, "sockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(402, "sockets.nim");
		nimln(402, "sockets.nim");
		LOC3 = 0;
		LOC3 = listen((*socket).Fd, backlog);
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(402, "sockets.nim");
		nimln(402, "sockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_123041();
		raiseoserror_123009(LOC6);
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, acceptaddr_196448)(tsocketimpl193807* server, tsocketimpl193807** client, NimStringDesc** address) {
	struct sockaddr_in sockaddress_196456;
	socklen_t addrlen_196458;
	int sock_196460;
	nimfr("acceptAddr", "sockets.nim")
	nimln(489, "sockets.nim");
	{
		nimln(489, "sockets.nim");
		nimln(489, "sockets.nim");
		nimln(489, "sockets.nim");
		if (!!(!(((*client) == NIM_NIL)))) goto LA3;
		nimln(489, "sockets.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP825));
	}
	LA3: ;
	memset((void*)(&sockaddress_196456), 0, sizeof(sockaddress_196456));
	nimln(491, "sockets.nim");
	nimln(491, "sockets.nim");
	addrlen_196458 = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln(492, "sockets.nim");
	sock_196460 = accept((*server).Fd, ((struct sockaddr*) ((&sockaddress_196456))), (&addrlen_196458));
	nimln(495, "sockets.nim");
	{
		NI32 err_196462;
		nimln(495, "sockets.nim");
		if (!(sock_196460 == osinvalidsocket_194004)) goto LA7;
		nimln(496, "sockets.nim");
		err_196462 = oslasterror_123041();
		nimln(507, "sockets.nim");
		{
			NIM_BOOL LOC11;
			nimln(507, "sockets.nim");
			LOC11 = 0;
			nimln(507, "sockets.nim");
			LOC11 = (err_196462 == EAGAIN);
			if (LOC11) goto LA12;
			nimln(507, "sockets.nim");
			LOC11 = (err_196462 == EWOULDBLOCK);
			LA12: ;
			if (!LOC11) goto LA13;
			nimln(508, "sockets.nim");
			unsureAsgnRef((void**) (&(*client)), NIM_NIL);
			nimln(509, "sockets.nim");
			unsureAsgnRef((void**) (&(*address)), copyString(((NimStringDesc*) &TMP826)));
			nimln(511, "sockets.nim");
			goto BeforeRet;
		}
		goto LA9;
		LA13: ;
		{
			nimln(514, "sockets.nim");
			raiseoserror_123009(err_196462);
		}
		LA9: ;
	}
	goto LA5;
	LA7: ;
	{
		NIM_BOOL LOC17;
		NCSTRING LOC18;
		nimln(516, "sockets.nim");
		(*(*client)).Fd = sock_196460;
		nimln(517, "sockets.nim");
		LOC17 = 0;
		LOC17 = (*server).Isbuffered;
		FieldDiscriminantCheck((NI)(NU)((*(*client)).Isbuffered), (NI)(NU)(LOC17), NimDT_193807_isbuffered, 3);
		(*(*client)).Isbuffered = LOC17;
		nimln(520, "sockets.nim");
		nimln(520, "sockets.nim");
		nimln(520, "sockets.nim");
		LOC18 = 0;
		LOC18 = inet_ntoa(sockaddress_196456.sin_addr);
		unsureAsgnRef((void**) (&(*address)), cstrToNimstr(LOC18));
		nimln(522, "sockets.nim");
		goto BeforeRet;
	}
	LA5: ;
	BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, raisesocketerror_195201)(tsocketimpl193807* socket, NI err, NIM_BOOL async) {
	nimfr("raiseSocketError", "sockets.nim")
	nimln(385, "sockets.nim");
	{
		NIM_BOOL LOC3;
		NI32 lasterror;
		nimln(385, "sockets.nim");
		LOC3 = 0;
		nimln(385, "sockets.nim");
		LOC3 = (err == -1);
		if (!(LOC3)) goto LA4;
		LOC3 = NIM_TRUE;
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(386, "sockets.nim");
		lasterror = oslasterror_123041();
		nimln(387, "sockets.nim");
		{
			if (!async) goto LA9;
			nimln(393, "sockets.nim");
			{
				NIM_BOOL LOC13;
				nimln(393, "sockets.nim");
				LOC13 = 0;
				nimln(393, "sockets.nim");
				LOC13 = (lasterror == EAGAIN);
				if (LOC13) goto LA14;
				nimln(393, "sockets.nim");
				LOC13 = (lasterror == EWOULDBLOCK);
				LA14: ;
				if (!LOC13) goto LA15;
				nimln(394, "sockets.nim");
				goto BeforeRet;
			}
			goto LA11;
			LA15: ;
			{
				nimln(395, "sockets.nim");
				raiseoserror_123009(lasterror);
			}
			LA11: ;
		}
		goto LA7;
		LA9: ;
		{
			nimln(396, "sockets.nim");
			raiseoserror_123009(lasterror);
		}
		LA7: ;
	}
	LA5: ;
	BeforeRet: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
	result = 0;
	{
		if (!(b == 0)) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == -1);
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI64)(a / b);
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(struct timeval, timevalfrommilliseconds_200601)(NI timeout) {
	struct timeval result;
	nimfr("timeValFromMilliseconds", "sockets.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(937, "sockets.nim");
	{
		NI seconds;
		NI TMP834;
		NI TMP835;
		NI TMP836;
		NI TMP837;
		nimln(937, "sockets.nim");
		nimln(937, "sockets.nim");
		if (!!((timeout == -1))) goto LA3;
		nimln(938, "sockets.nim");
		nimln(938, "sockets.nim");
		TMP834 = divInt(timeout, 1000);
		seconds = (NI64)(TMP834);
		nimln(939, "sockets.nim");
		result.tv_sec = ((NI) (((NI32)chckRange(seconds, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
		nimln(940, "sockets.nim");
		nimln(940, "sockets.nim");
		nimln(940, "sockets.nim");
		nimln(940, "sockets.nim");
		TMP835 = mulInt(seconds, 1000);
		TMP836 = subInt(timeout, (NI64)(TMP835));
		TMP837 = mulInt((NI64)(TMP836), 1000);
		result.tv_usec = ((NI) (((NI32)chckRange((NI64)(TMP837), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, createfdset_200616)(fd_set* fd, TY202215* s, NI* m) {
	nimfr("createFdSet", "sockets.nim")
	nimln(943, "sockets.nim");
	FD_ZERO(fd);
	{
		tsocketimpl193807* i_200822;
		NI i_200838;
		NI l_200840;
		i_200822 = 0;
		nimln(2986, "system.nim");
		i_200838 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_200840 = s->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_200838 < l_200840)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_200838) >= (NU)(s->Sup.len)) raiseIndexError();
				i_200822 = s->data[i_200838];
				nimln(945, "sockets.nim");
				nimln(945, "sockets.nim");
				(*m) = (((*m) >= ((NI) ((*i_200822).Fd))) ? (*m) : ((NI) ((*i_200822).Fd)));
				nimln(946, "sockets.nim");
				FD_SET((*i_200822).Fd, fd);
				nimln(2990, "system.nim");
				i_200838 = addInt(i_200838, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((s->Sup.len == l_200840))) goto LA6;
					nimln(2991, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP838));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, prunesocketset_200856)(TY202215** s, fd_set* fd) {
	NI i;
	NI l;
	nimfr("pruneSocketSet", "sockets.nim")
	nimln(949, "sockets.nim");
	i = 0;
	nimln(950, "sockets.nim");
	nimln(950, "sockets.nim");
	l = (*s)->Sup.len;
	{
		nimln(951, "sockets.nim");
		while (1) {
			nimln(951, "sockets.nim");
			if (!(i < l)) goto LA2;
			nimln(952, "sockets.nim");
			{
				int LOC5;
				NI TMP841;
				nimln(952, "sockets.nim");
				nimln(952, "sockets.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				LOC5 = 0;
				LOC5 = FD_ISSET((*(*s)->data[i]).Fd, fd);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(954, "sockets.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				nimln(954, "sockets.nim");
				TMP841 = subInt(l, 1);
				if ((NU)((NI64)(TMP841)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				asgnRefNoCycle((void**) (&(*s)->data[i]), (*s)->data[(NI64)(TMP841)]);
				nimln(955, "sockets.nim");
				l = subInt(l, 1);
			}
			goto LA3;
			LA6: ;
			{
				nimln(957, "sockets.nim");
				i = addInt(i, 1);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(958, "sockets.nim");
	(*s) = (TY202215*) setLengthSeq(&((*s))->Sup, sizeof(tsocketimpl193807*), l);
	popFrame();
}

N_NIMCALL(NI, selectwrite_201244)(TY202215** writefds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set wr;
	NI m;
	nimfr("selectWrite", "sockets.nim")
	result = 0;
	nimln(1043, "sockets.nim");
	tv = timevalfrommilliseconds_200601(timeout);
	memset((void*)(&wr), 0, sizeof(wr));
	nimln(1046, "sockets.nim");
	m = 0;
	nimln(1047, "sockets.nim");
	createfdset_200616((&wr), (*writefds), (&m));
	nimln(1049, "sockets.nim");
	{
		NI TMP839;
		int LOC5;
		nimln(1049, "sockets.nim");
		nimln(1049, "sockets.nim");
		if (!!((timeout == -1))) goto LA3;
		nimln(1050, "sockets.nim");
		nimln(1050, "sockets.nim");
		nimln(1050, "sockets.nim");
		TMP839 = addInt(m, 1);
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI64)(TMP839), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP840;
		int LOC7;
		nimln(1052, "sockets.nim");
		nimln(1052, "sockets.nim");
		nimln(1052, "sockets.nim");
		TMP840 = addInt(m, 1);
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI64)(TMP840), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(1054, "sockets.nim");
	prunesocketset_200856(writefds, (&wr));
	popFrame();
	return result;
}

N_NIMCALL(NI, readintobuf_201360)(tsocketimpl193807* socket, NI32 flags) {
	NI result;
	nimfr("readIntoBuf", "sockets.nim")
	result = 0;
	nimln(1075, "sockets.nim");
	result = 0;
	nimln(1082, "sockets.nim");
	if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP842));
	result = recv((*socket).Fd, ((void*) ((*socket).isbufferedU.S1.Buffer)), 4000, flags);
	nimln(1083, "sockets.nim");
	{
		nimln(1083, "sockets.nim");
		if (!(result <= 0)) goto LA3;
		nimln(1084, "sockets.nim");
		if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
		(*socket).isbufferedU.S1.Buflen = 0;
		nimln(1085, "sockets.nim");
		if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
		(*socket).isbufferedU.S1.Currpos = 0;
		nimln(1086, "sockets.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(1087, "sockets.nim");
	if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
	(*socket).isbufferedU.S1.Buflen = result;
	nimln(1088, "sockets.nim");
	if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
	(*socket).isbufferedU.S1.Currpos = 0;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, recv_201502)(tsocketimpl193807* socket, void* data, NI size) {
	NI result;
	nimfr("recv", "sockets.nim")
	result = 0;
	nimln(1103, "sockets.nim");
	{
		nimln(1103, "sockets.nim");
		if (!(size == 0)) goto LA3;
		nimln(1103, "sockets.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(1104, "sockets.nim");
	{
		NI read;
		if (!(*socket).Isbuffered) goto LA7;
		nimln(1105, "sockets.nim");
		{
			NI res;
			nimln(1105, "sockets.nim");
			if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
			if (!((*socket).isbufferedU.S1.Buflen == 0)) goto LA11;
			nimln(1091, "sockets.nim");
			res = readintobuf_201360(socket, ((NI32) 0));
			nimln(1092, "sockets.nim");
			{
				nimln(1092, "sockets.nim");
				if (!(res <= 0)) goto LA15;
				nimln(1093, "sockets.nim");
				{
					if (!NIM_FALSE) goto LA19;
					nimln(1094, "sockets.nim");
					nimln(1106, "sockets.nim");
					result = 0;
					goto BeforeRet;
				}
				goto LA17;
				LA19: ;
				{
					nimln(1096, "sockets.nim");
					nimln(1096, "sockets.nim");
					result = res;
					goto BeforeRet;
				}
				LA17: ;
			}
			LA15: ;
		}
		LA11: ;
		nimln(1108, "sockets.nim");
		read = 0;
		{
			nimln(1109, "sockets.nim");
			while (1) {
				NI chunk;
				NI TMP843;
				NI TMP844;
				NCSTRING d;
				nimln(1109, "sockets.nim");
				if (!(read < size)) goto LA23;
				nimln(1110, "sockets.nim");
				{
					NI res;
					nimln(1110, "sockets.nim");
					if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
					if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
					if (!((*socket).isbufferedU.S1.Buflen <= (*socket).isbufferedU.S1.Currpos)) goto LA26;
					nimln(1091, "sockets.nim");
					res = readintobuf_201360(socket, ((NI32) 0));
					nimln(1092, "sockets.nim");
					{
						nimln(1092, "sockets.nim");
						if (!(res <= 0)) goto LA30;
						nimln(1093, "sockets.nim");
						{
							nimln(1093, "sockets.nim");
							if (!(0 < read)) goto LA34;
							nimln(1094, "sockets.nim");
							nimln(1111, "sockets.nim");
							result = read;
							goto BeforeRet;
						}
						goto LA32;
						LA34: ;
						{
							nimln(1096, "sockets.nim");
							nimln(1096, "sockets.nim");
							result = res;
							goto BeforeRet;
						}
						LA32: ;
					}
					LA30: ;
				}
				LA26: ;
				nimln(1113, "sockets.nim");
				nimln(1113, "sockets.nim");
				nimln(1113, "sockets.nim");
				if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
				if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
				TMP843 = subInt((*socket).isbufferedU.S1.Buflen, (*socket).isbufferedU.S1.Currpos);
				nimln(1113, "sockets.nim");
				TMP844 = subInt(size, read);
				chunk = (((NI64)(TMP843) <= (NI64)(TMP844)) ? (NI64)(TMP843) : (NI64)(TMP844));
				nimln(1114, "sockets.nim");
				d = ((NCSTRING) (data));
				nimln(1115, "sockets.nim");
				if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP842));
				if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
				if ((NU)((*socket).isbufferedU.S1.Currpos) > (NU)(4000)) raiseIndexError();
				memcpy(((void*) ((&d[read]))), ((void*) ((&(*socket).isbufferedU.S1.Buffer[((*socket).isbufferedU.S1.Currpos)- 0]))), chunk);
				nimln(1116, "sockets.nim");
				read = addInt(read, chunk);
				nimln(1117, "sockets.nim");
				if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
				(*socket).isbufferedU.S1.Currpos = addInt((*socket).isbufferedU.S1.Currpos, chunk);
			} LA23: ;
		}
		nimln(1119, "sockets.nim");
		result = read;
	}
	goto LA5;
	LA7: ;
	{
		nimln(1136, "sockets.nim");
		result = recv((*socket).Fd, data, ((NI) (((int)chckRange(size, ((int) (-2147483647 -1)), ((int) 2147483647))))), ((NI32) 0));
	}
	LA5: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, peekchar_202338)(tsocketimpl193807* socket, NIM_CHAR* c) {
	NI result;
	nimfr("peekChar", "sockets.nim")
	result = 0;
	nimln(1225, "sockets.nim");
	{
		if (!(*socket).Isbuffered) goto LA3;
		nimln(1226, "sockets.nim");
		result = 1;
		nimln(1227, "sockets.nim");
		{
			NIM_BOOL LOC7;
			NI TMP845;
			NI res;
			nimln(1227, "sockets.nim");
			LOC7 = 0;
			nimln(1227, "sockets.nim");
			if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
			LOC7 = ((*socket).isbufferedU.S1.Buflen == 0);
			if (LOC7) goto LA8;
			nimln(1227, "sockets.nim");
			nimln(1227, "sockets.nim");
			if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP823));
			TMP845 = subInt((*socket).isbufferedU.S1.Buflen, 1);
			if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
			LOC7 = ((NI64)(TMP845) < (*socket).isbufferedU.S1.Currpos);
			LA8: ;
			if (!LOC7) goto LA9;
			nimln(1228, "sockets.nim");
			res = readintobuf_201360(socket, ((NI32) 0));
			nimln(1229, "sockets.nim");
			{
				nimln(1229, "sockets.nim");
				if (!(res <= 0)) goto LA13;
				nimln(1230, "sockets.nim");
				result = res;
			}
			LA13: ;
		}
		LA9: ;
		nimln(1232, "sockets.nim");
		if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP842));
		if (!(((2 &(1<<(((*socket).Isbuffered)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP813));
		if ((NU)((*socket).isbufferedU.S1.Currpos) > (NU)(4000)) raiseIndexError();
		(*c) = (*socket).isbufferedU.S1.Buffer[((*socket).isbufferedU.S1.Currpos)- 0];
	}
	goto LA1;
	LA3: ;
	{
		nimln(1242, "sockets.nim");
		result = recv((*socket).Fd, ((void*) (c)), 1, MSG_PEEK);
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NU8, recvlineasync_202685)(tsocketimpl193807* socket, NimStringDesc** line) {
	NU8 result;
	nimfr("recvLineAsync", "sockets.nim")
	result = 0;
	nimln(1346, "sockets.nim");
	(*line) = setLengthStr((*line), 0);
	{
		nimln(1347, "sockets.nim");
		while (1) {
			NIM_CHAR c;
			NI n;
			c = 0;
			nimln(1349, "sockets.nim");
			n = recv_201502(socket, ((void*) ((&c))), 1);
			nimln(1350, "sockets.nim");
			{
				nimln(1350, "sockets.nim");
				if (!(n < 0)) goto LA5;
				nimln(1351, "sockets.nim");
				nimln(1351, "sockets.nim");
				nimln(1351, "sockets.nim");
				{
					nimln(1351, "sockets.nim");
					nimln(1351, "sockets.nim");
					if (!((*line)->Sup.len == 0)) goto LA9;
					result = ((NU8) 3);
				}
				goto LA7;
				LA9: ;
				{
					result = ((NU8) 1);
				}
				LA7: ;
				goto BeforeRet;
			}
			goto LA3;
			LA5: ;
			{
				nimln(1352, "sockets.nim");
				if (!(n == 0)) goto LA13;
				nimln(1353, "sockets.nim");
				nimln(1353, "sockets.nim");
				nimln(1353, "sockets.nim");
				{
					nimln(1353, "sockets.nim");
					nimln(1353, "sockets.nim");
					if (!((*line)->Sup.len == 0)) goto LA17;
					result = ((NU8) 2);
				}
				goto LA15;
				LA17: ;
				{
					result = ((NU8) 1);
				}
				LA15: ;
				goto BeforeRet;
			}
			goto LA3;
			LA13: ;
			LA3: ;
			nimln(1354, "sockets.nim");
			{
				nimln(1354, "sockets.nim");
				if (!((NU8)(c) == (NU8)(13))) goto LA22;
				nimln(1355, "sockets.nim");
				n = peekchar_202338(socket, (&c));
				nimln(1356, "sockets.nim");
				{
					NIM_BOOL LOC26;
					NI LOC30;
					nimln(1356, "sockets.nim");
					LOC26 = 0;
					nimln(1356, "sockets.nim");
					LOC26 = (0 < n);
					if (!(LOC26)) goto LA27;
					nimln(1356, "sockets.nim");
					LOC26 = ((NU8)(c) == (NU8)(10));
					LA27: ;
					if (!LOC26) goto LA28;
					nimln(1357, "sockets.nim");
					nimln(1357, "sockets.nim");
					LOC30 = 0;
					LOC30 = recv_201502(socket, ((void*) ((&c))), 1);
				}
				goto LA24;
				LA28: ;
				{
					nimln(1358, "sockets.nim");
					if (!(n <= 0)) goto LA32;
					nimln(1359, "sockets.nim");
					nimln(1359, "sockets.nim");
					nimln(1359, "sockets.nim");
					{
						nimln(1359, "sockets.nim");
						nimln(1359, "sockets.nim");
						if (!((*line)->Sup.len == 0)) goto LA36;
						result = ((NU8) 3);
					}
					goto LA34;
					LA36: ;
					{
						result = ((NU8) 1);
					}
					LA34: ;
					goto BeforeRet;
				}
				goto LA24;
				LA32: ;
				LA24: ;
				nimln(1360, "sockets.nim");
				nimln(1360, "sockets.nim");
				result = ((NU8) 0);
				goto BeforeRet;
			}
			goto LA20;
			LA22: ;
			{
				nimln(1361, "sockets.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA40;
				nimln(1361, "sockets.nim");
				nimln(1361, "sockets.nim");
				result = ((NU8) 0);
				goto BeforeRet;
			}
			goto LA20;
			LA40: ;
			LA20: ;
			nimln(1362, "sockets.nim");
			(*line) = addChar((*line), c);
		}
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NU8, readlineasync_202714)(tsocketimpl193807* socket, NimStringDesc** line) {
	NU8 result;
	nimfr("readLineAsync", "sockets.nim")
	result = 0;
	nimln(1375, "sockets.nim");
	(*line) = setLengthStr((*line), 0);
	{
		nimln(1381, "sockets.nim");
		while (1) {
			NIM_CHAR c;
			NI n;
			c = 0;
			nimln(1383, "sockets.nim");
			n = recv_201502(socket, ((void*) ((&c))), 1);
			nimln(1385, "sockets.nim");
			{
				nimln(1385, "sockets.nim");
				if (!(n < 0)) goto LA5;
				nimln(1386, "sockets.nim");
				{
					nimln(1386, "sockets.nim");
					nimln(1386, "sockets.nim");
					if (!((*line)->Sup.len == 0)) goto LA9;
					nimln(1378, "sockets.nim");
					raisesocketerror_195201(socket, -1, NIM_TRUE);
					nimln(1379, "sockets.nim");
					nimln(1379, "sockets.nim");
					result = ((NU8) 3);
					goto BeforeRet;
				}
				goto LA7;
				LA9: ;
				{
					nimln(1386, "sockets.nim");
					nimln(1386, "sockets.nim");
					result = ((NU8) 1);
					goto BeforeRet;
				}
				LA7: ;
			}
			goto LA3;
			LA5: ;
			{
				nimln(1387, "sockets.nim");
				if (!(n == 0)) goto LA13;
				nimln(1388, "sockets.nim");
				nimln(1388, "sockets.nim");
				nimln(1388, "sockets.nim");
				{
					nimln(1388, "sockets.nim");
					nimln(1388, "sockets.nim");
					if (!((*line)->Sup.len == 0)) goto LA17;
					result = ((NU8) 2);
				}
				goto LA15;
				LA17: ;
				{
					result = ((NU8) 1);
				}
				LA15: ;
				goto BeforeRet;
			}
			goto LA3;
			LA13: ;
			LA3: ;
			nimln(1389, "sockets.nim");
			{
				nimln(1389, "sockets.nim");
				if (!((NU8)(c) == (NU8)(13))) goto LA22;
				nimln(1390, "sockets.nim");
				n = peekchar_202338(socket, (&c));
				nimln(1391, "sockets.nim");
				{
					NIM_BOOL LOC26;
					NI LOC30;
					nimln(1391, "sockets.nim");
					LOC26 = 0;
					nimln(1391, "sockets.nim");
					LOC26 = (0 < n);
					if (!(LOC26)) goto LA27;
					nimln(1391, "sockets.nim");
					LOC26 = ((NU8)(c) == (NU8)(10));
					LA27: ;
					if (!LOC26) goto LA28;
					nimln(1392, "sockets.nim");
					nimln(1392, "sockets.nim");
					LOC30 = 0;
					LOC30 = recv_201502(socket, ((void*) ((&c))), 1);
				}
				goto LA24;
				LA28: ;
				{
					nimln(1393, "sockets.nim");
					if (!(n <= 0)) goto LA32;
					nimln(1394, "sockets.nim");
					{
						nimln(1394, "sockets.nim");
						nimln(1394, "sockets.nim");
						if (!((*line)->Sup.len == 0)) goto LA36;
						nimln(1378, "sockets.nim");
						raisesocketerror_195201(socket, -1, NIM_TRUE);
						nimln(1379, "sockets.nim");
						nimln(1379, "sockets.nim");
						result = ((NU8) 3);
						goto BeforeRet;
					}
					goto LA34;
					LA36: ;
					{
						nimln(1394, "sockets.nim");
						nimln(1394, "sockets.nim");
						result = ((NU8) 1);
						goto BeforeRet;
					}
					LA34: ;
				}
				goto LA24;
				LA32: ;
				LA24: ;
				nimln(1395, "sockets.nim");
				nimln(1395, "sockets.nim");
				result = ((NU8) 0);
				goto BeforeRet;
			}
			goto LA20;
			LA22: ;
			{
				nimln(1396, "sockets.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA40;
				nimln(1396, "sockets.nim");
				nimln(1396, "sockets.nim");
				result = ((NU8) 0);
				goto BeforeRet;
			}
			goto LA20;
			LA40: ;
			LA20: ;
			nimln(1397, "sockets.nim");
			(*line) = addChar((*line), c);
		}
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, tocint_199263)(NU8 opt) {
	int result;
	nimfr("toCInt", "sockets.nim")
	result = 0;
	nimln(762, "sockets.nim");
	nimln(762, "sockets.nim");
	switch (opt) {
	case ((NU8) 0):
	{
		result = SO_ACCEPTCONN;
	}
	break;
	case ((NU8) 1):
	{
		result = SO_BROADCAST;
	}
	break;
	case ((NU8) 2):
	{
		result = SO_DEBUG;
	}
	break;
	case ((NU8) 3):
	{
		result = SO_DONTROUTE;
	}
	break;
	case ((NU8) 4):
	{
		result = SO_KEEPALIVE;
	}
	break;
	case ((NU8) 5):
	{
		result = SO_OOBINLINE;
	}
	break;
	case ((NU8) 6):
	{
		result = SO_REUSEADDR;
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, setsockopt_199292)(tsocketimpl193807* socket, NU8 opt, NIM_BOOL value, int level) {
	int valuei;
	NI LOC1;
	nimfr("setSockOpt", "sockets.nim")
	nimln(784, "sockets.nim");
	LOC1 = 0;
	nimln(784, "sockets.nim");
	{
		if (!value) goto LA4;
		LOC1 = 1;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = 0;
	}
	LA2: ;
	valuei = ((int)chckRange(LOC1, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln(785, "sockets.nim");
	{
		int LOC9;
		int LOC10;
		NI32 LOC13;
		nimln(786, "sockets.nim");
		nimln(785, "sockets.nim");
		nimln(785, "sockets.nim");
		LOC9 = 0;
		LOC9 = tocint_199263(opt);
		LOC10 = 0;
		LOC10 = setsockopt((*socket).Fd, level, LOC9, ((void*) ((&valuei))), ((socklen_t) 4));
		if (!(LOC10 < ((NI32) 0))) goto LA11;
		nimln(787, "sockets.nim");
		nimln(787, "sockets.nim");
		LOC13 = 0;
		LOC13 = oslasterror_123041();
		raiseoserror_123009(LOC13);
	}
	LA11: ;
	popFrame();
}

N_NIMCALL(NI, checkbuffer_201007)(TY202215** readfds) {
	NI result;
	TY202215* res;
	nimfr("checkBuffer", "sockets.nim")
	result = 0;
	nimln(973, "sockets.nim");
	res = (TY202215*) newSeq((&NTI202215), 0);
	nimln(974, "sockets.nim");
	result = 0;
	{
		tsocketimpl193807* s_201047;
		TY202215* HEX3Atmp_201081;
		NI i_201084;
		NI l_201086;
		s_201047 = 0;
		HEX3Atmp_201081 = 0;
		nimln(975, "sockets.nim");
		unsureAsgnRef((void**) (&HEX3Atmp_201081), (*readfds));
		nimln(2986, "system.nim");
		i_201084 = 0;
		nimln(2987, "system.nim");
		nimln(2987, "system.nim");
		l_201086 = HEX3Atmp_201081->Sup.len;
		{
			nimln(2988, "system.nim");
			while (1) {
				nimln(2988, "system.nim");
				if (!(i_201084 < l_201086)) goto LA3;
				nimln(2989, "system.nim");
				if ((NU)(i_201084) >= (NU)(HEX3Atmp_201081->Sup.len)) raiseIndexError();
				s_201047 = HEX3Atmp_201081->data[i_201084];
				nimln(976, "sockets.nim");
				{
					NIM_BOOL LOC6;
					nimln(976, "sockets.nim");
					LOC6 = 0;
					LOC6 = hasdatabuffered_200939(s_201047);
					if (!LOC6) goto LA7;
					nimln(977, "sockets.nim");
					result = addInt(result, 1);
					nimln(978, "sockets.nim");
					res = (TY202215*) incrSeq(&(res)->Sup, sizeof(tsocketimpl193807*));
					asgnRefNoCycle((void**) (&res->data[res->Sup.len-1]), s_201047);
				}
				LA7: ;
				nimln(2990, "system.nim");
				i_201084 = addInt(i_201084, 1);
				nimln(2991, "system.nim");
				{
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					nimln(2991, "system.nim");
					if (!!((HEX3Atmp_201081->Sup.len == l_201086))) goto LA11;
					nimln(2991, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP838));
				}
				LA11: ;
			} LA3: ;
		}
	}
	nimln(979, "sockets.nim");
	{
		nimln(979, "sockets.nim");
		if (!(0 < result)) goto LA15;
		nimln(980, "sockets.nim");
		genericSeqAssign((&(*readfds)), res, (&NTI202215));
	}
	LA15: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, select_201301)(TY202215** readfds, NI timeout) {
	NI result;
	NI buffersfilled;
	struct timeval tv;
	fd_set rd;
	NI m;
	nimfr("select", "sockets.nim")
	result = 0;
	nimln(1058, "sockets.nim");
	buffersfilled = checkbuffer_201007(readfds);
	nimln(1059, "sockets.nim");
	{
		nimln(1059, "sockets.nim");
		if (!(0 < buffersfilled)) goto LA3;
		nimln(1060, "sockets.nim");
		nimln(1060, "sockets.nim");
		result = buffersfilled;
		goto BeforeRet;
	}
	LA3: ;
	nimln(1061, "sockets.nim");
	tv = timevalfrommilliseconds_200601(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(1064, "sockets.nim");
	m = 0;
	nimln(1065, "sockets.nim");
	createfdset_200616((&rd), (*readfds), (&m));
	nimln(1067, "sockets.nim");
	{
		NI TMP866;
		int LOC9;
		nimln(1067, "sockets.nim");
		nimln(1067, "sockets.nim");
		if (!!((timeout == -1))) goto LA7;
		nimln(1068, "sockets.nim");
		nimln(1068, "sockets.nim");
		nimln(1068, "sockets.nim");
		TMP866 = addInt(m, 1);
		LOC9 = 0;
		LOC9 = select(((int)chckRange((NI64)(TMP866), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (LOC9));
	}
	goto LA5;
	LA7: ;
	{
		NI TMP867;
		int LOC11;
		nimln(1070, "sockets.nim");
		nimln(1070, "sockets.nim");
		nimln(1070, "sockets.nim");
		TMP867 = addInt(m, 1);
		LOC11 = 0;
		LOC11 = select(((int)chckRange((NI64)(TMP867), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (LOC11));
	}
	LA5: ;
	nimln(1072, "sockets.nim");
	prunesocketset_200856(readfds, (&rd));
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, accept_197601)(tsocketimpl193807* server, tsocketimpl193807** client) {
	NimStringDesc* addrdummy;
	nimfr("accept", "sockets.nim")
	nimln(629, "sockets.nim");
	addrdummy = copyString(((NimStringDesc*) &TMP826));
	nimln(630, "sockets.nim");
	acceptaddr_196448(server, client, (&addrdummy));
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, send_204007)(tsocketimpl193807* socket, NimStringDesc* data) {
	NI sent;
	nimfr("send", "sockets.nim")
	nimln(1583, "sockets.nim");
	{
		valueerror3249* e_204013;
		NimStringDesc* LOC5;
		if (!(*socket).Nonblocking) goto LA3;
		e_204013 = 0;
		nimln(2149, "system.nim");
		e_204013 = (valueerror3249*) newObj((&NTI21801), sizeof(valueerror3249));
		(*e_204013).Sup.Sup.m_type = (&NTI3249);
		nimln(2150, "system.nim");
		LOC5 = 0;
		LOC5 = (*e_204013).Sup.message; (*e_204013).Sup.message = copyStringRC1(((NimStringDesc*) &TMP878));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(1584, "sockets.nim");
		raiseException((Exception*)e_204013, "ValueError");
	}
	LA3: ;
	nimln(1585, "sockets.nim");
	nimln(1585, "sockets.nim");
	sent = send_203664(socket, ((void*) (data->data)), data->Sup.len);
	nimln(1586, "sockets.nim");
	{
		NI32 LOC10;
		nimln(1586, "sockets.nim");
		if (!(sent < 0)) goto LA8;
		nimln(1591, "sockets.nim");
		nimln(1591, "sockets.nim");
		LOC10 = 0;
		LOC10 = oslasterror_123041();
		raiseoserror_123009(LOC10);
	}
	LA8: ;
	nimln(1593, "sockets.nim");
	{
		oserror3233* e_204203;
		NimStringDesc* LOC15;
		nimln(1593, "sockets.nim");
		nimln(1593, "sockets.nim");
		nimln(1593, "sockets.nim");
		if (!!((sent == data->Sup.len))) goto LA13;
		e_204203 = 0;
		nimln(2149, "system.nim");
		e_204203 = (oserror3233*) newObj((&NTI148404), sizeof(oserror3233));
		(*e_204203).Sup.Sup.Sup.m_type = (&NTI3233);
		nimln(2150, "system.nim");
		LOC15 = 0;
		LOC15 = (*e_204203).Sup.Sup.message; (*e_204203).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP879));
		if (LOC15) nimGCunrefNoCycle(LOC15);
		nimln(1594, "sockets.nim");
		raiseException((Exception*)e_204203, "OSError");
	}
	LA13: ;
	popFrame();
}

N_NIMCALL(NI, recvasync_202324)(tsocketimpl193807* socket, NimStringDesc** data, NI size) {
	NI result;
	nimfr("recvAsync", "sockets.nim")
	result = 0;
	nimln(1216, "sockets.nim");
	(*data) = setLengthStr((*data), size);
	nimln(1217, "sockets.nim");
	result = recv_201502(socket, ((void*) ((*data)->data)), size);
	nimln(1218, "sockets.nim");
	{
		nimln(1218, "sockets.nim");
		if (!(result < 0)) goto LA3;
		nimln(1219, "sockets.nim");
		(*data) = setLengthStr((*data), 0);
		nimln(1220, "sockets.nim");
		raisesocketerror_195201(socket, -1, NIM_TRUE);
		nimln(1221, "sockets.nim");
		result = -1;
	}
	LA3: ;
	nimln(1222, "sockets.nim");
	(*data) = setLengthStr((*data), result);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_socketsInit)(void) {
	nimfr("sockets", "sockets.nim")
	nimln(162, "sockets.nim");
	osinvalidsocket_194004 = ((int) -1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_socketsDatInit)(void) {
static TNimNode* TMP796[3];
static TNimNode* TMP797[3];
static TNimNode* TMP803[6];
NI TMP805;
static char* NIM_CONST TMP804[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TMP786[16];
NTI193807.size = sizeof(tsocketimpl193807);
NTI193807.kind = 18;
NTI193807.base = 0;
NTI193807.flags = 3;
TMP796[0] = &TMP786[1];
TMP786[1].kind = 1;
TMP786[1].offset = offsetof(tsocketimpl193807, Fd);
TMP786[1].typ = (&NTI5611);
TMP786[1].name = "fd";
TMP796[1] = &TMP786[2];
TMP786[2].kind = 3;
TMP786[2].offset = offsetof(tsocketimpl193807, Isbuffered);
TMP786[2].typ = (&NTI138);
TMP786[2].name = "isBuffered";
TMP786[2].sons = &NimDT_193807_isbuffered[0];
TMP786[2].len = 2;
TMP797[0] = &TMP786[4];
TMP786[4].kind = 1;
TMP786[4].offset = offsetof(tsocketimpl193807, isbufferedU.S1.Buffer);
TMP786[4].typ = (&NTI175208);
TMP786[4].name = "buffer";
TMP797[1] = &TMP786[5];
TMP786[5].kind = 1;
TMP786[5].offset = offsetof(tsocketimpl193807, isbufferedU.S1.Currpos);
TMP786[5].typ = (&NTI108);
TMP786[5].name = "currPos";
TMP797[2] = &TMP786[6];
TMP786[6].kind = 1;
TMP786[6].offset = offsetof(tsocketimpl193807, isbufferedU.S1.Buflen);
TMP786[6].typ = (&NTI108);
TMP786[6].name = "bufLen";
TMP786[3].len = 3; TMP786[3].kind = 2; TMP786[3].sons = &TMP797[0];
NimDT_193807_isbuffered[1] = &TMP786[3];
TMP786[7].len = 0; TMP786[7].kind = 2;
NimDT_193807_isbuffered[0] = &TMP786[7];
TMP796[2] = &TMP786[8];
TMP786[8].kind = 1;
TMP786[8].offset = offsetof(tsocketimpl193807, Nonblocking);
TMP786[8].typ = (&NTI138);
TMP786[8].name = "nonblocking";
TMP786[0].len = 3; TMP786[0].kind = 2; TMP786[0].sons = &TMP796[0];
NTI193807.node = &TMP786[0];
NTI193809.size = sizeof(tsocketimpl193807*);
NTI193809.kind = 22;
NTI193809.base = (&NTI193807);
NTI193809.flags = 2;
NTI193809.marker = TMP798;
NTI193817.size = sizeof(NU8);
NTI193817.kind = 14;
NTI193817.base = 0;
NTI193817.flags = 3;
for (TMP805 = 0; TMP805 < 6; TMP805++) {
TMP786[TMP805+9].kind = 1;
TMP786[TMP805+9].offset = TMP805;
TMP786[TMP805+9].name = TMP804[TMP805];
TMP803[TMP805] = &TMP786[TMP805+9];
}
TMP786[9].offset = 6;
TMP786[10].offset = 17;
TMP786[11].offset = 18;
TMP786[12].offset = 19;
TMP786[13].offset = 20;
TMP786[14].offset = 21;
TMP786[15].len = 6; TMP786[15].kind = 2; TMP786[15].sons = &TMP803[0];
NTI193817.node = &TMP786[15];
NTI193817.flags = 1<<2;
}

