/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_re.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_re.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct regexerror189015 regexerror189015;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct tpcre187621 tpcre187621;
typedef struct regexdesc189011 regexdesc189011;
typedef struct textra187632 textra187632;
typedef struct rtarray189213 rtarray189213;
typedef struct TY189219 TY189219;
typedef struct TY189344 TY189344;
typedef struct TY13406 TY13406;
typedef struct TY190420 TY190420;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  regexerror189015  {
  valueerror3249 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
typedef N_CDECL_PTR(tpcre187621*, TY187673) (NCSTRING a2, int a3, NCSTRING* a4, NI32* a5, NIM_CHAR* a6);
typedef N_CDECL_PTR(void, TY187771) (NCSTRING a2);
struct  regexdesc189011  {
tpcre187621* H;
textra187632* E;
};
typedef N_CDECL_PTR(textra187632*, TY187861) (tpcre187621* a2, int a3, NCSTRING* a4);
typedef int TY189223[10];
struct  rtarray189213  {
NI L;
TY189219* Spart;
TY189223 Apart;
};
typedef N_CDECL_PTR(int, TY187755) (tpcre187621* a2, textra187632* a3, NCSTRING a4, int a5, int a6, int a7, NI32* a8, int a9);
struct TY189344 {
NI Field0;
NI Field1;
};
typedef NimStringDesc* TY190117[20];
struct TY190420 {
regexdesc189011* Field0;
NimStringDesc* Field1;
};
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tpcre187621  {
char dummy;
};
struct  textra187632  {
NI Flags;
void* Studydata;
NI Matchlimit;
void* Calloutdata;
NCSTRING Tables;
NI Matchlimitrecursion;
NCSTRING* Mark;
void* Executablejit;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY189219 {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
struct TY13406 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, raiseinvalidregex_189034)(NimStringDesc* msg);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP688)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(tpcre187621*, rawcompile_189062)(NimStringDesc* pattern, int flags);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NI count, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, finalizeregex_189096)(regexdesc189011* x);
N_NIMCALL(regexdesc189011*, re_189118)(NimStringDesc* s, NU8 flags);
N_NIMCALL(void, TMP698)(void* p, NI op);
N_NIMCALL(void, initrtarray_189206)(NI len_189210, rtarray189213* Result);
N_NIMCALL(int*, getrawdata_189256)(rtarray189213* x_189264);
N_NIMCALL(int, matchorfind_189195)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, int start, int flags);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TY189344, findbounds_189336)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start);
N_NIMCALL(TY189344, findbounds_189435)(NimStringDesc* s, regexdesc189011* pattern, TY189344* matches, NI matchesLen0, NI start);
N_NIMCALL(TY189344, findbounds_189539)(NimStringDesc* s, regexdesc189011* pattern, NI start);
N_NIMCALL(int, matchorfind_189591)(NimStringDesc* s, regexdesc189011* pattern, int start, int flags);
N_NIMCALL(NIM_BOOL, match_189634)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start);
N_NIMCALL(NIM_BOOL, match_189649)(NimStringDesc* s, regexdesc189011* pattern, NI start);
N_NIMCALL(NI, matchlen_189661)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start);
N_NIMCALL(NI, matchlen_189676)(NimStringDesc* s, regexdesc189011* pattern, NI start);
N_NIMCALL(NI, find_189688)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start);
N_NIMCALL(NI, find_189780)(NimStringDesc* s, regexdesc189011* pattern, NI start);
N_NIMCALL(TY13406*, findall_189880)(NimStringDesc* s, regexdesc189011* pattern, NI start);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NIM_BOOL, contains_190014)(NimStringDesc* s, regexdesc189011* pattern, NI start);
N_NIMCALL(NIM_BOOL, contains_190026)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start);
N_NIMCALL(NIM_BOOL, startswith_190041)(NimStringDesc* s, regexdesc189011* prefix);
N_NIMCALL(NIM_BOOL, endswith_190052)(NimStringDesc* s, regexdesc189011* suffix);
N_NIMCALL(NimStringDesc*, replace_190089)(NimStringDesc* s, regexdesc189011* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NimStringDesc*, replacef_190111)(NimStringDesc* s, regexdesc189011* sub, NimStringDesc* by);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, parallelreplace_190416)(NimStringDesc* s, TY190420* subs, NI subsLen0);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(void, transformfile_190502)(NimStringDesc* infile, NimStringDesc* outfile, TY190420* subs, NI subsLen0);
N_NIMCALL(NimStringDesc*, readfile_13042)(NimStringDesc* filename);
N_NIMCALL(void, writefile_13045)(NimStringDesc* filename, NimStringDesc* content);
N_NIMCALL(TY13406*, split_190576)(NimStringDesc* s, regexdesc189011* sep);
N_NIMCALL(NimStringDesc*, escapere_190652)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
STRING_LITERAL(TMP694, "\012", 1);
STRING_LITERAL(TMP695, "^\012", 2);
NIM_CONST TY189344 TMP716 = {-1,
0}
;
STRING_LITERAL(TMP755, "", 0);
STRING_LITERAL(TMP758, "result != nil ", 14);
STRING_LITERAL(TMP759, "s != nil ", 9);
STRING_LITERAL(TMP779, "\\x", 2);
STRING_LITERAL(TMP783, "len(a) == L string modified while iterating over it", 51);
extern TNimType NTI3249; /* ValueError */
TNimType NTI189015; /* RegexError */
TNimType NTI189037; /* ref RegexError */
extern TFrame* frameptr_16442;
extern tgcheap47416 gch_47444;
extern TY187673 Dl_187672;
extern TY187771 Dl_187770;
TNimType NTI189011; /* RegexDesc */
extern TNimType NTI187912; /* ptr TPcre */
extern TNimType NTI189022; /* ptr TExtra */
TNimType NTI189013; /* Regex */
extern TY187861 Dl_187860;
extern TY187755 Dl_187754;
extern TNimType NTI13406; /* seq[string] */
extern TNimType NTI149; /* string */
TNimType NTI190117; /* array[0..19, string] */
N_NIMCALL(void, TMP688)(void* p, NI op) {
	regexerror189015* a;
	a = (regexerror189015*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, raiseinvalidregex_189034)(NimStringDesc* msg) {
	regexerror189015* e;
	NimStringDesc* LOC1;
	nimfr("raiseInvalidRegex", "re.nim")
	e = 0;
	nimln(53, "re.nim");
	e = (regexerror189015*) newObj((&NTI189037), sizeof(regexerror189015));
	(*e).Sup.Sup.Sup.m_type = (&NTI189015);
	nimln(54, "re.nim");
	LOC1 = 0;
	LOC1 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(55, "re.nim");
	raiseException((Exception*)e, "RegexError");
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(tpcre187621*, rawcompile_189062)(NimStringDesc* pattern, int flags) {
	tpcre187621* result;
	NCSTRING msg;
	int offset;
	nimfr("rawCompile", "re.nim")
	result = 0;
	msg = 0;
	offset = 0;
	nimln(61, "re.nim");
	result = Dl_187672(pattern->data, flags, (&msg), (&offset), NIM_NIL);
	nimln(62, "re.nim");
	{
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		nimln(62, "re.nim");
		if (!(result == NIM_NIL)) goto LA3;
		nimln(63, "re.nim");
		nimln(63, "re.nim");
		LOC5 = 0;
		nimln(63, "re.nim");
		LOC6 = 0;
		LOC6 = cstrToNimstr(msg);
		nimln(63, "re.nim");
		LOC7 = 0;
		LOC7 = nsuRepeatChar(((NI) (offset)), 32);
		LOC5 = rawNewString(LOC6->Sup.len + pattern->Sup.len + LOC7->Sup.len + 4);
appendString(LOC5, LOC6);
appendString(LOC5, ((NimStringDesc*) &TMP694));
appendString(LOC5, pattern);
appendString(LOC5, ((NimStringDesc*) &TMP694));
appendString(LOC5, LOC7);
appendString(LOC5, ((NimStringDesc*) &TMP695));
		raiseinvalidregex_189034(LOC5);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, finalizeregex_189096)(regexdesc189011* x) {
	nimfr("finalizeRegEx", "re.nim")
	nimln(69, "re.nim");
	Dl_187770(((NCSTRING) ((*x).H)));
	nimln(70, "re.nim");
	{
		nimln(70, "re.nim");
		nimln(70, "re.nim");
		if (!!((*x).E == 0)) goto LA3;
		nimln(71, "re.nim");
		Dl_187770(((NCSTRING) ((*x).E)));
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP698)(void* p, NI op) {
	regexdesc189011* a;
	a = (regexdesc189011*)p;
}

N_NIMCALL(regexdesc189011*, re_189118)(NimStringDesc* s, NU8 flags) {
	regexdesc189011* result;
	nimfr("re", "re.nim")
	result = 0;
	nimln(77, "re.nim");
	result = (regexdesc189011*) newObj((&NTI189013), sizeof(regexdesc189011));
	nimln(78, "re.nim");
	nimln(78, "re.nim");
	(*result).H = rawcompile_189062(s, ((int) ((flags & ~ 16))));
	nimln(79, "re.nim");
	{
		NCSTRING msg;
		nimln(79, "re.nim");
		if (!((flags &(1<<((((NU8) 4))&7)))!=0)) goto LA3;
		msg = 0;
		nimln(81, "re.nim");
		(*result).E = Dl_187860((*result).H, ((int) 0), (&msg));
		nimln(82, "re.nim");
		{
			NimStringDesc* LOC9;
			nimln(82, "re.nim");
			nimln(82, "re.nim");
			if (!!(msg == 0)) goto LA7;
			nimln(82, "re.nim");
			nimln(82, "re.nim");
			LOC9 = 0;
			LOC9 = cstrToNimstr(msg);
			raiseinvalidregex_189034(LOC9);
		}
		LA7: ;
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(int, matchorfind_189195)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, int start, int flags) {
	int result;
	rtarray189213 rtarray;
	NI TMP700;
	NI TMP701;
	int* rawmatches;
	int res;
	NI TMP702;
	NI TMP703;
	NI TMP711;
	nimfr("matchOrFind", "re.nim")
	result = 0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(87, "re.nim");
	nimln(87, "re.nim");
	nimln(87, "re.nim");
	nimln(87, "re.nim");
	TMP700 = addInt(matchesLen0, 1);
	TMP701 = mulInt((NI64)(TMP700), 3);
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(((NI)chckRange((NI64)(TMP701), 0, IL64(9223372036854775807))), (&rtarray));
	nimln(88, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(89, "re.nim");
	nimln(89, "re.nim");
	nimln(90, "re.nim");
	nimln(90, "re.nim");
	nimln(90, "re.nim");
	TMP702 = addInt(matchesLen0, 1);
	TMP703 = mulInt(((int)chckRange((NI64)(TMP702), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TMP703 < (-2147483647 -1) || TMP703 > 2147483647) raiseOverflow();
	res = Dl_187754((*pattern).H, (*pattern).E, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), start, flags, ((NI32*) (rawmatches)), (NI32)(TMP703));
	nimln(91, "re.nim");
	{
		nimln(91, "re.nim");
		if (!(res < ((NI32) 0))) goto LA3;
		nimln(91, "re.nim");
		nimln(91, "re.nim");
		result = res;
		goto BeforeRet;
	}
	LA3: ;
	{
		NI i_189308;
		NI HEX3Atmp_189316;
		NI TMP704;
		NI res_189319;
		i_189308 = 0;
		HEX3Atmp_189316 = 0;
		nimln(92, "re.nim");
		nimln(92, "re.nim");
		TMP704 = subInt(((NI) (res)), 1);
		HEX3Atmp_189316 = (NI64)(TMP704);
		nimln(1576, "system.nim");
		res_189319 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				int a;
				NI TMP705;
				int b;
				NI TMP706;
				NI TMP707;
				nimln(1577, "system.nim");
				if (!(res_189319 <= HEX3Atmp_189316)) goto LA7;
				nimln(1576, "system.nim");
				i_189308 = res_189319;
				nimln(93, "re.nim");
				nimln(93, "re.nim");
				TMP705 = mulInt(i_189308, 2);
				a = rawmatches[((NI64)(TMP705))- 0];
				nimln(94, "re.nim");
				nimln(94, "re.nim");
				nimln(94, "re.nim");
				TMP706 = mulInt(i_189308, 2);
				TMP707 = addInt((NI64)(TMP706), 1);
				b = rawmatches[((NI64)(TMP707))- 0];
				nimln(95, "re.nim");
				{
					NI TMP708;
					NI TMP709;
					nimln(95, "re.nim");
					if (!(((NI32) 0) <= a)) goto LA10;
					nimln(95, "re.nim");
					nimln(95, "re.nim");
					TMP708 = subInt(i_189308, 1);
					if ((NU)((NI64)(TMP708)) >= (NU)(matchesLen0)) raiseIndexError();
					nimln(95, "re.nim");
					nimln(95, "re.nim");
					TMP709 = subInt(((NI) (b)), 1);
					unsureAsgnRef((void**) (&matches[(NI64)(TMP708)]), copyStrLast(s, ((NI) (a)), (NI64)(TMP709)));
				}
				goto LA8;
				LA10: ;
				{
					NI TMP710;
					nimln(96, "re.nim");
					nimln(96, "re.nim");
					TMP710 = subInt(i_189308, 1);
					if ((NU)((NI64)(TMP710)) >= (NU)(matchesLen0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI64)(TMP710)]), copyString(NIM_NIL));
				}
				LA8: ;
				nimln(1579, "system.nim");
				res_189319 = addInt(res_189319, 1);
			} LA7: ;
		}
	}
	nimln(97, "re.nim");
	nimln(97, "re.nim");
	nimln(97, "re.nim");
	TMP711 = subInt(rawmatches[(1)- 0], rawmatches[(0)- 0]);
	if (TMP711 < (-2147483647 -1) || TMP711 > 2147483647) raiseOverflow();
	result = (NI32)(TMP711);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY189344, findbounds_189336)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start) {
	TY189344 result;
	rtarray189213 rtarray;
	NI TMP712;
	NI TMP713;
	int* rawmatches;
	int res;
	NI TMP714;
	NI TMP715;
	NI TMP724;
	nimfr("findBounds", "re.nim")
	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(106, "re.nim");
	nimln(106, "re.nim");
	nimln(106, "re.nim");
	nimln(106, "re.nim");
	TMP712 = addInt(matchesLen0, 1);
	TMP713 = mulInt((NI64)(TMP712), 3);
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(((NI)chckRange((NI64)(TMP713), 0, IL64(9223372036854775807))), (&rtarray));
	nimln(107, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(108, "re.nim");
	nimln(108, "re.nim");
	nimln(109, "re.nim");
	nimln(109, "re.nim");
	nimln(109, "re.nim");
	TMP714 = addInt(matchesLen0, 1);
	TMP715 = mulInt(((int)chckRange((NI64)(TMP714), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TMP715 < (-2147483647 -1) || TMP715 > 2147483647) raiseOverflow();
	res = Dl_187754((*pattern).H, (*pattern).E, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((NI32*) (rawmatches)), (NI32)(TMP715));
	nimln(110, "re.nim");
	{
		nimln(110, "re.nim");
		if (!(res < ((NI32) 0))) goto LA3;
		nimln(110, "re.nim");
		nimln(110, "re.nim");
		result = TMP716;
		goto BeforeRet;
	}
	LA3: ;
	{
		NI i_189404;
		NI HEX3Atmp_189413;
		NI TMP717;
		NI res_189416;
		i_189404 = 0;
		HEX3Atmp_189413 = 0;
		nimln(111, "re.nim");
		nimln(111, "re.nim");
		TMP717 = subInt(((NI) (res)), 1);
		HEX3Atmp_189413 = (NI64)(TMP717);
		nimln(1576, "system.nim");
		res_189416 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				int a;
				NI TMP718;
				int b;
				NI TMP719;
				NI TMP720;
				nimln(1577, "system.nim");
				if (!(res_189416 <= HEX3Atmp_189413)) goto LA7;
				nimln(1576, "system.nim");
				i_189404 = res_189416;
				nimln(112, "re.nim");
				nimln(112, "re.nim");
				TMP718 = mulInt(i_189404, 2);
				a = rawmatches[((NI64)(TMP718))- 0];
				nimln(113, "re.nim");
				nimln(113, "re.nim");
				nimln(113, "re.nim");
				TMP719 = mulInt(i_189404, 2);
				TMP720 = addInt((NI64)(TMP719), 1);
				b = rawmatches[((NI64)(TMP720))- 0];
				nimln(114, "re.nim");
				{
					NI TMP721;
					NI TMP722;
					nimln(114, "re.nim");
					if (!(((NI32) 0) <= a)) goto LA10;
					nimln(114, "re.nim");
					nimln(114, "re.nim");
					TMP721 = subInt(i_189404, 1);
					if ((NU)((NI64)(TMP721)) >= (NU)(matchesLen0)) raiseIndexError();
					nimln(114, "re.nim");
					nimln(114, "re.nim");
					TMP722 = subInt(((NI) (b)), 1);
					unsureAsgnRef((void**) (&matches[(NI64)(TMP721)]), copyStrLast(s, ((NI) (a)), (NI64)(TMP722)));
				}
				goto LA8;
				LA10: ;
				{
					NI TMP723;
					nimln(115, "re.nim");
					nimln(115, "re.nim");
					TMP723 = subInt(i_189404, 1);
					if ((NU)((NI64)(TMP723)) >= (NU)(matchesLen0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI64)(TMP723)]), copyString(NIM_NIL));
				}
				LA8: ;
				nimln(1579, "system.nim");
				res_189416 = addInt(res_189416, 1);
			} LA7: ;
		}
	}
	nimln(116, "re.nim");
	nimln(116, "re.nim");
	result.Field0 = ((NI) (rawmatches[(0)- 0]));
	nimln(116, "re.nim");
	TMP724 = subInt(((NI) (rawmatches[(1)- 0])), 1);
	result.Field1 = (NI64)(TMP724);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY189344, findbounds_189435)(NimStringDesc* s, regexdesc189011* pattern, TY189344* matches, NI matchesLen0, NI start) {
	TY189344 result;
	rtarray189213 rtarray;
	NI TMP725;
	NI TMP726;
	int* rawmatches;
	int res;
	NI TMP727;
	NI TMP728;
	NI TMP736;
	nimfr("findBounds", "re.nim")
	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(126, "re.nim");
	nimln(126, "re.nim");
	nimln(126, "re.nim");
	nimln(126, "re.nim");
	TMP725 = addInt(matchesLen0, 1);
	TMP726 = mulInt((NI64)(TMP725), 3);
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(((NI)chckRange((NI64)(TMP726), 0, IL64(9223372036854775807))), (&rtarray));
	nimln(127, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(128, "re.nim");
	nimln(128, "re.nim");
	nimln(129, "re.nim");
	nimln(129, "re.nim");
	nimln(129, "re.nim");
	TMP727 = addInt(matchesLen0, 1);
	TMP728 = mulInt(((int)chckRange((NI64)(TMP727), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TMP728 < (-2147483647 -1) || TMP728 > 2147483647) raiseOverflow();
	res = Dl_187754((*pattern).H, (*pattern).E, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((NI32*) (rawmatches)), (NI32)(TMP728));
	nimln(130, "re.nim");
	{
		nimln(130, "re.nim");
		if (!(res < ((NI32) 0))) goto LA3;
		nimln(130, "re.nim");
		nimln(130, "re.nim");
		result = TMP716;
		goto BeforeRet;
	}
	LA3: ;
	{
		NI i_189506;
		NI HEX3Atmp_189517;
		NI TMP729;
		NI res_189520;
		i_189506 = 0;
		HEX3Atmp_189517 = 0;
		nimln(131, "re.nim");
		nimln(131, "re.nim");
		TMP729 = subInt(((NI) (res)), 1);
		HEX3Atmp_189517 = (NI64)(TMP729);
		nimln(1576, "system.nim");
		res_189520 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				int a;
				NI TMP730;
				int b;
				NI TMP731;
				NI TMP732;
				nimln(1577, "system.nim");
				if (!(res_189520 <= HEX3Atmp_189517)) goto LA7;
				nimln(1576, "system.nim");
				i_189506 = res_189520;
				nimln(132, "re.nim");
				nimln(132, "re.nim");
				TMP730 = mulInt(i_189506, 2);
				a = rawmatches[((NI64)(TMP730))- 0];
				nimln(133, "re.nim");
				nimln(133, "re.nim");
				nimln(133, "re.nim");
				TMP731 = mulInt(i_189506, 2);
				TMP732 = addInt((NI64)(TMP731), 1);
				b = rawmatches[((NI64)(TMP732))- 0];
				nimln(134, "re.nim");
				{
					NI TMP733;
					NI TMP734;
					nimln(134, "re.nim");
					if (!(((NI32) 0) <= a)) goto LA10;
					nimln(134, "re.nim");
					nimln(134, "re.nim");
					TMP733 = subInt(i_189506, 1);
					if ((NU)((NI64)(TMP733)) >= (NU)(matchesLen0)) raiseIndexError();
					matches[(NI64)(TMP733)].Field0 = ((NI) (a));
					nimln(134, "re.nim");
					TMP734 = subInt(((NI) (b)), 1);
					matches[(NI64)(TMP733)].Field1 = (NI64)(TMP734);
				}
				goto LA8;
				LA10: ;
				{
					NI TMP735;
					nimln(135, "re.nim");
					nimln(135, "re.nim");
					TMP735 = subInt(i_189506, 1);
					if ((NU)((NI64)(TMP735)) >= (NU)(matchesLen0)) raiseIndexError();
					matches[(NI64)(TMP735)] = TMP716;
				}
				LA8: ;
				nimln(1579, "system.nim");
				res_189520 = addInt(res_189520, 1);
			} LA7: ;
		}
	}
	nimln(136, "re.nim");
	nimln(136, "re.nim");
	result.Field0 = ((NI) (rawmatches[(0)- 0]));
	nimln(136, "re.nim");
	TMP736 = subInt(((NI) (rawmatches[(1)- 0])), 1);
	result.Field1 = (NI64)(TMP736);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY189344, findbounds_189539)(NimStringDesc* s, regexdesc189011* pattern, NI start) {
	TY189344 result;
	rtarray189213 rtarray;
	int* rawmatches;
	int res;
	NI TMP737;
	nimfr("findBounds", "re.nim")
	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(143, "re.nim");
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(3, (&rtarray));
	nimln(144, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(145, "re.nim");
	nimln(145, "re.nim");
	res = Dl_187754((*pattern).H, NIM_NIL, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((NI32*) (rawmatches)), ((int) 3));
	nimln(147, "re.nim");
	{
		nimln(147, "re.nim");
		if (!(res < ((NI32) 0))) goto LA3;
		nimln(147, "re.nim");
		nimln(147, "re.nim");
		result.Field0 = ((NI) (res));
		result.Field1 = 0;
		goto BeforeRet;
	}
	LA3: ;
	nimln(148, "re.nim");
	nimln(148, "re.nim");
	result.Field0 = ((NI) (rawmatches[(0)- 0]));
	nimln(148, "re.nim");
	TMP737 = subInt(rawmatches[(1)- 0], ((NI32) 1));
	if (TMP737 < (-2147483647 -1) || TMP737 > 2147483647) raiseOverflow();
	result.Field1 = ((NI) ((NI32)(TMP737)));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, matchorfind_189591)(NimStringDesc* s, regexdesc189011* pattern, int start, int flags) {
	int result;
	rtarray189213 rtarray;
	int* rawmatches;
	nimfr("matchOrFind", "re.nim")
	result = 0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(152, "re.nim");
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(3, (&rtarray));
	nimln(153, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(154, "re.nim");
	nimln(154, "re.nim");
	result = Dl_187754((*pattern).H, (*pattern).E, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), start, flags, ((NI32*) (rawmatches)), ((int) 3));
	nimln(156, "re.nim");
	{
		NI TMP738;
		nimln(156, "re.nim");
		if (!(((NI32) 0) <= result)) goto LA3;
		nimln(157, "re.nim");
		nimln(157, "re.nim");
		TMP738 = subInt(rawmatches[(1)- 0], rawmatches[(0)- 0]);
		if (TMP738 < (-2147483647 -1) || TMP738 > 2147483647) raiseOverflow();
		result = (NI32)(TMP738);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, match_189634)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start) {
	NIM_BOOL result;
	int LOC1;
	NI TMP739;
	nimfr("match", "re.nim")
	result = 0;
	nimln(165, "re.nim");
	nimln(166, "re.nim");
	nimln(166, "re.nim");
	nimln(165, "re.nim");
	LOC1 = 0;
	LOC1 = matchorfind_189195(s, pattern, matches, matchesLen0, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	nimln(166, "re.nim");
	nimln(166, "re.nim");
	TMP739 = subInt(s->Sup.len, start);
	result = (LOC1 == ((int)chckRange((NI64)(TMP739), ((int) (-2147483647 -1)), ((int) 2147483647))));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, match_189649)(NimStringDesc* s, regexdesc189011* pattern, NI start) {
	NIM_BOOL result;
	int LOC1;
	NI TMP740;
	nimfr("match", "re.nim")
	result = 0;
	nimln(170, "re.nim");
	nimln(170, "re.nim");
	nimln(170, "re.nim");
	nimln(170, "re.nim");
	LOC1 = 0;
	LOC1 = matchorfind_189591(s, pattern, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	nimln(170, "re.nim");
	nimln(170, "re.nim");
	TMP740 = subInt(s->Sup.len, start);
	result = (LOC1 == ((int)chckRange((NI64)(TMP740), ((int) (-2147483647 -1)), ((int) 2147483647))));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, matchlen_189661)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start) {
	NI result;
	int LOC1;
	nimfr("matchLen", "re.nim")
	result = 0;
	nimln(177, "re.nim");
	nimln(177, "re.nim");
	nimln(177, "re.nim");
	LOC1 = 0;
	LOC1 = matchorfind_189195(s, pattern, matches, matchesLen0, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	result = ((NI) (LOC1));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, matchlen_189676)(NimStringDesc* s, regexdesc189011* pattern, NI start) {
	NI result;
	int LOC1;
	nimfr("matchLen", "re.nim")
	result = 0;
	nimln(183, "re.nim");
	nimln(183, "re.nim");
	nimln(183, "re.nim");
	LOC1 = 0;
	LOC1 = matchorfind_189591(s, pattern, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	result = ((NI) (LOC1));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, find_189688)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start) {
	NI result;
	rtarray189213 rtarray;
	NI TMP741;
	NI TMP742;
	int* rawmatches;
	int res;
	NI TMP743;
	NI TMP744;
	nimfr("find", "re.nim")
	result = 0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(191, "re.nim");
	nimln(191, "re.nim");
	nimln(191, "re.nim");
	nimln(191, "re.nim");
	TMP741 = addInt(matchesLen0, 1);
	TMP742 = mulInt((NI64)(TMP741), 3);
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(((NI)chckRange((NI64)(TMP742), 0, IL64(9223372036854775807))), (&rtarray));
	nimln(192, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(193, "re.nim");
	nimln(193, "re.nim");
	nimln(194, "re.nim");
	nimln(194, "re.nim");
	nimln(194, "re.nim");
	TMP743 = addInt(matchesLen0, 1);
	TMP744 = mulInt(((int)chckRange((NI64)(TMP743), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 3));
	if (TMP744 < (-2147483647 -1) || TMP744 > 2147483647) raiseOverflow();
	res = Dl_187754((*pattern).H, (*pattern).E, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((NI32*) (rawmatches)), (NI32)(TMP744));
	nimln(195, "re.nim");
	{
		nimln(195, "re.nim");
		if (!(res < ((NI32) 0))) goto LA3;
		nimln(195, "re.nim");
		nimln(195, "re.nim");
		result = ((NI) (res));
		goto BeforeRet;
	}
	LA3: ;
	{
		NI i_189752;
		NI HEX3Atmp_189760;
		NI TMP745;
		NI res_189763;
		i_189752 = 0;
		HEX3Atmp_189760 = 0;
		nimln(196, "re.nim");
		nimln(196, "re.nim");
		TMP745 = subInt(((NI) (res)), 1);
		HEX3Atmp_189760 = (NI64)(TMP745);
		nimln(1576, "system.nim");
		res_189763 = 1;
		{
			nimln(1577, "system.nim");
			while (1) {
				int a;
				NI TMP746;
				int b;
				NI TMP747;
				NI TMP748;
				nimln(1577, "system.nim");
				if (!(res_189763 <= HEX3Atmp_189760)) goto LA7;
				nimln(1576, "system.nim");
				i_189752 = res_189763;
				nimln(197, "re.nim");
				nimln(197, "re.nim");
				TMP746 = mulInt(i_189752, 2);
				a = rawmatches[((NI64)(TMP746))- 0];
				nimln(198, "re.nim");
				nimln(198, "re.nim");
				nimln(198, "re.nim");
				TMP747 = mulInt(i_189752, 2);
				TMP748 = addInt((NI64)(TMP747), 1);
				b = rawmatches[((NI64)(TMP748))- 0];
				nimln(199, "re.nim");
				{
					NI TMP749;
					NI TMP750;
					nimln(199, "re.nim");
					if (!(((NI32) 0) <= a)) goto LA10;
					nimln(199, "re.nim");
					nimln(199, "re.nim");
					TMP749 = subInt(i_189752, 1);
					if ((NU)((NI64)(TMP749)) >= (NU)(matchesLen0)) raiseIndexError();
					nimln(199, "re.nim");
					nimln(199, "re.nim");
					TMP750 = subInt(((NI) (b)), 1);
					unsureAsgnRef((void**) (&matches[(NI64)(TMP749)]), copyStrLast(s, ((NI) (a)), (NI64)(TMP750)));
				}
				goto LA8;
				LA10: ;
				{
					NI TMP751;
					nimln(200, "re.nim");
					nimln(200, "re.nim");
					TMP751 = subInt(i_189752, 1);
					if ((NU)((NI64)(TMP751)) >= (NU)(matchesLen0)) raiseIndexError();
					unsureAsgnRef((void**) (&matches[(NI64)(TMP751)]), copyString(NIM_NIL));
				}
				LA8: ;
				nimln(1579, "system.nim");
				res_189763 = addInt(res_189763, 1);
			} LA7: ;
		}
	}
	nimln(201, "re.nim");
	nimln(201, "re.nim");
	result = ((NI) (rawmatches[(0)- 0]));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, find_189780)(NimStringDesc* s, regexdesc189011* pattern, NI start) {
	NI result;
	rtarray189213 rtarray;
	int* rawmatches;
	int res;
	nimfr("find", "re.nim")
	result = 0;
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	nimln(207, "re.nim");
	chckNil((void*)(&rtarray));
	memset((void*)(&rtarray), 0, sizeof(rtarray));
	initrtarray_189206(3, (&rtarray));
	nimln(208, "re.nim");
	rawmatches = getrawdata_189256((&rtarray));
	nimln(209, "re.nim");
	nimln(209, "re.nim");
	res = Dl_187754((*pattern).H, NIM_NIL, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0), ((NI32*) (rawmatches)), ((int) 3));
	nimln(211, "re.nim");
	{
		nimln(211, "re.nim");
		if (!(res < ((NI32) 0))) goto LA3;
		nimln(211, "re.nim");
		nimln(211, "re.nim");
		result = ((NI) (res));
		goto BeforeRet;
	}
	LA3: ;
	nimln(212, "re.nim");
	nimln(212, "re.nim");
	result = ((NI) (rawmatches[(0)- 0]));
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(TY13406*, findall_189880)(NimStringDesc* s, regexdesc189011* pattern, NI start) {
	TY13406* result;
	nimfr("findAll", "re.nim")
	result = 0;
	nimln(2042, "system.nim");
	result = (TY13406*) newSeq((&NTI13406), 0);
	{
		NimStringDesc* x_189888;
		NI32 i_189930;
		rtarray189213 rtarray_189932;
		int* rawmatches_189934;
		x_189888 = 0;
		nimln(220, "re.nim");
		i_189930 = ((NI32)chckRange(start, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		memset((void*)(&rtarray_189932), 0, sizeof(rtarray_189932));
		nimln(221, "re.nim");
		chckNil((void*)(&rtarray_189932));
		memset((void*)(&rtarray_189932), 0, sizeof(rtarray_189932));
		initrtarray_189206(3, (&rtarray_189932));
		nimln(222, "re.nim");
		rawmatches_189934 = getrawdata_189256((&rtarray_189932));
		{
			nimln(223, "re.nim");
			while (1) {
				int res_189936;
				int a_189939;
				int b_189941;
				NI TMP752;
				NimStringDesc* LOC8;
				nimln(224, "re.nim");
				nimln(224, "re.nim");
				res_189936 = Dl_187754((*pattern).H, (*pattern).E, s->data, ((int)chckRange(s->Sup.len, ((int) (-2147483647 -1)), ((int) 2147483647))), i_189930, ((NI32) 0), ((NI32*) (rawmatches_189934)), ((int) 3));
				nimln(226, "re.nim");
				{
					nimln(226, "re.nim");
					if (!(res_189936 < ((NI32) 0))) goto LA6;
					nimln(226, "re.nim");
					goto LA2;
				}
				LA6: ;
				nimln(227, "re.nim");
				a_189939 = rawmatches_189934[(0)- 0];
				nimln(228, "re.nim");
				b_189941 = rawmatches_189934[(1)- 0];
				nimln(229, "re.nim");
				nimln(229, "re.nim");
				nimln(229, "re.nim");
				TMP752 = subInt(((NI) (b_189941)), 1);
				x_189888 = copyStrLast(s, ((NI) (a_189939)), (NI64)(TMP752));
				nimln(2043, "system.nim");
				result = (TY13406*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
				LOC8 = 0;
				LOC8 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(x_189888);
				if (LOC8) nimGCunrefNoCycle(LOC8);
				nimln(230, "re.nim");
				i_189930 = b_189941;
			}
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_190014)(NimStringDesc* s, regexdesc189011* pattern, NI start) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "re.nim")
	result = 0;
	nimln(267, "re.nim");
	nimln(267, "re.nim");
	nimln(267, "re.nim");
	nimln(267, "re.nim");
	LOC1 = 0;
	LOC1 = find_189780(s, pattern, start);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_190026)(NimStringDesc* s, regexdesc189011* pattern, NimStringDesc** matches, NI matchesLen0, NI start) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("contains", "re.nim")
	result = 0;
	nimln(272, "re.nim");
	nimln(272, "re.nim");
	nimln(272, "re.nim");
	nimln(272, "re.nim");
	LOC1 = 0;
	LOC1 = find_189688(s, pattern, matches, matchesLen0, start);
	result = (0 <= LOC1);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, startswith_190041)(NimStringDesc* s, regexdesc189011* prefix) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("startsWith", "re.nim")
	result = 0;
	nimln(276, "re.nim");
	nimln(276, "re.nim");
	nimln(276, "re.nim");
	LOC1 = 0;
	LOC1 = matchlen_189676(s, prefix, 0);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, endswith_190052)(NimStringDesc* s, regexdesc189011* suffix) {
	NIM_BOOL result;
	nimfr("endsWith", "re.nim")
	result = 0;
	{
		NI i_190067;
		NI HEX3Atmp_190069;
		NI TMP753;
		NI res_190072;
		i_190067 = 0;
		HEX3Atmp_190069 = 0;
		nimln(280, "re.nim");
		nimln(280, "re.nim");
		nimln(280, "re.nim");
		TMP753 = subInt(s->Sup.len, 1);
		HEX3Atmp_190069 = (NI64)(TMP753);
		nimln(1576, "system.nim");
		res_190072 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				nimln(1577, "system.nim");
				if (!(res_190072 <= HEX3Atmp_190069)) goto LA3;
				nimln(1576, "system.nim");
				i_190067 = res_190072;
				nimln(281, "re.nim");
				{
					NI LOC6;
					NI TMP754;
					nimln(281, "re.nim");
					nimln(281, "re.nim");
					LOC6 = 0;
					LOC6 = matchlen_189676(s, suffix, i_190067);
					nimln(281, "re.nim");
					nimln(281, "re.nim");
					TMP754 = subInt(s->Sup.len, i_190067);
					if (!(LOC6 == (NI64)(TMP754))) goto LA7;
					nimln(281, "re.nim");
					nimln(281, "re.nim");
					result = NIM_TRUE;
					goto BeforeRet;
				}
				LA7: ;
				nimln(1579, "system.nim");
				res_190072 = addInt(res_190072, 1);
			} LA3: ;
		}
	}
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, replace_190089)(NimStringDesc* s, regexdesc189011* sub, NimStringDesc* by) {
	NimStringDesc* result;
	NI prev;
	NimStringDesc* LOC8;
	nimfr("replace", "re.nim")
	result = 0;
	nimln(295, "re.nim");
	result = copyString(((NimStringDesc*) &TMP755));
	nimln(296, "re.nim");
	prev = 0;
	{
		nimln(297, "re.nim");
		while (1) {
			TY189344 match;
			NI TMP756;
			NimStringDesc* LOC7;
			NI TMP757;
			nimln(298, "re.nim");
			match = findbounds_189539(s, sub, prev);
			nimln(299, "re.nim");
			{
				nimln(299, "re.nim");
				if (!(match.Field0 < 0)) goto LA5;
				nimln(299, "re.nim");
				goto LA1;
			}
			LA5: ;
			nimln(300, "re.nim");
			nimln(300, "re.nim");
			nimln(300, "re.nim");
			TMP756 = subInt(match.Field0, 1);
			LOC7 = 0;
			LOC7 = copyStrLast(s, prev, (NI64)(TMP756));
			result = resizeString(result, LOC7->Sup.len + 0);
appendString(result, LOC7);
			nimln(301, "re.nim");
			result = resizeString(result, by->Sup.len + 0);
appendString(result, by);
			nimln(302, "re.nim");
			nimln(302, "re.nim");
			TMP757 = addInt(match.Field1, 1);
			prev = (NI64)(TMP757);
		}
	} LA1: ;
	nimln(303, "re.nim");
	nimln(303, "re.nim");
	LOC8 = 0;
	LOC8 = copyStr(s, prev);
	result = resizeString(result, LOC8->Sup.len + 0);
appendString(result, LOC8);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, replacef_190111)(NimStringDesc* s, regexdesc189011* sub, NimStringDesc* by) {
	NimStringDesc* result;
	TY190117 caps;
	NI prev;
	NimStringDesc* LOC16;
	nimfr("replacef", "re.nim")
	result = 0;
	nimln(317, "re.nim");
	result = copyString(((NimStringDesc*) &TMP755));
	memset((void*)caps, 0, sizeof(caps));
	nimln(319, "re.nim");
	prev = 0;
	{
		nimln(320, "re.nim");
		while (1) {
			TY189344 match;
			NI TMP760;
			NimStringDesc* LOC15;
			NI TMP777;
			nimln(321, "re.nim");
			match = findbounds_189336(s, sub, caps, 20, prev);
			nimln(322, "re.nim");
			{
				nimln(322, "re.nim");
				if (!(match.Field0 < 0)) goto LA5;
				nimln(322, "re.nim");
				goto LA1;
			}
			LA5: ;
			nimln(323, "re.nim");
			{
				nimln(323, "re.nim");
				nimln(323, "re.nim");
				nimln(323, "re.nim");
				if (!!(!((result == NIM_NIL)))) goto LA9;
				nimln(323, "re.nim");
				failedassertimpl_85425(((NimStringDesc*) &TMP758));
			}
			LA9: ;
			nimln(324, "re.nim");
			{
				nimln(324, "re.nim");
				nimln(324, "re.nim");
				nimln(324, "re.nim");
				if (!!(!((s == NIM_NIL)))) goto LA13;
				nimln(324, "re.nim");
				failedassertimpl_85425(((NimStringDesc*) &TMP759));
			}
			LA13: ;
			nimln(325, "re.nim");
			nimln(325, "re.nim");
			nimln(325, "re.nim");
			TMP760 = subInt(match.Field0, 1);
			LOC15 = 0;
			LOC15 = copyStrLast(s, prev, (NI64)(TMP760));
			result = resizeString(result, LOC15->Sup.len + 0);
appendString(result, LOC15);
			nimln(326, "re.nim");
			nsuAddf((&result), by, caps, 20);
			nimln(327, "re.nim");
			nimln(327, "re.nim");
			TMP777 = addInt(match.Field1, 1);
			prev = (NI64)(TMP777);
		}
	} LA1: ;
	nimln(328, "re.nim");
	nimln(328, "re.nim");
	LOC16 = 0;
	LOC16 = copyStr(s, prev);
	result = resizeString(result, LOC16->Sup.len + 0);
appendString(result, LOC16);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, parallelreplace_190416)(NimStringDesc* s, TY190420* subs, NI subsLen0) {
	NimStringDesc* result;
	NI i;
	TY190117 caps;
	NimStringDesc* LOC11;
	nimfr("parallelReplace", "re.nim")
	result = 0;
	nimln(334, "re.nim");
	result = copyString(((NimStringDesc*) &TMP755));
	nimln(335, "re.nim");
	i = 0;
	memset((void*)caps, 0, sizeof(caps));
	{
		nimln(337, "re.nim");
		while (1) {
			nimln(337, "re.nim");
			nimln(337, "re.nim");
			if (!(i < s->Sup.len)) goto LA2;
			{
				{
					NI j_190441;
					NI HEX3Atmp_190473;
					NI res_190476;
					j_190441 = 0;
					HEX3Atmp_190473 = 0;
					nimln(339, "re.nim");
					nimln(339, "re.nim");
					HEX3Atmp_190473 = (subsLen0-1);
					nimln(1576, "system.nim");
					res_190476 = 0;
					{
						nimln(1577, "system.nim");
						while (1) {
							NI x;
							nimln(1577, "system.nim");
							if (!(res_190476 <= HEX3Atmp_190473)) goto LA6;
							nimln(1576, "system.nim");
							j_190441 = res_190476;
							nimln(340, "re.nim");
							if ((NU)(j_190441) >= (NU)(subsLen0)) raiseIndexError();
							x = matchlen_189661(s, subs[j_190441].Field0, caps, 20, i);
							nimln(341, "re.nim");
							{
								nimln(341, "re.nim");
								if (!(0 < x)) goto LA9;
								nimln(342, "re.nim");
								if ((NU)(j_190441) >= (NU)(subsLen0)) raiseIndexError();
								nsuAddf((&result), subs[j_190441].Field1, caps, 20);
								nimln(343, "re.nim");
								i = addInt(i, x);
								nimln(344, "re.nim");
								goto LA3;
							}
							LA9: ;
							nimln(1579, "system.nim");
							res_190476 = addInt(res_190476, 1);
						} LA6: ;
					}
				}
				nimln(345, "re.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				result = addChar(result, s->data[i]);
				nimln(346, "re.nim");
				i = addInt(i, 1);
			} LA3: ;
		} LA2: ;
	}
	nimln(348, "re.nim");
	nimln(348, "re.nim");
	LOC11 = 0;
	LOC11 = copyStr(s, i);
	result = resizeString(result, LOC11->Sup.len + 0);
appendString(result, LOC11);
	popFrame();
	return result;
}

N_NIMCALL(void, transformfile_190502)(NimStringDesc* infile, NimStringDesc* outfile, TY190420* subs, NI subsLen0) {
	NimStringDesc* x;
	NimStringDesc* LOC1;
	nimfr("transformFile", "re.nim")
	nimln(355, "re.nim");
	nimln(355, "re.nim");
	x = readfile_13042(infile);
	nimln(356, "re.nim");
	nimln(356, "re.nim");
	LOC1 = 0;
	LOC1 = parallelreplace_190416(x, subs, subsLen0);
	writefile_13045(outfile, LOC1);
	popFrame();
}

N_NIMCALL(TY13406*, split_190576)(NimStringDesc* s, regexdesc189011* sep) {
	TY13406* result;
	nimfr("split", "re.nim")
	result = 0;
	nimln(2042, "system.nim");
	result = (TY13406*) newSeq((&NTI13406), 0);
	{
		NimStringDesc* x_190583;
		NI first_190626;
		NI last_190628;
		x_190583 = 0;
		nimln(377, "re.nim");
		first_190626 = 0;
		nimln(378, "re.nim");
		last_190628 = 0;
		{
			nimln(379, "re.nim");
			while (1) {
				NI x_190630;
				nimln(379, "re.nim");
				nimln(379, "re.nim");
				if (!(last_190628 < s->Sup.len)) goto LA3;
				nimln(380, "re.nim");
				x_190630 = matchlen_189676(s, sep, last_190628);
				nimln(381, "re.nim");
				{
					nimln(381, "re.nim");
					if (!(0 < x_190630)) goto LA6;
					nimln(381, "re.nim");
					last_190628 = addInt(last_190628, x_190630);
				}
				LA6: ;
				nimln(382, "re.nim");
				first_190626 = last_190628;
				{
					nimln(383, "re.nim");
					while (1) {
						nimln(383, "re.nim");
						nimln(383, "re.nim");
						if (!(last_190628 < s->Sup.len)) goto LA9;
						nimln(384, "re.nim");
						last_190628 = addInt(last_190628, 1);
						nimln(385, "re.nim");
						x_190630 = matchlen_189676(s, sep, last_190628);
						nimln(386, "re.nim");
						{
							nimln(386, "re.nim");
							if (!(0 < x_190630)) goto LA12;
							nimln(386, "re.nim");
							goto LA8;
						}
						LA12: ;
					} LA9: ;
				} LA8: ;
				nimln(387, "re.nim");
				{
					NI TMP778;
					NimStringDesc* LOC18;
					nimln(387, "re.nim");
					if (!(first_190626 < last_190628)) goto LA16;
					nimln(388, "re.nim");
					nimln(388, "re.nim");
					nimln(388, "re.nim");
					TMP778 = subInt(last_190628, 1);
					x_190583 = copyStrLast(s, first_190626, (NI64)(TMP778));
					nimln(2043, "system.nim");
					result = (TY13406*) incrSeq(&(result)->Sup, sizeof(NimStringDesc*));
					LOC18 = 0;
					LOC18 = result->data[result->Sup.len-1]; result->data[result->Sup.len-1] = copyStringRC1(x_190583);
					if (LOC18) nimGCunrefNoCycle(LOC18);
				}
				LA16: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, escapere_190652)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("escapeRe", "re.nim")
	result = 0;
	nimln(397, "re.nim");
	result = copyString(((NimStringDesc*) &TMP755));
	{
		NIM_CHAR c_190656;
		NI i_190668;
		NI l_190670;
		c_190656 = 0;
		nimln(2995, "system.nim");
		i_190668 = 0;
		nimln(2996, "system.nim");
		nimln(2996, "system.nim");
		l_190670 = s->Sup.len;
		{
			nimln(2997, "system.nim");
			while (1) {
				nimln(2997, "system.nim");
				if (!(i_190668 < l_190670)) goto LA3;
				nimln(2998, "system.nim");
				if ((NU)(i_190668) > (NU)(s->Sup.len)) raiseIndexError();
				c_190656 = s->data[i_190668];
				nimln(399, "re.nim");
				switch (((NU8)(c_190656))) {
				case 97 ... 122:
				case 65 ... 90:
				case 48 ... 57:
				case 95:
				{
					nimln(401, "re.nim");
					result = addChar(result, c_190656);
				}
				break;
				default:
				{
					NimStringDesc* LOC6;
					nimln(403, "re.nim");
					result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP779));
					nimln(404, "re.nim");
					nimln(404, "re.nim");
					nimln(404, "re.nim");
					LOC6 = 0;
					LOC6 = nsuToHex(((NI64) (((NU8)(c_190656)))), 2);
					result = resizeString(result, LOC6->Sup.len + 0);
appendString(result, LOC6);
				}
				break;
				}
				nimln(2999, "system.nim");
				i_190668 = addInt(i_190668, 1);
				nimln(3000, "system.nim");
				{
					nimln(3000, "system.nim");
					nimln(3000, "system.nim");
					nimln(3000, "system.nim");
					if (!!((s->Sup.len == l_190670))) goto LA9;
					nimln(3000, "system.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP783));
				}
				LA9: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit)(void) {
	nimfr("re", "re.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit)(void) {
static TNimNode* TMP696[2];
static TNimNode TMP682[4];
NTI189015.size = sizeof(regexerror189015);
NTI189015.kind = 17;
NTI189015.base = (&NTI3249);
TMP682[0].len = 0; TMP682[0].kind = 2;
NTI189015.node = &TMP682[0];
NTI189037.size = sizeof(regexerror189015*);
NTI189037.kind = 22;
NTI189037.base = (&NTI189015);
NTI189037.marker = TMP688;
NTI189011.size = sizeof(regexdesc189011);
NTI189011.kind = 18;
NTI189011.base = 0;
NTI189011.flags = 3;
TMP696[0] = &TMP682[2];
TMP682[2].kind = 1;
TMP682[2].offset = offsetof(regexdesc189011, H);
TMP682[2].typ = (&NTI187912);
TMP682[2].name = "h";
TMP696[1] = &TMP682[3];
TMP682[3].kind = 1;
TMP682[3].offset = offsetof(regexdesc189011, E);
TMP682[3].typ = (&NTI189022);
TMP682[3].name = "e";
TMP682[1].len = 2; TMP682[1].kind = 2; TMP682[1].sons = &TMP696[0];
NTI189011.node = &TMP682[1];
NTI189013.size = sizeof(regexdesc189011*);
NTI189013.kind = 22;
NTI189013.base = (&NTI189011);
NTI189013.flags = 2;
NTI189013.marker = TMP698;
(&NTI189013)->finalizer = (void*)finalizeregex_189096;
NTI190117.size = sizeof(TY190117);
NTI190117.kind = 16;
NTI190117.base = (&NTI149);
NTI190117.flags = 2;
}

