/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_strtabs.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_strtabs.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct stringtableobj173012 stringtableobj173012;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct keyvaluepairseq173010 keyvaluepairseq173010;
typedef struct TY109352 TY109352;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct keyerror3251 keyerror3251;
typedef struct valueerror3249 valueerror3249;
typedef struct Exception Exception;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY109352 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  stringtableobj173012  {
  TNimObject Sup;
NI Counter;
keyvaluepairseq173010* Data;
NU8 Mode;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  valueerror3249  {
  Exception Sup;
};
struct  keyerror3251  {
  valueerror3249 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
typedef NU8 TY76268[32];
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct keyvaluepairseq173010 {
  TGenericSeq Sup;
  TY109352 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, nstlen)(stringtableobj173012* t);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, myhash_173171)(stringtableobj173012* t, NimStringDesc* key);
N_NIMCALL(NI, hash_137842)(NimStringDesc* x);
N_NIMCALL(NI, hashignorecase_137980)(NimStringDesc* x);
N_NIMCALL(NI, hashignorestyle_137888)(NimStringDesc* x);
N_NIMCALL(NIM_BOOL, mycmp_173182)(stringtableobj173012* t, NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, cmp_4517)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_BOOL, mustrehash_173194)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_173410)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NI, rawget_173421)(stringtableobj173012* t, NimStringDesc* key);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, nstGet)(stringtableobj173012* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc**, nstTake)(stringtableobj173012* t, NimStringDesc* key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, nsthasKey)(stringtableobj173012* t, NimStringDesc* key);
N_NIMCALL(void, rawinsert_173499)(stringtableobj173012* t, keyvaluepairseq173010** data, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, enlarge_173521)(stringtableobj173012* t);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP455)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, nstPut)(stringtableobj173012* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, raiseformatexception_173639)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, getvalue_173667)(stringtableobj173012* t, NU8 flags, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, getenv_128642)(NimStringDesc* key);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(stringtableobj173012*, nstnewStringTable)(NU8 mode);
N_NIMCALL(void, TMP463)(void* p, NI op);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(stringtableobj173012*, nstnewStringTableWithPairs)(NimStringDesc** keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(stringtableobj173012*, nstnewStringTableWithTableConstr)(TY109352* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, stringtableobj173012* t, NU8 flags);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nstDollar)(stringtableobj173012* t);
STRING_LITERAL(TMP444, "length > counter ", 17);
STRING_LITERAL(TMP450, "", 0);
STRING_LITERAL(TMP452, "key does not exist: ", 20);
STRING_LITERAL(TMP456, "format string: key not found: ", 30);
NIM_CONST TY76268 patternchars_173876 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TMP473, "{:}", 3);
STRING_LITERAL(TMP474, "{", 1);
STRING_LITERAL(TMP475, ", ", 2);
STRING_LITERAL(TMP476, ": ", 2);
STRING_LITERAL(TMP477, "}", 1);
extern TFrame* frameptr_16442;
extern TNimType NTI173464; /* ref KeyError */
extern TNimType NTI3251; /* KeyError */
extern tgcheap47416 gch_47444;
extern TNimType NTI109352; /* tuple[nonDST: string, DST: string] */
TNimType NTI173010; /* KeyValuePairSeq */
extern TNimType NTI21801; /* ref ValueError */
extern TNimType NTI3249; /* ValueError */
extern TNimType NTI3211; /* RootObj */
TNimType NTI173012; /* StringTableObj */
extern TNimType NTI108; /* int */
TNimType NTI173006; /* StringTableMode */
TNimType NTI173014; /* StringTableRef */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

N_NIMCALL(NI, nstlen)(stringtableobj173012* t) {
	NI result;
	nimfr("len", "strtabs.nim")
	result = 0;
	nimln(39, "strtabs.nim");
	result = (*t).Counter;
	popFrame();
	return result;
}

N_NIMCALL(NI, myhash_173171)(stringtableobj173012* t, NimStringDesc* key) {
	NI result;
	nimfr("myhash", "strtabs.nim")
	result = 0;
	nimln(78, "strtabs.nim");
	switch ((*t).Mode) {
	case ((NU8) 0):
	{
		nimln(79, "strtabs.nim");
		result = hash_137842(key);
	}
	break;
	case ((NU8) 1):
	{
		nimln(80, "strtabs.nim");
		result = hashignorecase_137980(key);
	}
	break;
	case ((NU8) 2):
	{
		nimln(81, "strtabs.nim");
		result = hashignorestyle_137888(key);
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, mycmp_173182)(stringtableobj173012* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	nimfr("myCmp", "strtabs.nim")
	result = 0;
	nimln(84, "strtabs.nim");
	switch ((*t).Mode) {
	case ((NU8) 0):
	{
		NI LOC2;
		nimln(85, "strtabs.nim");
		nimln(85, "strtabs.nim");
		nimln(85, "strtabs.nim");
		LOC2 = 0;
		LOC2 = cmp_4517(a, b);
		result = (LOC2 == 0);
	}
	break;
	case ((NU8) 1):
	{
		NI LOC4;
		nimln(86, "strtabs.nim");
		nimln(86, "strtabs.nim");
		nimln(86, "strtabs.nim");
		LOC4 = 0;
		LOC4 = nsuCmpIgnoreCase(a, b);
		result = (LOC4 == 0);
	}
	break;
	case ((NU8) 2):
	{
		NI LOC6;
		nimln(87, "strtabs.nim");
		nimln(87, "strtabs.nim");
		nimln(87, "strtabs.nim");
		LOC6 = 0;
		LOC6 = nsuCmpIgnoreStyle(a, b);
		result = (LOC6 == 0);
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, mustrehash_173194)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP445;
	NI TMP446;
	NI TMP447;
	nimfr("mustRehash", "strtabs.nim")
	result = 0;
	nimln(90, "strtabs.nim");
	{
		nimln(90, "strtabs.nim");
		nimln(90, "strtabs.nim");
		if (!!((counter < length))) goto LA3;
		nimln(90, "strtabs.nim");
		failedassertimpl_85425(((NimStringDesc*) &TMP444));
	}
	LA3: ;
	nimln(91, "strtabs.nim");
	nimln(91, "strtabs.nim");
	LOC5 = 0;
	nimln(91, "strtabs.nim");
	nimln(91, "strtabs.nim");
	TMP445 = mulInt(length, 2);
	nimln(91, "strtabs.nim");
	TMP446 = mulInt(counter, 3);
	LOC5 = ((NI64)(TMP445) < (NI64)(TMP446));
	if (LOC5) goto LA6;
	nimln(91, "strtabs.nim");
	nimln(91, "strtabs.nim");
	TMP447 = subInt(length, counter);
	LOC5 = ((NI64)(TMP447) < 4);
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_173410)(NI h, NI maxhash) {
	NI result;
	NI TMP448;
	NI TMP449;
	nimfr("nextTry", "strtabs.nim")
	result = 0;
	nimln(94, "strtabs.nim");
	nimln(94, "strtabs.nim");
	nimln(94, "strtabs.nim");
	nimln(94, "strtabs.nim");
	TMP448 = mulInt(5, h);
	TMP449 = addInt((NI64)(TMP448), 1);
	result = (NI)((NI64)(TMP449) & maxhash);
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_173421)(stringtableobj173012* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "strtabs.nim")
	result = 0;
	nimln(97, "strtabs.nim");
	nimln(97, "strtabs.nim");
	nimln(97, "strtabs.nim");
	LOC1 = 0;
	LOC1 = myhash_173171(t, key);
	nimln(97, "strtabs.nim");
	h = (NI)(LOC1 & ((*t).Data->Sup.len-1));
	{
		nimln(98, "strtabs.nim");
		while (1) {
			nimln(98, "strtabs.nim");
			nimln(98, "strtabs.nim");
			if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
			if (!!((*t).Data->data[h].Field0 == 0)) goto LA3;
			nimln(99, "strtabs.nim");
			{
				NIM_BOOL LOC6;
				nimln(99, "strtabs.nim");
				if ((NU)(h) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
				LOC6 = 0;
				LOC6 = mycmp_173182(t, (*t).Data->data[h].Field0, key);
				if (!LOC6) goto LA7;
				nimln(100, "strtabs.nim");
				nimln(100, "strtabs.nim");
				result = h;
				goto BeforeRet;
			}
			LA7: ;
			nimln(101, "strtabs.nim");
			nimln(101, "strtabs.nim");
			h = nexttry_173410(h, ((*t).Data->Sup.len-1));
		} LA3: ;
	}
	nimln(102, "strtabs.nim");
	result = -1;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstGet)(stringtableobj173012* t, NimStringDesc* key) {
	NimStringDesc* result;
	NI index;
	nimfr("[]", "strtabs.nim")
	result = 0;
	nimln(108, "strtabs.nim");
	index = rawget_173421(t, key);
	nimln(109, "strtabs.nim");
	{
		nimln(109, "strtabs.nim");
		if (!(0 <= index)) goto LA3;
		nimln(109, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
		result = copyString((*t).Data->data[index].Field1);
	}
	goto LA1;
	LA3: ;
	{
		nimln(110, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP450));
	}
	LA1: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NimStringDesc**, nstTake)(stringtableobj173012* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index;
	nimfr("mget", "strtabs.nim")
	result = 0;
	nimln(116, "strtabs.nim");
	index = rawget_173421(t, key);
	nimln(117, "strtabs.nim");
	{
		nimln(117, "strtabs.nim");
		if (!(0 <= index)) goto LA3;
		nimln(117, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
		result = (&(*t).Data->data[index].Field1);
	}
	goto LA1;
	LA3: ;
	{
		keyerror3251* e_173463;
		NimStringDesc* LOC6;
		e_173463 = 0;
		nimln(2149, "system.nim");
		e_173463 = (keyerror3251*) newObj((&NTI173464), sizeof(keyerror3251));
		(*e_173463).Sup.Sup.Sup.m_type = (&NTI3251);
		nimln(2150, "system.nim");
		nimln(118, "strtabs.nim");
		LOC6 = 0;
		LOC6 = rawNewString(key->Sup.len + 20);
appendString(LOC6, ((NimStringDesc*) &TMP452));
appendString(LOC6, key);
		asgnRefNoCycle((void**) (&(*e_173463).Sup.Sup.message), LOC6);
		nimln(118, "strtabs.nim");
		raiseException((Exception*)e_173463, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nsthasKey)(stringtableobj173012* t, NimStringDesc* key) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "strtabs.nim")
	result = 0;
	nimln(122, "strtabs.nim");
	nimln(122, "strtabs.nim");
	nimln(122, "strtabs.nim");
	LOC1 = 0;
	LOC1 = rawget_173421(t, key);
	result = (0 <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_173499)(stringtableobj173012* t, keyvaluepairseq173010** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("rawInsert", "strtabs.nim")
	nimln(125, "strtabs.nim");
	nimln(125, "strtabs.nim");
	nimln(125, "strtabs.nim");
	LOC1 = 0;
	LOC1 = myhash_173171(t, key);
	nimln(125, "strtabs.nim");
	h = (NI)(LOC1 & ((*data)->Sup.len-1));
	{
		nimln(126, "strtabs.nim");
		while (1) {
			nimln(126, "strtabs.nim");
			nimln(126, "strtabs.nim");
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!((*data)->data[h].Field0 == 0)) goto LA3;
			nimln(127, "strtabs.nim");
			nimln(127, "strtabs.nim");
			h = nexttry_173410(h, ((*data)->Sup.len-1));
		} LA3: ;
	}
	nimln(128, "strtabs.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(129, "strtabs.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC5 = 0;
	LOC5 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (LOC5) nimGCunrefNoCycle(LOC5);
	popFrame();
}
N_NIMCALL(void, TMP455)(void* p, NI op) {
	keyvaluepairseq173010* a;
	NI LOC1;
	a = (keyvaluepairseq173010*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, enlarge_173521)(stringtableobj173012* t) {
	keyvaluepairseq173010* n;
	NI TMP453;
	keyvaluepairseq173010* LOC8;
	nimfr("enlarge", "strtabs.nim")
	n = 0;
	nimln(133, "strtabs.nim");
	nimln(133, "strtabs.nim");
	nimln(133, "strtabs.nim");
	TMP453 = mulInt((*t).Data->Sup.len, 2);
	n = (keyvaluepairseq173010*) newSeq((&NTI173010), (NI64)(TMP453));
	{
		NI i_173564;
		NI HEX3Atmp_173583;
		NI res_173586;
		i_173564 = 0;
		HEX3Atmp_173583 = 0;
		nimln(134, "strtabs.nim");
		nimln(134, "strtabs.nim");
		HEX3Atmp_173583 = ((*t).Data->Sup.len-1);
		nimln(1569, "system.nim");
		res_173586 = 0;
		{
			nimln(1570, "system.nim");
			while (1) {
				nimln(1570, "system.nim");
				if (!(res_173586 <= HEX3Atmp_173583)) goto LA3;
				nimln(1569, "system.nim");
				i_173564 = res_173586;
				nimln(135, "strtabs.nim");
				{
					nimln(135, "strtabs.nim");
					nimln(135, "strtabs.nim");
					if ((NU)(i_173564) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
					if (!!((*t).Data->data[i_173564].Field0 == 0)) goto LA6;
					nimln(135, "strtabs.nim");
					if ((NU)(i_173564) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
					if ((NU)(i_173564) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
					rawinsert_173499(t, (&n), (*t).Data->data[i_173564].Field0, (*t).Data->data[i_173564].Field1);
				}
				LA6: ;
				nimln(1572, "system.nim");
				res_173586 = addInt(res_173586, 1);
			} LA3: ;
		}
	}
	nimln(136, "strtabs.nim");
	LOC8 = 0;
	LOC8 = (*t).Data;
	asgnRefNoCycle((void**) (&(*t).Data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, nstPut)(stringtableobj173012* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	nimfr("[]=", "strtabs.nim")
	nimln(140, "strtabs.nim");
	index = rawget_173421(t, key);
	nimln(141, "strtabs.nim");
	{
		NimStringDesc* LOC5;
		nimln(141, "strtabs.nim");
		if (!(0 <= index)) goto LA3;
		nimln(142, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t).Data->data[index].Field1; (*t).Data->data[index].Field1 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		nimln(144, "strtabs.nim");
		{
			NIM_BOOL LOC9;
			nimln(144, "strtabs.nim");
			nimln(144, "strtabs.nim");
			LOC9 = 0;
			LOC9 = mustrehash_173194((*t).Data->Sup.len, (*t).Counter);
			if (!LOC9) goto LA10;
			nimln(144, "strtabs.nim");
			enlarge_173521(t);
		}
		LA10: ;
		nimln(145, "strtabs.nim");
		rawinsert_173499(t, (&(*t).Data), key, val);
		nimln(146, "strtabs.nim");
		(*t).Counter = addInt((*t).Counter, 1);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, raiseformatexception_173639)(NimStringDesc* s) {
	valueerror3249* e;
	NimStringDesc* LOC1;
	nimfr("raiseFormatException", "strtabs.nim")
	e = 0;
	nimln(150, "strtabs.nim");
	e = (valueerror3249*) newObj((&NTI21801), sizeof(valueerror3249));
	(*e).Sup.Sup.m_type = (&NTI3249);
	nimln(151, "strtabs.nim");
	nimln(151, "strtabs.nim");
	LOC1 = 0;
	LOC1 = rawNewString(s->Sup.len + 30);
appendString(LOC1, ((NimStringDesc*) &TMP456));
appendString(LOC1, s);
	asgnRefNoCycle((void**) (&(*e).Sup.message), LOC1);
	nimln(152, "strtabs.nim");
	raiseException((Exception*)e, "ValueError");
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI64)((*dest).Sup.len + 1))- 0] = 0;
	(*dest).Sup.len += 1;
}

N_NIMCALL(NimStringDesc*, getvalue_173667)(stringtableobj173012* t, NU8 flags, NimStringDesc* key) {
	NimStringDesc* result;
	nimfr("getValue", "strtabs.nim")
	result = 0;
	nimln(155, "strtabs.nim");
	{
		NIM_BOOL LOC3;
		nimln(155, "strtabs.nim");
		LOC3 = 0;
		LOC3 = nsthasKey(t, key);
		if (!LOC3) goto LA4;
		nimln(155, "strtabs.nim");
		nimln(155, "strtabs.nim");
		result = nstGet(t, key);
		goto BeforeRet;
	}
	LA4: ;
	nimln(157, "strtabs.nim");
	{
		nimln(157, "strtabs.nim");
		if (!((flags &(1<<((((NU8) 0))&7)))!=0)) goto LA8;
		nimln(157, "strtabs.nim");
		nimln(157, "strtabs.nim");
		result = getenv_128642(key);
	}
	goto LA6;
	LA8: ;
	{
		nimln(158, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP450));
	}
	LA6: ;
	nimln(159, "strtabs.nim");
	{
		nimln(159, "strtabs.nim");
		nimln(159, "strtabs.nim");
		if (!(result->Sup.len == 0)) goto LA13;
		nimln(160, "strtabs.nim");
		{
			NimStringDesc* LOC19;
			nimln(160, "strtabs.nim");
			if (!((flags &(1<<((((NU8) 2))&7)))!=0)) goto LA17;
			nimln(160, "strtabs.nim");
			nimln(160, "strtabs.nim");
			LOC19 = 0;
			LOC19 = rawNewString(key->Sup.len + 1);
appendChar(LOC19, 36);
appendString(LOC19, key);
			result = LOC19;
		}
		goto LA15;
		LA17: ;
		{
			nimln(161, "strtabs.nim");
			nimln(161, "strtabs.nim");
			if (!!(((flags &(1<<((((NU8) 1))&7)))!=0))) goto LA21;
			nimln(161, "strtabs.nim");
			raiseformatexception_173639(key);
		}
		goto LA15;
		LA21: ;
		LA15: ;
	}
	LA13: ;
	BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP463)(void* p, NI op) {
	stringtableobj173012* a;
	a = (stringtableobj173012*)p;
	nimGCvisit((void*)(*a).Data, op);
}

N_NIMCALL(stringtableobj173012*, nstnewStringTable)(NU8 mode) {
	stringtableobj173012* result;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(166, "strtabs.nim");
	result = (stringtableobj173012*) newObj((&NTI173014), sizeof(stringtableobj173012));
	(*result).Sup.m_type = (&NTI173012);
	nimln(167, "strtabs.nim");
	(*result).Mode = mode;
	nimln(168, "strtabs.nim");
	(*result).Counter = 0;
	nimln(169, "strtabs.nim");
	if ((*result).Data) nimGCunrefNoCycle((*result).Data);
	(*result).Data = (keyvaluepairseq173010*) newSeqRC1((&NTI173010), 64);
	popFrame();
	return result;
}

N_NIMCALL(stringtableobj173012*, nstnewStringTableWithPairs)(NimStringDesc** keyvaluepairs, NI keyvaluepairsLen0, NU8 mode) {
	stringtableobj173012* result;
	NI i;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(178, "strtabs.nim");
	result = nstnewStringTable(mode);
	nimln(179, "strtabs.nim");
	i = 0;
	{
		nimln(180, "strtabs.nim");
		while (1) {
			NI TMP464;
			nimln(180, "strtabs.nim");
			nimln(180, "strtabs.nim");
			if (!(i < (keyvaluepairsLen0-1))) goto LA2;
			nimln(181, "strtabs.nim");
			if ((NU)(i) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
			nimln(181, "strtabs.nim");
			TMP464 = addInt(i, 1);
			if ((NU)((NI64)(TMP464)) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
			nstPut(result, keyvaluepairs[i], keyvaluepairs[(NI64)(TMP464)]);
			nimln(182, "strtabs.nim");
			i = addInt(i, 2);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(stringtableobj173012*, nstnewStringTableWithTableConstr)(TY109352* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode) {
	stringtableobj173012* result;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(191, "strtabs.nim");
	result = nstnewStringTable(mode);
	{
		NimStringDesc* key_173846;
		NimStringDesc* val_173847;
		NI i_173851;
		key_173846 = 0;
		val_173847 = 0;
		nimln(1649, "system.nim");
		i_173851 = 0;
		{
			nimln(1650, "system.nim");
			while (1) {
				nimln(1650, "system.nim");
				nimln(1650, "system.nim");
				if (!(i_173851 < keyvaluepairsLen0)) goto LA3;
				nimln(1651, "system.nim");
				if ((NU)(i_173851) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
				key_173846 = keyvaluepairs[i_173851].Field0;
				nimln(1651, "system.nim");
				if ((NU)(i_173851) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
				val_173847 = keyvaluepairs[i_173851].Field1;
				nimln(192, "strtabs.nim");
				nstPut(result, key_173846, val_173847);
				nimln(1652, "system.nim");
				i_173851 = addInt(i_173851, 1);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, stringtableobj173012* t, NU8 flags) {
	NimStringDesc* result;
	NI i;
	nimfr("%", "strtabs.nim")
	result = 0;
	nimln(199, "strtabs.nim");
	result = copyString(((NimStringDesc*) &TMP450));
	nimln(200, "strtabs.nim");
	i = 0;
	{
		nimln(201, "strtabs.nim");
		while (1) {
			nimln(201, "strtabs.nim");
			nimln(201, "strtabs.nim");
			if (!(i < f->Sup.len)) goto LA2;
			nimln(202, "strtabs.nim");
			{
				NI TMP465;
				nimln(202, "strtabs.nim");
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				if (!((NU8)(f->data[i]) == (NU8)(36))) goto LA5;
				nimln(203, "strtabs.nim");
				nimln(203, "strtabs.nim");
				TMP465 = addInt(i, 1);
				if ((NU)((NI64)(TMP465)) > (NU)(f->Sup.len)) raiseIndexError();
				switch (((NU8)(f->data[(NI64)(TMP465)]))) {
				case 36:
				{
					nimln(205, "strtabs.nim");
					result = addChar(result, 36);
					nimln(206, "strtabs.nim");
					i = addInt(i, 2);
				}
				break;
				case 123:
				{
					NI j;
					NI TMP466;
					NI TMP467;
					NI TMP468;
					NimStringDesc* LOC13;
					NimStringDesc* LOC14;
					NI TMP469;
					nimln(208, "strtabs.nim");
					nimln(208, "strtabs.nim");
					TMP466 = addInt(i, 1);
					j = (NI64)(TMP466);
					{
						nimln(209, "strtabs.nim");
						while (1) {
							NIM_BOOL LOC11;
							nimln(209, "strtabs.nim");
							LOC11 = 0;
							nimln(209, "strtabs.nim");
							nimln(209, "strtabs.nim");
							LOC11 = (j < f->Sup.len);
							if (!(LOC11)) goto LA12;
							nimln(209, "strtabs.nim");
							nimln(209, "strtabs.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							LOC11 = !(((NU8)(f->data[j]) == (NU8)(125)));
							LA12: ;
							if (!LOC11) goto LA10;
							nimln(209, "strtabs.nim");
							j = addInt(j, 1);
						} LA10: ;
					}
					nimln(210, "strtabs.nim");
					nimln(210, "strtabs.nim");
					nimln(210, "strtabs.nim");
					nimln(210, "strtabs.nim");
					TMP467 = addInt(i, 2);
					nimln(210, "strtabs.nim");
					TMP468 = subInt(j, 1);
					LOC13 = 0;
					LOC13 = copyStrLast(f, (NI64)(TMP467), (NI64)(TMP468));
					LOC14 = 0;
					LOC14 = getvalue_173667(t, flags, LOC13);
					result = resizeString(result, LOC14->Sup.len + 0);
appendString(result, LOC14);
					nimln(211, "strtabs.nim");
					nimln(211, "strtabs.nim");
					TMP469 = addInt(j, 1);
					i = (NI64)(TMP469);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j;
					NI TMP470;
					NI TMP471;
					NI TMP472;
					NimStringDesc* LOC20;
					NimStringDesc* LOC21;
					nimln(213, "strtabs.nim");
					nimln(213, "strtabs.nim");
					TMP470 = addInt(i, 1);
					j = (NI64)(TMP470);
					{
						nimln(214, "strtabs.nim");
						while (1) {
							NIM_BOOL LOC18;
							nimln(214, "strtabs.nim");
							LOC18 = 0;
							nimln(214, "strtabs.nim");
							nimln(214, "strtabs.nim");
							LOC18 = (j < f->Sup.len);
							if (!(LOC18)) goto LA19;
							nimln(214, "strtabs.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							LOC18 = (((NU8)(f->data[j])) >= ((NU8)(97)) && ((NU8)(f->data[j])) <= ((NU8)(122)) || ((NU8)(f->data[j])) >= ((NU8)(65)) && ((NU8)(f->data[j])) <= ((NU8)(90)) || ((NU8)(f->data[j])) >= ((NU8)(48)) && ((NU8)(f->data[j])) <= ((NU8)(57)) || ((NU8)(f->data[j])) == ((NU8)(95)) || ((NU8)(f->data[j])) >= ((NU8)(128)) && ((NU8)(f->data[j])) <= ((NU8)(255)));
							LA19: ;
							if (!LOC18) goto LA17;
							nimln(214, "strtabs.nim");
							j = addInt(j, 1);
						} LA17: ;
					}
					nimln(215, "strtabs.nim");
					nimln(215, "strtabs.nim");
					nimln(215, "strtabs.nim");
					nimln(215, "strtabs.nim");
					TMP471 = addInt(i, 1);
					nimln(215, "strtabs.nim");
					TMP472 = subInt(j, 1);
					LOC20 = 0;
					LOC20 = copyStrLast(f, (NI64)(TMP471), (NI64)(TMP472));
					LOC21 = 0;
					LOC21 = getvalue_173667(t, flags, LOC20);
					result = resizeString(result, LOC21->Sup.len + 0);
appendString(result, LOC21);
					nimln(216, "strtabs.nim");
					i = j;
				}
				break;
				default:
				{
					nimln(218, "strtabs.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					result = addChar(result, f->data[i]);
					nimln(219, "strtabs.nim");
					i = addInt(i, 1);
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				nimln(221, "strtabs.nim");
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				result = addChar(result, f->data[i]);
				nimln(222, "strtabs.nim");
				i = addInt(i, 1);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstDollar)(stringtableobj173012* t) {
	NimStringDesc* result;
	nimfr("$", "strtabs.nim")
	result = 0;
	nimln(226, "strtabs.nim");
	{
		NI LOC3;
		nimln(226, "strtabs.nim");
		nimln(226, "strtabs.nim");
		LOC3 = 0;
		LOC3 = nstlen(t);
		if (!(LOC3 == 0)) goto LA4;
		nimln(227, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP473));
	}
	goto LA1;
	LA4: ;
	{
		nimln(229, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP474));
		{
			NimStringDesc* key_173988;
			NimStringDesc* val_173989;
			key_173988 = 0;
			val_173989 = 0;
			{
				NI h_173995;
				NI HEX3Atmp_173997;
				NI res_173999;
				h_173995 = 0;
				HEX3Atmp_173997 = 0;
				nimln(43, "strtabs.nim");
				nimln(43, "strtabs.nim");
				HEX3Atmp_173997 = ((*t).Data->Sup.len-1);
				nimln(1576, "system.nim");
				res_173999 = 0;
				{
					nimln(1577, "system.nim");
					while (1) {
						nimln(1577, "system.nim");
						if (!(res_173999 <= HEX3Atmp_173997)) goto LA10;
						nimln(1576, "system.nim");
						h_173995 = res_173999;
						nimln(44, "strtabs.nim");
						{
							nimln(44, "strtabs.nim");
							nimln(44, "strtabs.nim");
							if ((NU)(h_173995) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
							if (!!((*t).Data->data[h_173995].Field0 == 0)) goto LA13;
							nimln(45, "strtabs.nim");
							if ((NU)(h_173995) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
							key_173988 = (*t).Data->data[h_173995].Field0;
							nimln(45, "strtabs.nim");
							if ((NU)(h_173995) >= (NU)((*t).Data->Sup.len)) raiseIndexError();
							val_173989 = (*t).Data->data[h_173995].Field1;
							nimln(231, "strtabs.nim");
							{
								nimln(231, "strtabs.nim");
								nimln(231, "strtabs.nim");
								if (!(1 < result->Sup.len)) goto LA17;
								nimln(231, "strtabs.nim");
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP475));
							}
							LA17: ;
							nimln(232, "strtabs.nim");
							result = resizeString(result, key_173988->Sup.len + 0);
appendString(result, key_173988);
							nimln(233, "strtabs.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP476));
							nimln(234, "strtabs.nim");
							result = resizeString(result, val_173989->Sup.len + 0);
appendString(result, val_173989);
						}
						LA13: ;
						nimln(1579, "system.nim");
						res_173999 = addInt(res_173999, 1);
					} LA10: ;
				}
			}
		}
		nimln(235, "strtabs.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP477));
	}
	LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void) {
	nimfr("strtabs", "strtabs.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void) {
static TNimNode* TMP459[3];
static TNimNode* TMP460[3];
NI TMP462;
static char* NIM_CONST TMP461[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TMP440[8];
NTI173010.size = sizeof(keyvaluepairseq173010*);
NTI173010.kind = 24;
NTI173010.base = (&NTI109352);
NTI173010.flags = 2;
NTI173010.marker = TMP455;
NTI173012.size = sizeof(stringtableobj173012);
NTI173012.kind = 17;
NTI173012.base = (&NTI3211);
TMP459[0] = &TMP440[1];
TMP440[1].kind = 1;
TMP440[1].offset = offsetof(stringtableobj173012, Counter);
TMP440[1].typ = (&NTI108);
TMP440[1].name = "counter";
TMP459[1] = &TMP440[2];
TMP440[2].kind = 1;
TMP440[2].offset = offsetof(stringtableobj173012, Data);
TMP440[2].typ = (&NTI173010);
TMP440[2].name = "data";
TMP459[2] = &TMP440[3];
NTI173006.size = sizeof(NU8);
NTI173006.kind = 14;
NTI173006.base = 0;
NTI173006.flags = 3;
for (TMP462 = 0; TMP462 < 3; TMP462++) {
TMP440[TMP462+4].kind = 1;
TMP440[TMP462+4].offset = TMP462;
TMP440[TMP462+4].name = TMP461[TMP462];
TMP460[TMP462] = &TMP440[TMP462+4];
}
TMP440[7].len = 3; TMP440[7].kind = 2; TMP440[7].sons = &TMP460[0];
NTI173006.node = &TMP440[7];
TMP440[3].kind = 1;
TMP440[3].offset = offsetof(stringtableobj173012, Mode);
TMP440[3].typ = (&NTI173006);
TMP440[3].name = "mode";
TMP440[0].len = 3; TMP440[0].kind = 2; TMP440[0].sons = &TMP459[0];
NTI173012.node = &TMP440[0];
NTI173014.size = sizeof(stringtableobj173012*);
NTI173014.kind = 22;
NTI173014.base = (&NTI173012);
NTI173014.marker = TMP463;
}

