/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_scgi.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/stdlib_scgi.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <sys/socket.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct scgierror211005 scgierror211005;
typedef struct ioerror3231 ioerror3231;
typedef struct systemerror3229 systemerror3229;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct stringtableobj173012 stringtableobj173012;
typedef struct TY109352 TY109352;
typedef struct tsocketimpl193807 tsocketimpl193807;
typedef struct scgistate211131 scgistate211131;
typedef struct TY202215 TY202215;
typedef struct asyncclientHEX3Aobjecttype211148 asyncclientHEX3Aobjecttype211148;
typedef struct asyncsocketobj207215 asyncsocketobj207215;
typedef struct asyncscgistateobj211137 asyncscgistateobj211137;
typedef struct dispatcherobj207211 dispatcherobj207211;
typedef struct TY211519 TY211519;
typedef struct TY161264 TY161264;
typedef struct TY161267 TY161267;
typedef struct delegateobj207205 delegateobj207205;
typedef struct TY211572 TY211572;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
typedef struct keyvaluepairseq173010 keyvaluepairseq173010;
typedef struct TY207242 TY207242;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  systemerror3229  {
  Exception Sup;
};
struct  ioerror3231  {
  systemerror3229 Sup;
};
struct  scgierror211005  {
  ioerror3231 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
struct TY109352 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef TY109352 TY185182[1];
struct  scgistate211131  {
  TNimObject Sup;
tsocketimpl193807* Server;
NI Buflen;
tsocketimpl193807* Client;
stringtableobj173012* Headers;
NimStringDesc* Input;
};
typedef NIM_CHAR TY175208[4001];
struct  tsocketimpl193807  {
int Fd;
NIM_BOOL Isbuffered;
union {
struct {TY175208 Buffer;
NI Currpos;
NI Buflen;
} S1;
} isbufferedU;
NIM_BOOL Nonblocking;
};
typedef tsocketimpl193807* TY208923[1];
typedef N_NIMCALL_PTR(NIM_BOOL, TY211369) (tsocketimpl193807* client, NimStringDesc* input, stringtableobj173012* headers);
struct  asyncclientHEX3Aobjecttype211148  {
asyncsocketobj207215* C;
NU8 Mode;
NI Datalen;
stringtableobj173012* Headers;
NimStringDesc* Input;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (asyncsocketobj207215* s, void* ClEnv);
void* ClEnv;
} TY207246;
typedef N_CLOSURE_PTR(void, TMP887) (asyncsocketobj207215* s, void* ClEnv);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (asyncsocketobj207215* client, NimStringDesc* input, stringtableobj173012* headers, void* ClEnv);
void* ClEnv;
} TY211154;
struct  asyncscgistateobj211137  {
TY211154 Handlerequest;
asyncsocketobj207215* Asyncserver;
dispatcherobj207211* Disp;
};
typedef N_CLOSURE_PTR(void, TMP894) (asyncsocketobj207215* client, NimStringDesc* input, stringtableobj173012* headers);
typedef N_CLOSURE_PTR(void, TMP896) (asyncsocketobj207215* client, NimStringDesc* input, stringtableobj173012* headers);
typedef N_CLOSURE_PTR(void, TMP897) (asyncsocketobj207215* client, NimStringDesc* input, stringtableobj173012* headers);
struct  TY211519  {
NI HEX3Astate;
asyncclientHEX3Aobjecttype211148* Asyncclient211513;
asyncscgistateobj211137* S211484;
};
struct TY161264 {
void* Field0;
TY161267* Field1;
};
struct  asyncsocketobj207215  {
  TNimObject Sup;
tsocketimpl193807* Socket;
NU8 Info;
TY207246 Handleread;
TY207246 Handlewrite;
TY207246 Handleconnect;
TY207246 Handleaccept;
TY207246 Handletask;
NimStringDesc* Linebuffer;
NimStringDesc* Sendbuffer;
NIM_BOOL Sslneedaccept;
NU8 Proto;
delegateobj207205* Deleg;
};
struct  TY211572  {
NI HEX3Astate;
asyncscgistateobj211137* Cres211551;
};
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  stringtableobj173012  {
  TNimObject Sup;
NI Counter;
keyvaluepairseq173010* Data;
NU8 Mode;
};
struct  dispatcherobj207211  {
TY207242* Delegates;
};
struct TY161267 {
char dummy;
};
typedef N_NIMCALL_PTR(void, TY207220) (TNimObject* h);
typedef N_NIMCALL_PTR(void, TY207224) (TNimObject* h);
typedef N_NIMCALL_PTR(void, TY207228) (TNimObject* h);
typedef N_NIMCALL_PTR(NIM_BOOL, TY207232) (TNimObject* h);
typedef N_NIMCALL_PTR(void, TY207237) (TNimObject* h);
struct  delegateobj207205  {
int Fd;
TNimObject* Deleval;
TY207220 Handleread;
TY207224 Handlewrite;
TY207228 Handleerror;
TY207232 Hasdatabuffered;
NIM_BOOL Open;
TY207237 Task;
NU8 Mode;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY202215 {
  TGenericSeq Sup;
  tsocketimpl193807* data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq173010 {
  TGenericSeq Sup;
  TY109352 data[SEQ_DECL_SIZE];
};
struct TY207242 {
  TGenericSeq Sup;
  delegateobj207205* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, raisescgierror_211009)(NimStringDesc* msg);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP859)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, parseword_211037)(NimStringDesc* inp, NimStringDesc** outp, NI start);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_75228, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(stringtableobj173012*, parseheaders_211069)(NimStringDesc* s, NI l);
N_NIMCALL(stringtableobj173012*, nstnewStringTableWithTableConstr)(TY109352* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(void, nstPut)(stringtableobj173012* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NIM_CHAR, recvchar_211117)(tsocketimpl193807* s);
N_NIMCALL(NI, recv_201502)(tsocketimpl193807* socket, void* data, NI size);
N_NIMCALL(void, recvbuffer_211173)(scgistate211131* s, NI l);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(void, open_211186)(scgistate211131* s, NU16 port, NimStringDesc* address, NIM_BOOL reuseaddr);
N_NIMCALL(tsocketimpl193807*, socket_194804)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
N_NIMCALL(void, raiseoserror_123009)(NI32 errorcode);
N_NIMCALL(NI32, oslasterror_123041)(void);
N_NIMCALL(void, setsockopt_199292)(tsocketimpl193807* socket, NU8 opt, NIM_BOOL value, int level);
N_NIMCALL(void, bindaddr_195974)(tsocketimpl193807* socket, NU16 port, NimStringDesc* address);
N_NIMCALL(void, listen_195809)(tsocketimpl193807* socket, int backlog);
N_NIMCALL(void, close_211249)(scgistate211131* s);
N_NIMCALL(void, close_197678)(tsocketimpl193807* socket);
N_NIMCALL(NIM_BOOL, next_211259)(scgistate211131* s, NI timeout);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NI, select_201301)(TY202215** readfds, NI timeout);
N_NIMCALL(void, accept_197601)(tsocketimpl193807* server, tsocketimpl193807** client);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nstGet)(stringtableobj173012* t, NimStringDesc* key);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(void, writestatusoktextcontent_211357)(tsocketimpl193807* c, NimStringDesc* contenttype);
N_NIMCALL(void, send_204007)(tsocketimpl193807* socket, NimStringDesc* data);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, run_211367)(TY211369 handlerequest, NU16 port);
N_NIMCALL(NU8, recvbufferasync_211396)(asyncclientHEX3Aobjecttype211148* client, NI l);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NI, recvasync_202324)(tsocketimpl193807* socket, NimStringDesc** data, NI size);
N_NIMCALL(tsocketimpl193807*, getsocket_209046)(asyncsocketobj207215* s);
N_NIMCALL(void, close_207625)(asyncsocketobj207215* sock);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, checkclosesocket_211411)(asyncclientHEX3Aobjecttype211148* client);
N_NIMCALL(NIM_BOOL, isclosed_209113)(asyncsocketobj207215* s);
N_NIMCALL(NIM_BOOL, issenddatabuffered_209132)(asyncsocketobj207215* s);
N_NIMCALL(void, sethandlewrite_209142)(asyncsocketobj207215* s, TY207246 handlewrite);
N_NIMCALL(void, HEX3Aanonymous_211414)(asyncsocketobj207215* s);
N_NIMCALL(void, delhandlewrite_209155)(asyncsocketobj207215* s);
N_NIMCALL(void, handleclientread_211426)(asyncclientHEX3Aobjecttype211148* client, asyncscgistateobj211137* s);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51425)(tcell45335* c);
static N_INLINE(NIM_BOOL, canbecycleroot_49067)(tcell45335* c);
static N_INLINE(void, rtladdcycleroot_49829)(tcell45335* c);
N_NOINLINE(void, incl_46071)(tcellset45347* s, tcell45335* cell);
static N_INLINE(void, decref_51004)(tcell45335* c);
N_NIMCALL(void, handleaccept_211481)(asyncsocketobj207215* sock, asyncscgistateobj211137* s);
N_NIMCALL(void, TMP903)(void* p, NI op);
N_NIMCALL(void, TMP906)(void* p, NI op);
N_NIMCALL(void, TMP907)(void* p, NI op);
N_NIMCALL(void, accept_208626)(asyncsocketobj207215* server, asyncsocketobj207215** client);
N_CLOSURE(void, HEX3Aanonymous_211514)(asyncsocketobj207215* sock, void* ClEnv);
N_NIMCALL(delegateobj207205*, register_208760)(dispatcherobj207211* d, asyncsocketobj207215* sock);
N_NIMCALL(asyncscgistateobj211137*, open_211538)(TY211154 handlerequest, NU16 port, NimStringDesc* address, NIM_BOOL reuseaddr);
N_NIMCALL(void, TMP909)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_NIMCALL(asyncsocketobj207215*, asyncsocket_207400)(NU8 domain, NU8 typ, NU8 protocol, NIM_BOOL buffered);
N_CLOSURE(void, HEX3Aanonymous_211568)(asyncsocketobj207215* s, void* ClEnv);
N_NIMCALL(void, bindaddr_208293)(asyncsocketobj207215* sock, NU16 port, NimStringDesc* address);
N_NIMCALL(void, listen_208330)(asyncsocketobj207215* sock);
N_NIMCALL(delegateobj207205*, register_211586)(dispatcherobj207211* d, asyncscgistateobj211137* s);
N_NIMCALL(void, close_211597)(asyncscgistateobj211137* s);
STRING_LITERAL(TMP863, "\',\' after netstring expected", 28);
STRING_LITERAL(TMP864, "could not read all data", 23);
STRING_LITERAL(TMP865, "could not open socket", 21);
STRING_LITERAL(TMP868, "\':\' after length expected", 25);
STRING_LITERAL(TMP873, "SCGI", 4);
STRING_LITERAL(TMP874, "1", 1);
STRING_LITERAL(TMP875, "SCGI Version 1 expected", 23);
STRING_LITERAL(TMP877, "CONTENT_LENGTH", 14);
STRING_LITERAL(TMP880, "Status: 200 OK\015\012", 16);
STRING_LITERAL(TMP882, "Content-Type: $1\015\012\015\012", 20);
STRING_LITERAL(TMP884, "127.0.0.1", 9);
STRING_LITERAL(TMP885, "", 0);
STRING_LITERAL(TMP886, "Cannot read negative or zero length: ", 37);
extern TNimType NTI3231; /* IOError */
TNimType NTI211005; /* ScgiError */
TNimType NTI211012; /* ref ScgiError */
extern TFrame* frameptr_16442;
extern tgcheap47416 gch_47444;
extern TNimType NTI193809; /* Socket */
extern TNimType NTI202215; /* seq[Socket] */
extern TNimType NTI3211; /* RootObj */
TNimType NTI211131; /* ScgiState */
extern TNimType NTI108; /* int */
extern TNimType NTI173014; /* StringTableRef */
extern TNimType NTI149; /* string */
TNimType NTI211519; /* object */
extern TNimType NTI165711; /* range -1..0(int) */
TNimType NTI211148; /* AsyncClient:ObjectType */
extern TNimType NTI207213; /* AsyncSocket */
TNimType NTI211133; /* ClientMode */
TNimType NTI211135; /* AsyncClient */
TNimType NTI211137; /* AsyncScgiStateObj */
TNimType NTI211154; /* tuple[pointer, ref tuple[]] */
extern TNimType NTI153; /* pointer */
extern TNimType NTI161266; /* ref tuple[] */
extern TNimType NTI207209; /* Dispatcher */
TNimType NTI211139; /* AsyncScgiState */
TNimType NTI211530; /* ref object */
extern TNimType NTI207215; /* AsyncSocketObj */
TNimType NTI211572; /* object */
TNimType NTI211582; /* ref object */
N_NIMCALL(void, TMP859)(void* p, NI op) {
	scgierror211005* a;
	a = (scgierror211005*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, raisescgierror_211009)(NimStringDesc* msg) {
	scgierror211005* e;
	NimStringDesc* LOC1;
	nimfr("raiseScgiError", "scgi.nim")
	e = 0;
	nimln(43, "scgi.nim");
	e = (scgierror211005*) newObj((&NTI211012), sizeof(scgierror211005));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI211005);
	nimln(44, "scgi.nim");
	LOC1 = 0;
	LOC1 = (*e).Sup.Sup.Sup.message; (*e).Sup.Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(45, "scgi.nim");
	raiseException((Exception*)e, "ScgiError");
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, parseword_211037)(NimStringDesc* inp, NimStringDesc** outp, NI start) {
	NI result;
	NI TMP860;
	nimfr("parseWord", "scgi.nim")
	result = 0;
	nimln(48, "scgi.nim");
	result = start;
	{
		nimln(49, "scgi.nim");
		while (1) {
			nimln(49, "scgi.nim");
			nimln(49, "scgi.nim");
			if ((NU)(result) > (NU)(inp->Sup.len)) raiseIndexError();
			if (!!(((NU8)(inp->data[result]) == (NU8)(0)))) goto LA2;
			nimln(49, "scgi.nim");
			result = addInt(result, 1);
		} LA2: ;
	}
	nimln(50, "scgi.nim");
	nimln(50, "scgi.nim");
	nimln(50, "scgi.nim");
	TMP860 = subInt(result, 1);
	unsureAsgnRef((void**) (&(*outp)), copyStrLast(inp, start, (NI64)(TMP860)));
	popFrame();
	return result;
}

N_NIMCALL(stringtableobj173012*, parseheaders_211069)(NimStringDesc* s, NI l) {
	stringtableobj173012* result;
	TY185182 LOC1;
	NI i;
	nimfr("parseHeaders", "scgi.nim")
	result = 0;
	nimln(53, "scgi.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	result = nstnewStringTableWithTableConstr(LOC1, 0, ((NU8) 0));
	nimln(54, "scgi.nim");
	i = 0;
	{
		nimln(55, "scgi.nim");
		while (1) {
			NimStringDesc* key;
			NimStringDesc* val;
			NI LOC4;
			NI TMP861;
			NI LOC5;
			NI TMP862;
			nimln(55, "scgi.nim");
			if (!(i < l)) goto LA3;
			key = 0;
			val = 0;
			nimln(57, "scgi.nim");
			nimln(57, "scgi.nim");
			nimln(57, "scgi.nim");
			LOC4 = 0;
			LOC4 = parseword_211037(s, (&key), i);
			TMP861 = addInt(LOC4, 1);
			i = (NI64)(TMP861);
			nimln(58, "scgi.nim");
			nimln(58, "scgi.nim");
			nimln(58, "scgi.nim");
			LOC5 = 0;
			LOC5 = parseword_211037(s, (&val), i);
			TMP862 = addInt(LOC5, 1);
			i = (NI64)(TMP862);
			nimln(59, "scgi.nim");
			nstPut(result, key, val);
		} LA3: ;
	}
	nimln(60, "scgi.nim");
	{
		nimln(60, "scgi.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		if (!((NU8)(s->data[i]) == (NU8)(44))) goto LA8;
		nimln(60, "scgi.nim");
		i = addInt(i, 1);
	}
	goto LA6;
	LA8: ;
	{
		nimln(61, "scgi.nim");
		raisescgierror_211009(((NimStringDesc*) &TMP863));
	}
	LA6: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, recvchar_211117)(tsocketimpl193807* s) {
	NIM_CHAR result;
	NIM_CHAR c;
	nimfr("recvChar", "scgi.nim")
	result = 0;
	c = 0;
	nimln(65, "scgi.nim");
	{
		NI LOC3;
		nimln(65, "scgi.nim");
		nimln(65, "scgi.nim");
		LOC3 = 0;
		LOC3 = recv_201502(s, ((void*) ((&c))), 1);
		if (!(LOC3 == 1)) goto LA4;
		nimln(66, "scgi.nim");
		result = c;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, recvbuffer_211173)(scgistate211131* s, NI l) {
	nimfr("recvBuffer", "scgi.nim")
	nimln(101, "scgi.nim");
	{
		nimln(101, "scgi.nim");
		if (!((*s).Buflen < l)) goto LA3;
		nimln(102, "scgi.nim");
		(*s).Buflen = l;
		nimln(103, "scgi.nim");
		nimln(103, "scgi.nim");
		unsureAsgnRef((void**) (&(*s).Input), mnewString(l));
	}
	LA3: ;
	nimln(104, "scgi.nim");
	{
		NIM_BOOL LOC7;
		NI LOC9;
		nimln(104, "scgi.nim");
		LOC7 = 0;
		nimln(104, "scgi.nim");
		LOC7 = (0 < l);
		if (!(LOC7)) goto LA8;
		nimln(104, "scgi.nim");
		nimln(104, "scgi.nim");
		nimln(104, "scgi.nim");
		LOC9 = 0;
		LOC9 = recv_201502((*s).Client, ((void*) ((*s).Input->data)), l);
		LOC7 = !((LOC9 == l));
		LA8: ;
		if (!LOC7) goto LA10;
		nimln(105, "scgi.nim");
		raisescgierror_211009(((NimStringDesc*) &TMP864));
	}
	LA10: ;
	nimln(106, "scgi.nim");
	(*s).Input = setLengthStr((*s).Input, l);
	popFrame();
}

N_NIMCALL(void, open_211186)(scgistate211131* s, NU16 port, NimStringDesc* address, NIM_BOOL reuseaddr) {
	nimfr("open", "scgi.nim")
	nimln(111, "scgi.nim");
	(*s).Buflen = 4000;
	nimln(112, "scgi.nim");
	nimln(112, "scgi.nim");
	unsureAsgnRef((void**) (&(*s).Input), mnewString((*s).Buflen));
	nimln(114, "scgi.nim");
	unsureAsgnRef((void**) (&(*s).Server), socket_194804(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE));
	nimln(115, "scgi.nim");
	{
		NI32 LOC5;
		nimln(115, "scgi.nim");
		if (!((*s).Server == NIM_NIL)) goto LA3;
		nimln(115, "scgi.nim");
		nimln(115, "scgi.nim");
		LOC5 = 0;
		LOC5 = oslasterror_123041();
		raiseoserror_123009(LOC5);
	}
	LA3: ;
	nimln(116, "scgi.nim");
	unsureAsgnRef((void**) (&(*s).Client), (tsocketimpl193807*) newObj((&NTI193809), sizeof(tsocketimpl193807)));
	nimln(117, "scgi.nim");
	{
		nimln(117, "scgi.nim");
		if (!((*s).Server == NIM_NIL)) goto LA8;
		nimln(117, "scgi.nim");
		raisescgierror_211009(((NimStringDesc*) &TMP865));
	}
	LA8: ;
	nimln(119, "scgi.nim");
	{
		if (!reuseaddr) goto LA12;
		nimln(120, "scgi.nim");
		setsockopt_199292((*s).Server, ((NU8) 6), NIM_TRUE, SOL_SOCKET);
	}
	LA12: ;
	nimln(121, "scgi.nim");
	bindaddr_195974((*s).Server, port, address);
	nimln(122, "scgi.nim");
	listen_195809((*s).Server, SOMAXCONN);
	popFrame();
}

N_NIMCALL(void, close_211249)(scgistate211131* s) {
	nimfr("close", "scgi.nim")
	nimln(126, "scgi.nim");
	close_197678((*s).Server);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, next_211259)(scgistate211131* s, NI timeout) {
	NIM_BOOL result;
	TY202215* rsocks;
	TY208923 LOC1;
	nimfr("next", "scgi.nim")
	result = 0;
	nimln(132, "scgi.nim");
	nimln(132, "scgi.nim");
	rsocks = (TY202215*) newSeq((&NTI202215), 1);
	memset((void*)LOC1, 0, sizeof(LOC1));
	LOC1[0] = (*s).Server;
	asgnRefNoCycle((void**) (&rsocks->data[0]), LOC1[0]);
	nimln(133, "scgi.nim");
	{
		NIM_BOOL LOC4;
		NI LOC5;
		NI l;
		NI TMP872;
		NimStringDesc* LOC28;
		nimln(133, "scgi.nim");
		LOC4 = 0;
		nimln(133, "scgi.nim");
		nimln(133, "scgi.nim");
		LOC5 = 0;
		LOC5 = select_201301((&rsocks), timeout);
		LOC4 = (LOC5 == 1);
		if (!(LOC4)) goto LA6;
		nimln(133, "scgi.nim");
		nimln(133, "scgi.nim");
		LOC4 = (rsocks->Sup.len == 1);
		LA6: ;
		if (!LOC4) goto LA7;
		nimln(134, "scgi.nim");
		unsureAsgnRef((void**) (&(*s).Client), (tsocketimpl193807*) newObj((&NTI193809), sizeof(tsocketimpl193807)));
		nimln(135, "scgi.nim");
		accept_197601((*s).Server, &(*s).Client);
		nimln(136, "scgi.nim");
		l = 0;
		{
			nimln(137, "scgi.nim");
			while (1) {
				NIM_CHAR d;
				NI TMP869;
				NI TMP870;
				NI TMP871;
				nimln(138, "scgi.nim");
				d = recvchar_211117((*s).Client);
				nimln(139, "scgi.nim");
				{
					nimln(139, "scgi.nim");
					if (!((NU8)(d) == (NU8)(0))) goto LA13;
					nimln(140, "scgi.nim");
					close_197678((*s).Client);
					nimln(141, "scgi.nim");
					nimln(141, "scgi.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
				nimln(142, "scgi.nim");
				{
					nimln(142, "scgi.nim");
					nimln(142, "scgi.nim");
					if (!!((((NU8)(d)) >= ((NU8)(48)) && ((NU8)(d)) <= ((NU8)(57))))) goto LA17;
					nimln(143, "scgi.nim");
					{
						nimln(143, "scgi.nim");
						nimln(143, "scgi.nim");
						if (!!(((NU8)(d) == (NU8)(58)))) goto LA21;
						nimln(143, "scgi.nim");
						raisescgierror_211009(((NimStringDesc*) &TMP868));
					}
					LA21: ;
					nimln(144, "scgi.nim");
					goto LA9;
				}
				LA17: ;
				nimln(145, "scgi.nim");
				nimln(145, "scgi.nim");
				nimln(145, "scgi.nim");
				nimln(145, "scgi.nim");
				TMP869 = mulInt(l, 10);
				nimln(145, "scgi.nim");
				TMP870 = addInt((NI64)(TMP869), ((NI) (((NU8)(d)))));
				TMP871 = subInt((NI64)(TMP870), 48);
				l = (NI64)(TMP871);
			}
		} LA9: ;
		nimln(146, "scgi.nim");
		nimln(146, "scgi.nim");
		TMP872 = addInt(l, 1);
		recvbuffer_211173(s, (NI64)(TMP872));
		nimln(147, "scgi.nim");
		unsureAsgnRef((void**) (&(*s).Headers), parseheaders_211069((*s).Input, l));
		nimln(148, "scgi.nim");
		{
			NimStringDesc* LOC25;
			nimln(148, "scgi.nim");
			nimln(148, "scgi.nim");
			nimln(148, "scgi.nim");
			LOC25 = 0;
			LOC25 = nstGet((*s).Headers, ((NimStringDesc*) &TMP873));
			if (!!(eqStrings(LOC25, ((NimStringDesc*) &TMP874)))) goto LA26;
			nimln(148, "scgi.nim");
			raisescgierror_211009(((NimStringDesc*) &TMP875));
		}
		LA26: ;
		nimln(149, "scgi.nim");
		nimln(149, "scgi.nim");
		LOC28 = 0;
		LOC28 = nstGet((*s).Headers, ((NimStringDesc*) &TMP877));
		l = nsuParseInt(LOC28);
		nimln(150, "scgi.nim");
		recvbuffer_211173(s, l);
		nimln(151, "scgi.nim");
		nimln(151, "scgi.nim");
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA7: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, writestatusoktextcontent_211357)(tsocketimpl193807* c, NimStringDesc* contenttype) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("writeStatusOkTextContent", "scgi.nim")
	nimln(159, "scgi.nim");
	nimln(159, "scgi.nim");
	LOC1 = 0;
	nimln(160, "scgi.nim");
	LOC2 = 0;
	LOC2 = nsuFormatSingleElem(((NimStringDesc*) &TMP882), contenttype);
	LOC1 = rawNewString(LOC2->Sup.len + 16);
appendString(LOC1, ((NimStringDesc*) &TMP880));
appendString(LOC1, LOC2);
	send_204007(c, LOC1);
	popFrame();
}

N_NIMCALL(void, run_211367)(TY211369 handlerequest, NU16 port) {
	scgistate211131 s;
	NIM_BOOL stop;
	nimfr("run", "scgi.nim")
	memset((void*)(&s), 0, sizeof(s));
	s.Sup.m_type = (&NTI211131);
	nimln(167, "scgi.nim");
	open_211186((&s), port, ((NimStringDesc*) &TMP884), NIM_FALSE);
	nimln(168, "scgi.nim");
	stop = NIM_FALSE;
	{
		nimln(169, "scgi.nim");
		while (1) {
			nimln(169, "scgi.nim");
			if (!!(stop)) goto LA2;
			nimln(170, "scgi.nim");
			{
				NIM_BOOL LOC5;
				nimln(170, "scgi.nim");
				LOC5 = 0;
				LOC5 = next_211259((&s), -1);
				if (!LOC5) goto LA6;
				nimln(171, "scgi.nim");
				stop = handlerequest(s.Client, s.Input, s.Headers);
				nimln(172, "scgi.nim");
				close_197678(s.Client);
			}
			LA6: ;
		} LA2: ;
	}
	nimln(173, "scgi.nim");
	close_211249((&s));
	popFrame();
}

N_NIMCALL(NU8, recvbufferasync_211396)(asyncclientHEX3Aobjecttype211148* client, NI l) {
	NU8 result;
	NimStringDesc* data;
	NI ret;
	tsocketimpl193807* LOC7;
	nimfr("recvBufferAsync", "scgi.nim")
	result = 0;
	nimln(178, "scgi.nim");
	result = ((NU8) 1);
	nimln(179, "scgi.nim");
	data = copyString(((NimStringDesc*) &TMP885));
	nimln(180, "scgi.nim");
	{
		NimStringDesc* LOC5;
		NimStringDesc* LOC6;
		nimln(180, "scgi.nim");
		if (!(l < 1)) goto LA3;
		nimln(181, "scgi.nim");
		nimln(181, "scgi.nim");
		LOC5 = 0;
		nimln(181, "scgi.nim");
		LOC6 = 0;
		LOC6 = nimIntToStr(l);
		LOC5 = rawNewString(LOC6->Sup.len + 37);
appendString(LOC5, ((NimStringDesc*) &TMP886));
appendString(LOC5, LOC6);
		raisescgierror_211009(LOC5);
	}
	LA3: ;
	nimln(182, "scgi.nim");
	nimln(182, "scgi.nim");
	LOC7 = 0;
	LOC7 = getsocket_209046((*client).C);
	ret = recvasync_202324(LOC7, (&data), l);
	nimln(183, "scgi.nim");
	{
		NIM_BOOL LOC10;
		nimln(183, "scgi.nim");
		LOC10 = 0;
		nimln(183, "scgi.nim");
		LOC10 = (ret == 0);
		if (!(LOC10)) goto LA11;
		nimln(183, "scgi.nim");
		LOC10 = ((data) && (data)->Sup.len == 0);
		LA11: ;
		if (!LOC10) goto LA12;
		nimln(184, "scgi.nim");
		close_207625((*client).C);
		nimln(185, "scgi.nim");
		nimln(185, "scgi.nim");
		result = ((NU8) 2);
		goto BeforeRet;
	}
	LA12: ;
	nimln(186, "scgi.nim");
	{
		nimln(186, "scgi.nim");
		if (!(ret == -1)) goto LA16;
		nimln(187, "scgi.nim");
		nimln(187, "scgi.nim");
		result = ((NU8) 3);
		goto BeforeRet;
	}
	LA16: ;
	nimln(188, "scgi.nim");
	(*client).Input = resizeString((*client).Input, data->Sup.len + 0);
appendString((*client).Input, data);
	nimln(189, "scgi.nim");
	{
		nimln(189, "scgi.nim");
		if (!(ret == l)) goto LA20;
		nimln(190, "scgi.nim");
		nimln(190, "scgi.nim");
		result = ((NU8) 0);
		goto BeforeRet;
	}
	LA20: ;
	BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, HEX3Aanonymous_211414)(asyncsocketobj207215* s) {
	nimfr(":anonymous", "scgi.nim")
	nimln(196, "scgi.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC6;
		nimln(196, "scgi.nim");
		LOC3 = 0;
		nimln(196, "scgi.nim");
		nimln(196, "scgi.nim");
		LOC4 = 0;
		LOC4 = isclosed_209113(s);
		LOC3 = !(LOC4);
		if (!(LOC3)) goto LA5;
		nimln(196, "scgi.nim");
		nimln(196, "scgi.nim");
		LOC6 = 0;
		LOC6 = issenddatabuffered_209132(s);
		LOC3 = !(LOC6);
		LA5: ;
		if (!LOC3) goto LA7;
		nimln(197, "scgi.nim");
		close_207625(s);
		nimln(198, "scgi.nim");
		delhandlewrite_209155(s);
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(void, checkclosesocket_211411)(asyncclientHEX3Aobjecttype211148* client) {
	nimfr("checkCloseSocket", "scgi.nim")
	nimln(193, "scgi.nim");
	{
		NIM_BOOL LOC3;
		nimln(193, "scgi.nim");
		nimln(193, "scgi.nim");
		LOC3 = 0;
		LOC3 = isclosed_209113((*client).C);
		if (!!(LOC3)) goto LA4;
		nimln(194, "scgi.nim");
		{
			NIM_BOOL LOC8;
			TY207246 LOC11;
			nimln(194, "scgi.nim");
			LOC8 = 0;
			LOC8 = issenddatabuffered_209132((*client).C);
			if (!LOC8) goto LA9;
			nimln(195, "scgi.nim");
			memset((void*)(&LOC11), 0, sizeof(LOC11));
			LOC11.ClPrc = ((TMP887) (HEX3Aanonymous_211414)); LOC11.ClEnv = NIM_NIL;
			sethandlewrite_209142((*client).C, LOC11);
		}
		goto LA6;
		LA9: ;
		{
			nimln(199, "scgi.nim");
			close_207625((*client).C);
		}
		LA6: ;
	}
	LA4: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_49067)(tcell45335* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49829)(tcell45335* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_46071((&gch_47444.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51425)(tcell45335* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_49067(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49829(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_51004)(tcell45335* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_49067(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49829(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45335* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_49046(src);
		incref_51425(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45335* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_49046((*dest));
		decref_51004(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, handleclientread_211426)(asyncclientHEX3Aobjecttype211148* client, asyncscgistateobj211137* s) {
	nimfr("handleClientRead", "scgi.nim")
	nimln(202, "scgi.nim");
	switch ((*client).Mode) {
	case ((NU8) 0):
	{
		{
			nimln(204, "scgi.nim");
			while (1) {
				NimStringDesc* d;
				NI ret;
				tsocketimpl193807* LOC4;
				NI TMP888;
				NI TMP889;
				NI TMP890;
				nimln(205, "scgi.nim");
				d = copyString(((NimStringDesc*) &TMP885));
				nimln(206, "scgi.nim");
				nimln(206, "scgi.nim");
				LOC4 = 0;
				LOC4 = getsocket_209046((*client).C);
				ret = recvasync_202324(LOC4, (&d), 1);
				nimln(207, "scgi.nim");
				{
					NIM_BOOL LOC7;
					nimln(207, "scgi.nim");
					LOC7 = 0;
					nimln(207, "scgi.nim");
					LOC7 = ((d) && (d)->Sup.len == 0);
					if (!(LOC7)) goto LA8;
					nimln(207, "scgi.nim");
					LOC7 = (ret == 0);
					LA8: ;
					if (!LOC7) goto LA9;
					nimln(209, "scgi.nim");
					close_207625((*client).C);
					nimln(210, "scgi.nim");
					goto BeforeRet;
				}
				LA9: ;
				nimln(211, "scgi.nim");
				{
					nimln(211, "scgi.nim");
					if (!(ret == -1)) goto LA13;
					nimln(212, "scgi.nim");
					goto BeforeRet;
				}
				LA13: ;
				nimln(213, "scgi.nim");
				{
					nimln(213, "scgi.nim");
					nimln(213, "scgi.nim");
					if ((NU)(0) > (NU)(d->Sup.len)) raiseIndexError();
					if (!!((((NU8)(d->data[0])) >= ((NU8)(48)) && ((NU8)(d->data[0])) <= ((NU8)(57))))) goto LA17;
					nimln(214, "scgi.nim");
					{
						nimln(214, "scgi.nim");
						nimln(214, "scgi.nim");
						if ((NU)(0) > (NU)(d->Sup.len)) raiseIndexError();
						if (!!(((NU8)(d->data[0]) == (NU8)(58)))) goto LA21;
						nimln(214, "scgi.nim");
						raisescgierror_211009(((NimStringDesc*) &TMP868));
					}
					LA21: ;
					nimln(215, "scgi.nim");
					goto LA2;
				}
				LA17: ;
				nimln(216, "scgi.nim");
				nimln(216, "scgi.nim");
				nimln(216, "scgi.nim");
				nimln(216, "scgi.nim");
				TMP888 = mulInt((*client).Datalen, 10);
				nimln(216, "scgi.nim");
				if ((NU)(0) > (NU)(d->Sup.len)) raiseIndexError();
				TMP889 = addInt((NI64)(TMP888), ((NI) (((NU8)(d->data[0])))));
				TMP890 = subInt((NI64)(TMP889), 48);
				(*client).Datalen = (NI64)(TMP890);
			}
		} LA2: ;
		nimln(217, "scgi.nim");
		(*client).Mode = ((NU8) 1);
		nimln(218, "scgi.nim");
		handleclientread_211426(client, s);
	}
	break;
	case ((NU8) 1):
	{
		NU8 ret;
		NI TMP891;
		NI TMP892;
		nimln(220, "scgi.nim");
		nimln(220, "scgi.nim");
		nimln(220, "scgi.nim");
		TMP891 = addInt((*client).Datalen, 1);
		nimln(220, "scgi.nim");
		TMP892 = subInt((NI64)(TMP891), (*client).Input->Sup.len);
		ret = recvbufferasync_211396(client, (NI64)(TMP892));
		nimln(221, "scgi.nim");
		switch (ret) {
		case ((NU8) 0):
		{
			NI TMP893;
			NimStringDesc* LOC30;
			NI contentlen;
			NimStringDesc* LOC31;
			nimln(223, "scgi.nim");
			nimln(223, "scgi.nim");
			nimln(223, "scgi.nim");
			TMP893 = subInt((*client).Input->Sup.len, 1);
			asgnRef((void**) (&(*client).Headers), parseheaders_211069((*client).Input, (NI64)(TMP893)));
			nimln(224, "scgi.nim");
			{
				NimStringDesc* LOC27;
				nimln(224, "scgi.nim");
				nimln(224, "scgi.nim");
				nimln(224, "scgi.nim");
				LOC27 = 0;
				LOC27 = nstGet((*client).Headers, ((NimStringDesc*) &TMP873));
				if (!!(eqStrings(LOC27, ((NimStringDesc*) &TMP874)))) goto LA28;
				nimln(224, "scgi.nim");
				raisescgierror_211009(((NimStringDesc*) &TMP875));
			}
			LA28: ;
			nimln(225, "scgi.nim");
			LOC30 = 0;
			LOC30 = (*client).Input; (*client).Input = copyStringRC1(((NimStringDesc*) &TMP885));
			if (LOC30) nimGCunrefNoCycle(LOC30);
			nimln(227, "scgi.nim");
			nimln(227, "scgi.nim");
			LOC31 = 0;
			LOC31 = nstGet((*client).Headers, ((NimStringDesc*) &TMP877));
			contentlen = nsuParseInt(LOC31);
			nimln(228, "scgi.nim");
			{
				nimln(228, "scgi.nim");
				if (!(0 < contentlen)) goto LA34;
				nimln(229, "scgi.nim");
				(*client).Mode = ((NU8) 2);
			}
			goto LA32;
			LA34: ;
			{
				nimln(231, "scgi.nim");
				(*s).Handlerequest.ClEnv? (*s).Handlerequest.ClPrc((*client).C, (*client).Input, (*client).Headers, (*s).Handlerequest.ClEnv):((TMP894)((*s).Handlerequest.ClPrc))((*client).C, (*client).Input, (*client).Headers);
				nimln(232, "scgi.nim");
				checkclosesocket_211411(client);
			}
			LA32: ;
		}
		break;
		case ((NU8) 1):
		case ((NU8) 2):
		case ((NU8) 3):
		{
			nimln(233, "scgi.nim");
			goto BeforeRet;
		}
		break;
		}
	}
	break;
	case ((NU8) 2):
	{
		NI l;
		NimStringDesc* LOC39;
		NI LOC40;
		NI TMP895;
		nimln(235, "scgi.nim");
		nimln(235, "scgi.nim");
		nimln(235, "scgi.nim");
		nimln(235, "scgi.nim");
		LOC39 = 0;
		LOC39 = nstGet((*client).Headers, ((NimStringDesc*) &TMP877));
		LOC40 = 0;
		LOC40 = nsuParseInt(LOC39);
		nimln(235, "scgi.nim");
		TMP895 = subInt(LOC40, (*client).Input->Sup.len);
		l = (NI64)(TMP895);
		nimln(236, "scgi.nim");
		{
			NU8 ret;
			nimln(236, "scgi.nim");
			if (!(0 < l)) goto LA43;
			nimln(237, "scgi.nim");
			ret = recvbufferasync_211396(client, l);
			nimln(238, "scgi.nim");
			switch (ret) {
			case ((NU8) 0):
			{
				nimln(240, "scgi.nim");
				(*s).Handlerequest.ClEnv? (*s).Handlerequest.ClPrc((*client).C, (*client).Input, (*client).Headers, (*s).Handlerequest.ClEnv):((TMP896)((*s).Handlerequest.ClPrc))((*client).C, (*client).Input, (*client).Headers);
				nimln(241, "scgi.nim");
				checkclosesocket_211411(client);
			}
			break;
			case ((NU8) 1):
			case ((NU8) 2):
			case ((NU8) 3):
			{
				nimln(242, "scgi.nim");
				goto BeforeRet;
			}
			break;
			}
		}
		goto LA41;
		LA43: ;
		{
			nimln(244, "scgi.nim");
			(*s).Handlerequest.ClEnv? (*s).Handlerequest.ClPrc((*client).C, (*client).Input, (*client).Headers, (*s).Handlerequest.ClEnv):((TMP897)((*s).Handlerequest.ClPrc))((*client).C, (*client).Input, (*client).Headers);
			nimln(245, "scgi.nim");
			checkclosesocket_211411(client);
		}
		LA41: ;
	}
	break;
	}
	BeforeRet: ;
	popFrame();
}
N_NIMCALL(void, TMP903)(void* p, NI op) {
	asyncclientHEX3Aobjecttype211148* a;
	a = (asyncclientHEX3Aobjecttype211148*)p;
	nimGCvisit((void*)(*a).C, op);
	nimGCvisit((void*)(*a).Headers, op);
	nimGCvisit((void*)(*a).Input, op);
}
N_NIMCALL(void, TMP906)(void* p, NI op) {
	asyncscgistateobj211137* a;
	a = (asyncscgistateobj211137*)p;
	nimGCvisit((void*)(*a).Handlerequest.ClEnv, op);
	nimGCvisit((void*)(*a).Asyncserver, op);
	nimGCvisit((void*)(*a).Disp, op);
}
N_NIMCALL(void, TMP907)(void* p, NI op) {
	TY211519* a;
	a = (TY211519*)p;
	nimGCvisit((void*)(*a).Asyncclient211513, op);
	nimGCvisit((void*)(*a).S211484, op);
}

N_CLOSURE(void, HEX3Aanonymous_211514)(asyncsocketobj207215* sock, void* ClEnv) {
	TY211519* HEX3Aenvp_211525;
	nimfr(":anonymous", "scgi.nim")
	HEX3Aenvp_211525 = (TY211519*) ClEnv;
	nimln(255, "scgi.nim");
	handleclientread_211426((*HEX3Aenvp_211525).Asyncclient211513, (*HEX3Aenvp_211525).S211484);
	popFrame();
}

N_NIMCALL(void, handleaccept_211481)(asyncsocketobj207215* sock, asyncscgistateobj211137* s) {
	TY211519* HEX3Aenv_211529;
	asyncsocketobj207215* client;
	asyncclientHEX3Aobjecttype211148* LOC1;
	TY185182 LOC2;
	NimStringDesc* LOC3;
	TY207246 LOC4;
	delegateobj207205* LOC5;
	nimfr("handleAccept", "scgi.nim")
	HEX3Aenv_211529 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_211529 = (TY211519*) newObj((&NTI211530), sizeof(TY211519));
	nimln(248, "scgi.nim");
	asgnRef((void**) (&(*HEX3Aenv_211529).S211484), s);
	client = 0;
	nimln(249, "scgi.nim");
	client = (asyncsocketobj207215*) newObj((&NTI207213), sizeof(asyncsocketobj207215));
	(*client).Sup.m_type = (&NTI207215);
	nimln(250, "scgi.nim");
	accept_208626((*(*HEX3Aenv_211529).S211484).Asyncserver, &client);
	nimln(251, "scgi.nim");
	LOC1 = 0;
	LOC1 = (asyncclientHEX3Aobjecttype211148*) newObj((&NTI211135), sizeof(asyncclientHEX3Aobjecttype211148));
	asgnRef((void**) (&(*LOC1).C), client);
	(*LOC1).Mode = ((NU8) 0);
	(*LOC1).Datalen = 0;
	nimln(252, "scgi.nim");
	memset((void*)LOC2, 0, sizeof(LOC2));
	asgnRef((void**) (&(*LOC1).Headers), nstnewStringTableWithTableConstr(LOC2, 0, ((NU8) 0)));
	LOC3 = 0;
	LOC3 = (*LOC1).Input; (*LOC1).Input = copyStringRC1(((NimStringDesc*) &TMP885));
	if (LOC3) nimGCunrefNoCycle(LOC3);
	asgnRef((void**) (&(*HEX3Aenv_211529).Asyncclient211513), LOC1);
	nimln(253, "scgi.nim");
	memset((void*)(&LOC4), 0, sizeof(LOC4));
	LOC4.ClPrc = HEX3Aanonymous_211514; LOC4.ClEnv = HEX3Aenv_211529;
	asgnRef((void**) (&(*client).Handleread.ClEnv), LOC4.ClEnv);
	(*client).Handleread.ClPrc = LOC4.ClPrc;
	nimln(256, "scgi.nim");
	LOC5 = 0;
	LOC5 = register_208760((*(*HEX3Aenv_211529).S211484).Disp, client);
	popFrame();
}
N_NIMCALL(void, TMP909)(void* p, NI op) {
	TY211572* a;
	a = (TY211572*)p;
	nimGCvisit((void*)(*a).Cres211551, op);
}

static N_INLINE(void, nimGCunref)(void* p) {
	tcell45335* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(223, "gc.nim");
	nimln(223, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_49046(p);
	decref_51004(LOC1);
	popFrame();
}

N_CLOSURE(void, HEX3Aanonymous_211568)(asyncsocketobj207215* s, void* ClEnv) {
	TY211572* HEX3Aenvp_211578;
	nimfr(":anonymous", "scgi.nim")
	HEX3Aenvp_211578 = (TY211572*) ClEnv;
	nimln(270, "scgi.nim");
	handleaccept_211481(s, (*HEX3Aenvp_211578).Cres211551);
	popFrame();
}

N_NIMCALL(asyncscgistateobj211137*, open_211538)(TY211154 handlerequest, NU16 port, NimStringDesc* address, NIM_BOOL reuseaddr) {
	asyncscgistateobj211137* result;
	TY211572* HEX3Aenv_211581;
	TY207246 LOC1;
	nimfr("open", "scgi.nim")
	result = 0;
	HEX3Aenv_211581 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_211581 = (TY211572*) newObj((&NTI211582), sizeof(TY211572));
	nimln(268, "scgi.nim");
	if ((*HEX3Aenv_211581).Cres211551) nimGCunref((*HEX3Aenv_211581).Cres211551);
	(*HEX3Aenv_211581).Cres211551 = (asyncscgistateobj211137*) newObjRC1((&NTI211139), sizeof(asyncscgistateobj211137));
	nimln(269, "scgi.nim");
	asgnRef((void**) (&(*(*HEX3Aenv_211581).Cres211551).Asyncserver), asyncsocket_207400(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE));
	nimln(270, "scgi.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = HEX3Aanonymous_211568; LOC1.ClEnv = HEX3Aenv_211581;
	asgnRef((void**) (&(*(*(*HEX3Aenv_211581).Cres211551).Asyncserver).Handleaccept.ClEnv), LOC1.ClEnv);
	(*(*(*HEX3Aenv_211581).Cres211551).Asyncserver).Handleaccept.ClPrc = LOC1.ClPrc;
	nimln(271, "scgi.nim");
	{
		tsocketimpl193807* LOC6;
		if (!reuseaddr) goto LA4;
		nimln(272, "scgi.nim");
		nimln(272, "scgi.nim");
		LOC6 = 0;
		LOC6 = getsocket_209046((*(*HEX3Aenv_211581).Cres211551).Asyncserver);
		setsockopt_199292(LOC6, ((NU8) 6), NIM_TRUE, SOL_SOCKET);
	}
	LA4: ;
	nimln(273, "scgi.nim");
	bindaddr_208293((*(*HEX3Aenv_211581).Cres211551).Asyncserver, port, address);
	nimln(274, "scgi.nim");
	listen_208330((*(*HEX3Aenv_211581).Cres211551).Asyncserver);
	nimln(275, "scgi.nim");
	asgnRef((void**) (&(*(*HEX3Aenv_211581).Cres211551).Handlerequest.ClEnv), handlerequest.ClEnv);
	(*(*HEX3Aenv_211581).Cres211551).Handlerequest.ClPrc = handlerequest.ClPrc;
	nimln(276, "scgi.nim");
	result = (*HEX3Aenv_211581).Cres211551;
	popFrame();
	return result;
}

N_NIMCALL(delegateobj207205*, register_211586)(dispatcherobj207211* d, asyncscgistateobj211137* s) {
	delegateobj207205* result;
	nimfr("register", "scgi.nim")
	result = 0;
	nimln(280, "scgi.nim");
	result = register_208760(d, (*s).Asyncserver);
	nimln(281, "scgi.nim");
	asgnRef((void**) (&(*s).Disp), d);
	popFrame();
	return result;
}

N_NIMCALL(void, close_211597)(asyncscgistateobj211137* s) {
	nimfr("close", "scgi.nim")
	nimln(285, "scgi.nim");
	close_207625((*s).Asyncserver);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_scgiInit)(void) {
	nimfr("scgi", "scgi.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_scgiDatInit)(void) {
static TNimNode* TMP883[5];
static TNimNode* TMP898[3];
static TNimNode* TMP899[5];
static TNimNode* TMP900[3];
NI TMP902;
static char* NIM_CONST TMP901[3] = {
"ClientReadChar", 
"ClientReadHeaders", 
"ClientReadContent"};
static TNimNode* TMP904[3];
static TNimNode* TMP905[2];
static TNimNode* TMP908[2];
static TNimNode TMP784[31];
NTI211005.size = sizeof(scgierror211005);
NTI211005.kind = 17;
NTI211005.base = (&NTI3231);
TMP784[0].len = 0; TMP784[0].kind = 2;
NTI211005.node = &TMP784[0];
NTI211012.size = sizeof(scgierror211005*);
NTI211012.kind = 22;
NTI211012.base = (&NTI211005);
NTI211012.marker = TMP859;
NTI211131.size = sizeof(scgistate211131);
NTI211131.kind = 17;
NTI211131.base = (&NTI3211);
TMP883[0] = &TMP784[2];
TMP784[2].kind = 1;
TMP784[2].offset = offsetof(scgistate211131, Server);
TMP784[2].typ = (&NTI193809);
TMP784[2].name = "server";
TMP883[1] = &TMP784[3];
TMP784[3].kind = 1;
TMP784[3].offset = offsetof(scgistate211131, Buflen);
TMP784[3].typ = (&NTI108);
TMP784[3].name = "bufLen";
TMP883[2] = &TMP784[4];
TMP784[4].kind = 1;
TMP784[4].offset = offsetof(scgistate211131, Client);
TMP784[4].typ = (&NTI193809);
TMP784[4].name = "client";
TMP883[3] = &TMP784[5];
TMP784[5].kind = 1;
TMP784[5].offset = offsetof(scgistate211131, Headers);
TMP784[5].typ = (&NTI173014);
TMP784[5].name = "headers";
TMP883[4] = &TMP784[6];
TMP784[6].kind = 1;
TMP784[6].offset = offsetof(scgistate211131, Input);
TMP784[6].typ = (&NTI149);
TMP784[6].name = "input";
TMP784[1].len = 5; TMP784[1].kind = 2; TMP784[1].sons = &TMP883[0];
NTI211131.node = &TMP784[1];
NTI211519.size = sizeof(TY211519);
NTI211519.kind = 18;
NTI211519.base = 0;
TMP898[0] = &TMP784[8];
TMP784[8].kind = 1;
TMP784[8].offset = offsetof(TY211519, HEX3Astate);
TMP784[8].typ = (&NTI165711);
TMP784[8].name = ":state";
TMP898[1] = &TMP784[9];
NTI211148.size = sizeof(asyncclientHEX3Aobjecttype211148);
NTI211148.kind = 18;
NTI211148.base = 0;
TMP899[0] = &TMP784[11];
TMP784[11].kind = 1;
TMP784[11].offset = offsetof(asyncclientHEX3Aobjecttype211148, C);
TMP784[11].typ = (&NTI207213);
TMP784[11].name = "c";
TMP899[1] = &TMP784[12];
NTI211133.size = sizeof(NU8);
NTI211133.kind = 14;
NTI211133.base = 0;
NTI211133.flags = 3;
for (TMP902 = 0; TMP902 < 3; TMP902++) {
TMP784[TMP902+13].kind = 1;
TMP784[TMP902+13].offset = TMP902;
TMP784[TMP902+13].name = TMP901[TMP902];
TMP900[TMP902] = &TMP784[TMP902+13];
}
TMP784[16].len = 3; TMP784[16].kind = 2; TMP784[16].sons = &TMP900[0];
NTI211133.node = &TMP784[16];
TMP784[12].kind = 1;
TMP784[12].offset = offsetof(asyncclientHEX3Aobjecttype211148, Mode);
TMP784[12].typ = (&NTI211133);
TMP784[12].name = "mode";
TMP899[2] = &TMP784[17];
TMP784[17].kind = 1;
TMP784[17].offset = offsetof(asyncclientHEX3Aobjecttype211148, Datalen);
TMP784[17].typ = (&NTI108);
TMP784[17].name = "dataLen";
TMP899[3] = &TMP784[18];
TMP784[18].kind = 1;
TMP784[18].offset = offsetof(asyncclientHEX3Aobjecttype211148, Headers);
TMP784[18].typ = (&NTI173014);
TMP784[18].name = "headers";
TMP899[4] = &TMP784[19];
TMP784[19].kind = 1;
TMP784[19].offset = offsetof(asyncclientHEX3Aobjecttype211148, Input);
TMP784[19].typ = (&NTI149);
TMP784[19].name = "input";
TMP784[10].len = 5; TMP784[10].kind = 2; TMP784[10].sons = &TMP899[0];
NTI211148.node = &TMP784[10];
NTI211135.size = sizeof(asyncclientHEX3Aobjecttype211148*);
NTI211135.kind = 22;
NTI211135.base = (&NTI211148);
NTI211135.marker = TMP903;
TMP784[9].kind = 1;
TMP784[9].offset = offsetof(TY211519, Asyncclient211513);
TMP784[9].typ = (&NTI211135);
TMP784[9].name = "asyncClient211513";
TMP898[2] = &TMP784[20];
NTI211137.size = sizeof(asyncscgistateobj211137);
NTI211137.kind = 18;
NTI211137.base = 0;
TMP904[0] = &TMP784[22];
NTI211154.size = sizeof(TY161264);
NTI211154.kind = 18;
NTI211154.base = 0;
NTI211154.flags = 2;
TMP905[0] = &TMP784[24];
TMP784[24].kind = 1;
TMP784[24].offset = offsetof(TY161264, Field0);
TMP784[24].typ = (&NTI153);
TMP784[24].name = "Field0";
TMP905[1] = &TMP784[25];
TMP784[25].kind = 1;
TMP784[25].offset = offsetof(TY161264, Field1);
TMP784[25].typ = (&NTI161266);
TMP784[25].name = "Field1";
TMP784[23].len = 2; TMP784[23].kind = 2; TMP784[23].sons = &TMP905[0];
NTI211154.node = &TMP784[23];
TMP784[22].kind = 1;
TMP784[22].offset = offsetof(asyncscgistateobj211137, Handlerequest);
TMP784[22].typ = (&NTI211154);
TMP784[22].name = "handleRequest";
TMP904[1] = &TMP784[26];
TMP784[26].kind = 1;
TMP784[26].offset = offsetof(asyncscgistateobj211137, Asyncserver);
TMP784[26].typ = (&NTI207213);
TMP784[26].name = "asyncServer";
TMP904[2] = &TMP784[27];
TMP784[27].kind = 1;
TMP784[27].offset = offsetof(asyncscgistateobj211137, Disp);
TMP784[27].typ = (&NTI207209);
TMP784[27].name = "disp";
TMP784[21].len = 3; TMP784[21].kind = 2; TMP784[21].sons = &TMP904[0];
NTI211137.node = &TMP784[21];
NTI211139.size = sizeof(asyncscgistateobj211137*);
NTI211139.kind = 22;
NTI211139.base = (&NTI211137);
NTI211139.marker = TMP906;
TMP784[20].kind = 1;
TMP784[20].offset = offsetof(TY211519, S211484);
TMP784[20].typ = (&NTI211139);
TMP784[20].name = "s211484";
TMP784[7].len = 3; TMP784[7].kind = 2; TMP784[7].sons = &TMP898[0];
NTI211519.node = &TMP784[7];
NTI211530.size = sizeof(TY211519*);
NTI211530.kind = 22;
NTI211530.base = (&NTI211519);
NTI211530.marker = TMP907;
NTI211572.size = sizeof(TY211572);
NTI211572.kind = 18;
NTI211572.base = 0;
TMP908[0] = &TMP784[29];
TMP784[29].kind = 1;
TMP784[29].offset = offsetof(TY211572, HEX3Astate);
TMP784[29].typ = (&NTI165711);
TMP784[29].name = ":state";
TMP908[1] = &TMP784[30];
TMP784[30].kind = 1;
TMP784[30].offset = offsetof(TY211572, Cres211551);
TMP784[30].typ = (&NTI211139);
TMP784[30].name = "cres211551";
TMP784[28].len = 2; TMP784[28].kind = 2; TMP784[28].sons = &TMP908[0];
NTI211572.node = &TMP784[28];
NTI211582.size = sizeof(TY211572*);
NTI211582.kind = 22;
NTI211582.base = (&NTI211572);
NTI211582.marker = TMP909;
}

