/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/todo.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/todo.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <setjmp.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY231036 TY231036;
typedef struct todoitem231005 todoitem231005;
typedef struct tcell45335 tcell45335;
typedef struct TNimType TNimType;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct settingsHEX3Aobjecttype222053 settingsHEX3Aobjecttype222053;
typedef struct TNimNode TNimNode;
typedef struct futureHEX3Aobjecttype222048 futureHEX3Aobjecttype222048;
typedef struct requestHEX3Aobjecttype222060 requestHEX3Aobjecttype222060;
typedef struct responseHEX3Aobjecttype222078 responseHEX3Aobjecttype222078;
typedef struct TY232414 TY232414;
typedef struct futurebaseHEX3Aobjecttype160014 futurebaseHEX3Aobjecttype160014;
typedef struct TY214399 TY214399;
typedef struct stringtableobj173012 stringtableobj173012;
typedef struct asyncsocketdesc175202 asyncsocketdesc175202;
typedef struct TY222080 TY222080;
typedef struct TY109352 TY109352;
typedef struct table220013 table220013;
typedef struct keyvaluepairseq220016 keyvaluepairseq220016;
typedef struct keyvaluepair220019 keyvaluepair220019;
typedef struct TY220007 TY220007;
typedef struct pattern214014 pattern214014;
typedef struct node214012 node214012;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
typedef struct mimedb213010 mimedb213010;
typedef struct keyvaluepairseq173010 keyvaluepairseq173010;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  todoitem231005  {
NI Id;
NimStringDesc* Description;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
typedef struct {
N_NIMCALL_PTR(futurebaseHEX3Aobjecttype160014*, ClPrc) (void* ClEnv);
void* ClEnv;
} TY170666;
struct TY214399 {
NIM_BOOL Field0;
stringtableobj173012* Field1;
};
struct  TY232414  {
NI HEX3Astate;
responseHEX3Aobjecttype222078* Response232207;
requestHEX3Aobjecttype222060* Request232206;
futureHEX3Aobjecttype222048* Retfuture232202;
TY170666 Nameitervar232368;
NIM_BOOL Result232221;
TY214399 Patternmatchret232134;
TY214399 Patternmatchret232137;
TY214399 Patternmatchret232143;
TY214399 Patternmatchret232140;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY222080 {
NU8 Field0;
NU8 Field1;
stringtableobj173012* Field2;
NimStringDesc* Field3;
};
struct  responseHEX3Aobjecttype222078  {
asyncsocketdesc175202* Client;
TY222080 Data;
};
struct TY109352 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef TY109352 TY185182[1];
typedef NimStringDesc* TY190117[20];
struct TY220007 {
stringtableobj173012* Field0;
NimStringDesc* Field1;
};
struct keyvaluepair220019 {
NU8 Field0;
NimStringDesc* Field1;
TY220007 Field2;
};
struct  table220013  {
keyvaluepairseq220016* Data;
NI Counter;
};
struct  requestHEX3Aobjecttype222060  {
stringtableobj173012* Params;
TY190117 Matches;
NimStringDesc* Body;
stringtableobj173012* Headers;
table220013 Formdata;
NI Port;
NimStringDesc* Host;
NimStringDesc* Appname;
NimStringDesc* Pathinfo;
NIM_BOOL Secure;
NimStringDesc* Path;
stringtableobj173012* Cookies;
NimStringDesc* Ip;
NU8 Reqmeth;
settingsHEX3Aobjecttype222053* Settings;
};
struct  node214012  {
NU8 Typ;
NimStringDesc* Text;
NIM_BOOL Optional;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY15009;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY15009 raiseAction;
};
typedef N_CLOSURE_PTR(futurebaseHEX3Aobjecttype160014*, TMP2068) (void);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY160015;
struct  futurebaseHEX3Aobjecttype160014  {
  TNimObject Sup;
TY160015 Cb;
NIM_BOOL Finished;
Exception* Error;
NimStringDesc* Errorstacktrace;
NimStringDesc* Stacktrace;
NI Id;
NimStringDesc* Fromproc;
};
struct  futureHEX3Aobjecttype222048  {
  futurebaseHEX3Aobjecttype160014 Sup;
NIM_BOOL Value;
};
typedef N_CLOSURE_PTR(void, TMP2070) (void);
typedef N_NIMCALL_PTR(futureHEX3Aobjecttype222048*, TY225253) (requestHEX3Aobjecttype222060* request, responseHEX3Aobjecttype222078* response);
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  mimedb213010  {
stringtableobj173012* Mimes;
};
struct  settingsHEX3Aobjecttype222053  {
NimStringDesc* Staticdir;
NimStringDesc* Appname;
mimedb213010 Mimes;
NU16 Port;
};
struct  stringtableobj173012  {
  TNimObject Sup;
NI Counter;
keyvaluepairseq173010* Data;
NU8 Mode;
};
typedef NIM_CHAR TY175208[4001];
struct  asyncsocketdesc175202  {
int Fd;
NIM_BOOL Closed;
NIM_BOOL Isbuffered;
union {
struct {TY175208 Buffer;
NI Currpos;
NI Buflen;
} S1;
} isbufferedU;
NIM_BOOL Isssl;
union {
} issslU;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY231036 {
  TGenericSeq Sup;
  todoitem231005 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq220016 {
  TGenericSeq Sup;
  keyvaluepair220019 data[SEQ_DECL_SIZE];
};
struct pattern214014 {
  TGenericSeq Sup;
  node214012 data[SEQ_DECL_SIZE];
};
struct keyvaluepairseq173010 {
  TGenericSeq Sup;
  TY109352 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, add_232004)(NimStringDesc* description);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, remove_232044)(NimStringDesc* id);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(settingsHEX3Aobjecttype222053*, newsettings_225237)(NU16 port, NimStringDesc* staticdir, NimStringDesc* appname);
N_NIMCALL(NimStringDesc*, HEX2F_125499)(NimStringDesc* head, NimStringDesc* tail);
N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51425)(tcell45335* c);
static N_INLINE(NIM_BOOL, canbecycleroot_49067)(tcell45335* c);
static N_INLINE(void, rtladdcycleroot_49829)(tcell45335* c);
N_NOINLINE(void, incl_46071)(tcellset45347* s, tcell45335* cell);
static N_INLINE(void, decref_51004)(tcell45335* c);
N_NIMCALL(futureHEX3Aobjecttype222048*, match_232204)(requestHEX3Aobjecttype222060* request, responseHEX3Aobjecttype222078* response);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP2058)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(futureHEX3Aobjecttype222048*, newfuture_222132)(NimStringDesc* fromproc_222136);
N_CLOSURE(futurebaseHEX3Aobjecttype160014*, matchiter_232203)(void* ClEnv);
N_NIMCALL(stringtableobj173012*, nstnewStringTableWithTableConstr)(TY109352* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(void, match_214395)(pattern214014* pattern, NimStringDesc* s, TY214399* Result);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, copyparams_225553)(requestHEX3Aobjecttype222060* request, stringtableobj173012* params);
N_NIMCALL(void, nstPut)(stringtableobj173012* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NimStringDesc*, index_231079)(void);
N_NIMCALL(NIM_BOOL, checkaction_225616)(responseHEX3Aobjecttype222078* response);
N_NIMCALL(void, complete_222256)(futureHEX3Aobjecttype222048* future_222262, NIM_BOOL val_222265);
N_NIMCALL(NimStringDesc*, nstGet)(stringtableobj173012* t, NimStringDesc* key);
N_CLOSURE(void, cb_232371)(void* ClEnv);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished_171246)(TY170666 x_171250);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(void, callbackHEX3D_160849)(futurebaseHEX3Aobjecttype160014* future, TY160015 cb);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, fail_223203)(futureHEX3Aobjecttype222048* future_223209, Exception* error_223212);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, serve_225251)(TY225253 match, settingsHEX3Aobjecttype222053* settings);
N_NIMCALL(void, runforever_171443)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rawsocketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asynchttpserverInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asynchttpserverDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_socketsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_socketsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncioInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncioDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_scgiInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_scgiDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cookiesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cookiesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mimetypesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_patternsInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_patternsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_htmlgenInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_htmlgenDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_errorpagesInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_errorpagesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cgiInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cgiDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_utilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_utilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_jesterInit)(void);
NIM_EXTERNC N_NOINLINE(void, jester_jesterDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, templates_annotateInit)(void);
NIM_EXTERNC N_NOINLINE(void, templates_annotateDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, templates_templatesInit)(void);
NIM_EXTERNC N_NOINLINE(void, templates_templatesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_masterInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_masterDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_viewsInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_viewsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, todoInit)(void);
NIM_EXTERNC N_NOINLINE(void, todoDatInit)(void);
STRING_LITERAL(TMP2054, "public", 6);
STRING_LITERAL(TMP2055, "", 0);
STRING_LITERAL(TMP2059, "match", 5);
STRING_LITERAL(TMP2060, "/", 1);
STRING_LITERAL(TMP2061, "Content-Type", 12);
STRING_LITERAL(TMP2062, "text/html", 9);
STRING_LITERAL(TMP2063, "/add", 4);
STRING_LITERAL(TMP2064, "/remove/", 8);
STRING_LITERAL(TMP2065, "id", 2);
STRING_LITERAL(TMP2066, "newItem", 7);
STRING_LITERAL(TMP2069, "retFuture.(asyncdispatch.finished|system.finished|...) Async pr"
"ocedure\'s (match) return Future was not finished.", 112);
extern TY231036* todoitems_231065;
extern NI nextid_231011;
extern TFrame* frameptr_16442;
extern tgcheap47416 gch_47444;
settingsHEX3Aobjecttype222053* settings_232201;
TNimType NTI232414; /* object */
extern TNimType NTI165711; /* range -1..0(int) */
extern TNimType NTI222031; /* Response */
extern TNimType NTI222029; /* Request */
extern TNimType NTI222047; /* Future */
extern TNimType NTI170666; /* iterator (): FutureBase{.closure, gcsafe, locks: <unknown>.} */
extern TNimType NTI138; /* bool */
extern TNimType NTI214399; /* tuple[matched: bool, params: StringTableRef] */
TNimType NTI232432; /* ref object */
extern TNimType NTI214014; /* Pattern */
extern TSafePoint* exchandler_16443;
extern Exception* currexception_16445;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45335* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_49046(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50604(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, add_232004)(NimStringDesc* description) {
	todoitem231005 LOC1;
	NimStringDesc* LOC2;
	nimfr("add", "todo.nim")
	nimln(10, "todo.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Id = nextid_231011;
	LOC1.Description = copyString(description);
	todoitems_231065 = (TY231036*) incrSeq(&(todoitems_231065)->Sup, sizeof(todoitem231005));
	todoitems_231065->data[todoitems_231065->Sup.len-1].Id = LOC1.Id;
	LOC2 = 0;
	LOC2 = todoitems_231065->data[todoitems_231065->Sup.len-1].Description; todoitems_231065->data[todoitems_231065->Sup.len-1].Description = copyStringRC1(LOC1.Description);
	if (LOC2) nimGCunrefNoCycle(LOC2);
	nimln(14, "todo.nim");
	nextid_231011 = addInt(nextid_231011, 1);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (NI64)((*a).Sup.len * 1));
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	BeforeRet: ;
	return result;
}

N_NIMCALL(void, remove_232044)(NimStringDesc* id) {
	NI pos_232048;
	nimfr("remove", "todo.nim")
	nimln(282, "sequtils.nim");
	pos_232048 = 0;
	{
		NI i_232050;
		NI HEX3Atmp_232113;
		NI res_232116;
		i_232050 = 0;
		HEX3Atmp_232113 = 0;
		nimln(283, "sequtils.nim");
		nimln(283, "sequtils.nim");
		nimln(283, "sequtils.nim");
		HEX3Atmp_232113 = subInt(todoitems_231065->Sup.len, 1);
		nimln(1576, "system.nim");
		res_232116 = 0;
		{
			nimln(1577, "system.nim");
			while (1) {
				todoitem231005 it;
				nimln(1577, "system.nim");
				if (!(res_232116 <= HEX3Atmp_232113)) goto LA3;
				nimln(1576, "system.nim");
				i_232050 = res_232116;
				memset((void*)(&it), 0, sizeof(it));
				nimln(284, "sequtils.nim");
				if ((NU)(i_232050) >= (NU)(todoitems_231065->Sup.len)) raiseIndexError();
				it.Id = todoitems_231065->data[i_232050].Id;
				it.Description = todoitems_231065->data[i_232050].Description;
				nimln(285, "sequtils.nim");
				{
					NimStringDesc* LOC6;
					nimln(17, "todo.nim");
					nimln(17, "todo.nim");
					nimln(17, "todo.nim");
					LOC6 = 0;
					LOC6 = nimIntToStr(it.Id);
					if (!!(eqStrings(LOC6, id))) goto LA7;
					nimln(286, "sequtils.nim");
					{
						NimStringDesc* LOC13;
						nimln(286, "sequtils.nim");
						nimln(286, "sequtils.nim");
						if (!!((pos_232048 == i_232050))) goto LA11;
						nimln(287, "sequtils.nim");
						if ((NU)(pos_232048) >= (NU)(todoitems_231065->Sup.len)) raiseIndexError();
						if ((NU)(i_232050) >= (NU)(todoitems_231065->Sup.len)) raiseIndexError();
						todoitems_231065->data[pos_232048].Id = todoitems_231065->data[i_232050].Id;
						LOC13 = 0;
						LOC13 = todoitems_231065->data[pos_232048].Description; todoitems_231065->data[pos_232048].Description = copyStringRC1(todoitems_231065->data[i_232050].Description);
						if (LOC13) nimGCunrefNoCycle(LOC13);
					}
					LA11: ;
					nimln(288, "sequtils.nim");
					pos_232048 = addInt(pos_232048, 1);
				}
				LA7: ;
				nimln(1579, "system.nim");
				res_232116 = addInt(res_232116, 1);
			} LA3: ;
		}
	}
	nimln(289, "sequtils.nim");
	todoitems_231065 = (TY231036*) setLengthSeq(&(todoitems_231065)->Sup, sizeof(todoitem231005), pos_232048);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_49067)(tcell45335* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49829)(tcell45335* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_46071((&gch_47444.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51425)(tcell45335* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU64)((*c).Refcount) + (NU64)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_49067(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49829(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_51004)(tcell45335* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_49067(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49829(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45335* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_49046(src);
		incref_51425(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45335* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_49046((*dest));
		decref_51004(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, TMP2058)(void* p, NI op) {
	TY232414* a;
	a = (TY232414*)p;
	nimGCvisit((void*)(*a).Response232207, op);
	nimGCvisit((void*)(*a).Request232206, op);
	nimGCvisit((void*)(*a).Retfuture232202, op);
	nimGCvisit((void*)(*a).Nameitervar232368.ClEnv, op);
	nimGCvisit((void*)(*a).Patternmatchret232134.Field1, op);
	nimGCvisit((void*)(*a).Patternmatchret232137.Field1, op);
	nimGCvisit((void*)(*a).Patternmatchret232143.Field1, op);
	nimGCvisit((void*)(*a).Patternmatchret232140.Field1, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_CLOSURE(futurebaseHEX3Aobjecttype160014*, matchiter_232203)(void* ClEnv) {
	futurebaseHEX3Aobjecttype160014* result_232220;
	TY232414* HEX3Aenvp_232420;
	TY185182 LOC1;
	NimStringDesc* LOC2;
	nimfr("matchIter", "asyncdispatch.nim")
	result_232220 = 0;
	HEX3Aenvp_232420 = (TY232414*) ClEnv;
	switch ((*HEX3Aenvp_232420).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	}
	STATE0: ;
	nimln(546, "jester.nim");
	(*(*HEX3Aenvp_232420).Response232207).Data.Field0 = ((NU8) 3);
	nimln(547, "jester.nim");
	(*(*HEX3Aenvp_232420).Response232207).Data.Field1 = ((NU8) 2);
	nimln(548, "jester.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	asgnRef((void**) (&(*(*HEX3Aenvp_232420).Response232207).Data.Field2), nstnewStringTableWithTableConstr(LOC1, 0, ((NU8) 0)));
	nimln(549, "jester.nim");
	LOC2 = 0;
	LOC2 = (*(*HEX3Aenvp_232420).Response232207).Data.Field3; (*(*HEX3Aenvp_232420).Response232207).Data.Field3 = copyStringRC1(((NimStringDesc*) &TMP2055));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	nimln(34, "views.nim");
	switch ((*(*HEX3Aenvp_232420).Request232206).Reqmeth) {
	case ((NU8) 0):
	{
		pattern214014* LOC4;
		node214012 LOC5;
		pattern214014* LOC16;
		node214012 LOC17;
		pattern214014* LOC28;
		node214012 LOC29;
		node214012 LOC30;
		nimln(22, "todo.nim");
		LOC4 = 0;
		LOC4 = (pattern214014*) newSeq((&NTI214014), 1);
		memset((void*)(&LOC5), 0, sizeof(LOC5));
		memset((void*)(&LOC5), 0, sizeof(LOC5));
		LOC5.Typ = ((NU8) 0);
		LOC5.Text = copyString(((NimStringDesc*) &TMP2060));
		LOC5.Optional = NIM_FALSE;
		LOC4->data[0].Typ = LOC5.Typ;
		asgnRefNoCycle((void**) (&LOC4->data[0].Text), LOC5.Text);
		LOC4->data[0].Optional = LOC5.Optional;
		match_214395(LOC4, (*(*HEX3Aenvp_232420).Request232206).Path, (&(*HEX3Aenvp_232420).Patternmatchret232134));
		{
			nimln(22, "todo.nim");
			{
				if (!(*HEX3Aenvp_232420).Patternmatchret232134.Field0) goto LA9;
				nimln(22, "todo.nim");
				copyparams_225553((*HEX3Aenvp_232420).Request232206, (*HEX3Aenvp_232420).Patternmatchret232134.Field1);
				nimln(307, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field0 = ((NU8) 0);
				nimln(308, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field1 = ((NU8) 2);
				nimln(309, "jester.nim");
				nstPut((*(*HEX3Aenvp_232420).Response232207).Data.Field2, ((NimStringDesc*) &TMP2061), ((NimStringDesc*) &TMP2062));
				nimln(310, "jester.nim");
				asgnRefNoCycle((void**) (&(*(*HEX3Aenvp_232420).Response232207).Data.Field3), index_231079());
				nimln(266, "macros.nim");
				{
					NIM_BOOL LOC13;
					nimln(266, "macros.nim");
					LOC13 = 0;
					LOC13 = checkaction_225616((*HEX3Aenvp_232420).Response232207);
					if (!LOC13) goto LA14;
					nimln(266, "macros.nim");
					complete_222256((*HEX3Aenvp_232420).Retfuture232202, NIM_TRUE);
					nimln(266, "macros.nim");
					(*HEX3Aenvp_232420).HEX3Astate = -1;
					nimln(266, "macros.nim");
					nimln(266, "macros.nim");
					result_232220 = NIM_NIL;
					goto BeforeRet;
				}
				LA14: ;
			}
			LA9: ;
		}
		nimln(23, "todo.nim");
		LOC16 = 0;
		LOC16 = (pattern214014*) newSeq((&NTI214014), 1);
		memset((void*)(&LOC17), 0, sizeof(LOC17));
		memset((void*)(&LOC17), 0, sizeof(LOC17));
		LOC17.Typ = ((NU8) 0);
		LOC17.Text = copyString(((NimStringDesc*) &TMP2063));
		LOC17.Optional = NIM_FALSE;
		LOC16->data[0].Typ = LOC17.Typ;
		asgnRefNoCycle((void**) (&LOC16->data[0].Text), LOC17.Text);
		LOC16->data[0].Optional = LOC17.Optional;
		match_214395(LOC16, (*(*HEX3Aenvp_232420).Request232206).Path, (&(*HEX3Aenvp_232420).Patternmatchret232137));
		{
			nimln(23, "todo.nim");
			{
				if (!(*HEX3Aenvp_232420).Patternmatchret232137.Field0) goto LA21;
				nimln(23, "todo.nim");
				copyparams_225553((*HEX3Aenvp_232420).Request232206, (*HEX3Aenvp_232420).Patternmatchret232137.Field1);
				nimln(307, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field0 = ((NU8) 0);
				nimln(308, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field1 = ((NU8) 2);
				nimln(309, "jester.nim");
				nstPut((*(*HEX3Aenvp_232420).Response232207).Data.Field2, ((NimStringDesc*) &TMP2061), ((NimStringDesc*) &TMP2062));
				nimln(310, "jester.nim");
				asgnRefNoCycle((void**) (&(*(*HEX3Aenvp_232420).Response232207).Data.Field3), index_231079());
				nimln(266, "macros.nim");
				{
					NIM_BOOL LOC25;
					nimln(266, "macros.nim");
					LOC25 = 0;
					LOC25 = checkaction_225616((*HEX3Aenvp_232420).Response232207);
					if (!LOC25) goto LA26;
					nimln(266, "macros.nim");
					complete_222256((*HEX3Aenvp_232420).Retfuture232202, NIM_TRUE);
					nimln(266, "macros.nim");
					(*HEX3Aenvp_232420).HEX3Astate = -1;
					nimln(266, "macros.nim");
					nimln(266, "macros.nim");
					result_232220 = NIM_NIL;
					goto BeforeRet;
				}
				LA26: ;
			}
			LA21: ;
		}
		nimln(29, "todo.nim");
		LOC28 = 0;
		LOC28 = (pattern214014*) newSeq((&NTI214014), 2);
		memset((void*)(&LOC29), 0, sizeof(LOC29));
		memset((void*)(&LOC29), 0, sizeof(LOC29));
		LOC29.Typ = ((NU8) 0);
		LOC29.Text = copyString(((NimStringDesc*) &TMP2064));
		LOC29.Optional = NIM_FALSE;
		LOC28->data[0].Typ = LOC29.Typ;
		asgnRefNoCycle((void**) (&LOC28->data[0].Text), LOC29.Text);
		LOC28->data[0].Optional = LOC29.Optional;
		memset((void*)(&LOC30), 0, sizeof(LOC30));
		memset((void*)(&LOC30), 0, sizeof(LOC30));
		LOC30.Typ = ((NU8) 1);
		LOC30.Text = copyString(((NimStringDesc*) &TMP2065));
		LOC30.Optional = NIM_FALSE;
		LOC28->data[1].Typ = LOC30.Typ;
		asgnRefNoCycle((void**) (&LOC28->data[1].Text), LOC30.Text);
		LOC28->data[1].Optional = LOC30.Optional;
		match_214395(LOC28, (*(*HEX3Aenvp_232420).Request232206).Path, (&(*HEX3Aenvp_232420).Patternmatchret232143));
		{
			nimln(31, "todo.nim");
			{
				NimStringDesc* LOC36;
				if (!(*HEX3Aenvp_232420).Patternmatchret232143.Field0) goto LA34;
				nimln(29, "todo.nim");
				copyparams_225553((*HEX3Aenvp_232420).Request232206, (*HEX3Aenvp_232420).Patternmatchret232143.Field1);
				nimln(30, "todo.nim");
				nimln(30, "todo.nim");
				LOC36 = 0;
				LOC36 = nstGet((*(*HEX3Aenvp_232420).Request232206).Params, ((NimStringDesc*) &TMP2065));
				remove_232044(LOC36);
				nimln(307, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field0 = ((NU8) 0);
				nimln(308, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field1 = ((NU8) 2);
				nimln(309, "jester.nim");
				nstPut((*(*HEX3Aenvp_232420).Response232207).Data.Field2, ((NimStringDesc*) &TMP2061), ((NimStringDesc*) &TMP2062));
				nimln(310, "jester.nim");
				asgnRefNoCycle((void**) (&(*(*HEX3Aenvp_232420).Response232207).Data.Field3), index_231079());
				nimln(266, "macros.nim");
				{
					NIM_BOOL LOC39;
					nimln(266, "macros.nim");
					LOC39 = 0;
					LOC39 = checkaction_225616((*HEX3Aenvp_232420).Response232207);
					if (!LOC39) goto LA40;
					nimln(266, "macros.nim");
					complete_222256((*HEX3Aenvp_232420).Retfuture232202, NIM_TRUE);
					nimln(266, "macros.nim");
					(*HEX3Aenvp_232420).HEX3Astate = -1;
					nimln(266, "macros.nim");
					nimln(266, "macros.nim");
					result_232220 = NIM_NIL;
					goto BeforeRet;
				}
				LA40: ;
			}
			LA34: ;
		}
	}
	break;
	case ((NU8) 1):
	{
		pattern214014* LOC43;
		node214012 LOC44;
		nimln(25, "todo.nim");
		LOC43 = 0;
		LOC43 = (pattern214014*) newSeq((&NTI214014), 1);
		memset((void*)(&LOC44), 0, sizeof(LOC44));
		memset((void*)(&LOC44), 0, sizeof(LOC44));
		LOC44.Typ = ((NU8) 0);
		LOC44.Text = copyString(((NimStringDesc*) &TMP2063));
		LOC44.Optional = NIM_FALSE;
		LOC43->data[0].Typ = LOC44.Typ;
		asgnRefNoCycle((void**) (&LOC43->data[0].Text), LOC44.Text);
		LOC43->data[0].Optional = LOC44.Optional;
		match_214395(LOC43, (*(*HEX3Aenvp_232420).Request232206).Path, (&(*HEX3Aenvp_232420).Patternmatchret232140));
		{
			nimln(27, "todo.nim");
			{
				NimStringDesc* LOC50;
				if (!(*HEX3Aenvp_232420).Patternmatchret232140.Field0) goto LA48;
				nimln(25, "todo.nim");
				copyparams_225553((*HEX3Aenvp_232420).Request232206, (*HEX3Aenvp_232420).Patternmatchret232140.Field1);
				nimln(26, "todo.nim");
				nimln(26, "todo.nim");
				LOC50 = 0;
				LOC50 = nstGet((*(*HEX3Aenvp_232420).Request232206).Params, ((NimStringDesc*) &TMP2066));
				add_232004(LOC50);
				nimln(307, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field0 = ((NU8) 0);
				nimln(308, "jester.nim");
				(*(*HEX3Aenvp_232420).Response232207).Data.Field1 = ((NU8) 2);
				nimln(309, "jester.nim");
				nstPut((*(*HEX3Aenvp_232420).Response232207).Data.Field2, ((NimStringDesc*) &TMP2061), ((NimStringDesc*) &TMP2062));
				nimln(310, "jester.nim");
				asgnRefNoCycle((void**) (&(*(*HEX3Aenvp_232420).Response232207).Data.Field3), index_231079());
				nimln(266, "macros.nim");
				{
					NIM_BOOL LOC53;
					nimln(266, "macros.nim");
					LOC53 = 0;
					LOC53 = checkaction_225616((*HEX3Aenvp_232420).Response232207);
					if (!LOC53) goto LA54;
					nimln(266, "macros.nim");
					complete_222256((*HEX3Aenvp_232420).Retfuture232202, NIM_TRUE);
					nimln(266, "macros.nim");
					(*HEX3Aenvp_232420).HEX3Astate = -1;
					nimln(266, "macros.nim");
					nimln(266, "macros.nim");
					result_232220 = NIM_NIL;
					goto BeforeRet;
				}
				LA54: ;
			}
			LA48: ;
		}
	}
	break;
	}
	nimln(266, "macros.nim");
	complete_222256((*HEX3Aenvp_232420).Retfuture232202, (*HEX3Aenvp_232420).Result232221);
	nimln(1287, "asyncdispatch.nim");
	(*HEX3Aenvp_232420).HEX3Astate = -1;
	BeforeRet: ;
	popFrame();
	return result_232220;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_16443;
	exchandler_16443 = s;
}

static N_INLINE(NIM_BOOL, finished_171246)(TY170666 x_171250) {
	NIM_BOOL result;
	nimfr("finished", "system.nim")
	result = 0;
	nimln(2696, "system.nim");
	      result = *((NI*) x_171250.ClEnv) < 0;
      
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_16443 = (*exchandler_16443).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_16442 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2619, "system.nim");
	result = currexception_16445;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_16445), (*currexception_16445).parent);
}

N_CLOSURE(void, cb_232371)(void* ClEnv) {
	TY232414* HEX3Aenvp_232428;
	TSafePoint TMP2067;
	nimfr("cb", "asyncdispatch.nim")
	HEX3Aenvp_232428 = (TY232414*) ClEnv;
	nimln(1068, "asyncdispatch.nim");
	pushSafePoint(&TMP2067);
	TMP2067.status = _setjmp(TMP2067.context);
	if (TMP2067.status == 0) {
		nimln(1069, "asyncdispatch.nim");
		{
			NIM_BOOL LOC4;
			futurebaseHEX3Aobjecttype160014* next_232370;
			nimln(1069, "asyncdispatch.nim");
			nimln(1069, "asyncdispatch.nim");
			LOC4 = 0;
			LOC4 = finished_171246((*HEX3Aenvp_232428).Nameitervar232368);
			if (!!(LOC4)) goto LA5;
			nimln(1070, "asyncdispatch.nim");
			next_232370 = (*HEX3Aenvp_232428).Nameitervar232368.ClPrc((*HEX3Aenvp_232428).Nameitervar232368.ClEnv);
			nimln(1071, "asyncdispatch.nim");
			{
				nimln(1071, "asyncdispatch.nim");
				if (!(next_232370 == NIM_NIL)) goto LA9;
				nimln(1072, "asyncdispatch.nim");
				{
					nimln(1072, "asyncdispatch.nim");
					if (!!((*(*HEX3Aenvp_232428).Retfuture232202).Sup.Finished)) goto LA13;
					nimln(1072, "asyncdispatch.nim");
					failedassertimpl_85425(((NimStringDesc*) &TMP2069));
				}
				LA13: ;
			}
			goto LA7;
			LA9: ;
			{
				TY160015 LOC16;
				nimln(1075, "asyncdispatch.nim");
				memset((void*)(&LOC16), 0, sizeof(LOC16));
				LOC16.ClPrc = cb_232371; LOC16.ClEnv = HEX3Aenvp_232428;
				callbackHEX3D_160849(next_232370, LOC16);
			}
			LA7: ;
		}
		LA5: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&F);
		{
			TMP2067.status = 0;
			nimln(1077, "asyncdispatch.nim");
			{
				if (!(*(*HEX3Aenvp_232428).Retfuture232202).Sup.Finished) goto LA21;
				nimln(1080, "asyncdispatch.nim");
				reraiseException();
			}
			goto LA19;
			LA21: ;
			{
				Exception* LOC24;
				nimln(1082, "asyncdispatch.nim");
				nimln(1082, "asyncdispatch.nim");
				LOC24 = 0;
				LOC24 = getCurrentException();
				fail_223203((*HEX3Aenvp_232428).Retfuture232202, LOC24);
			}
			LA19: ;
			popCurrentException();
		}
	}
	if (TMP2067.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(futureHEX3Aobjecttype222048*, match_232204)(requestHEX3Aobjecttype222060* request, responseHEX3Aobjecttype222078* response) {
	futureHEX3Aobjecttype222048* result;
	TY232414* HEX3Aenv_232431;
	TY170666 LOC1;
	TY160015 LOC2;
	nimfr("match", "macros.nim")
	result = 0;
	HEX3Aenv_232431 = 0;
	nimln(172, "system.nim");
	HEX3Aenv_232431 = (TY232414*) newObj((&NTI232432), sizeof(TY232414));
	nimln(34, "views.nim");
	asgnRef((void**) (&(*HEX3Aenv_232431).Response232207), response);
	nimln(34, "views.nim");
	asgnRef((void**) (&(*HEX3Aenv_232431).Request232206), request);
	nimln(273, "macros.nim");
	asgnRef((void**) (&(*HEX3Aenv_232431).Retfuture232202), newfuture_222132(((NimStringDesc*) &TMP2059)));
	nimln(1065, "asyncdispatch.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = matchiter_232203; LOC1.ClEnv = HEX3Aenv_232431;
	asgnRef((void**) (&(*HEX3Aenv_232431).Nameitervar232368.ClEnv), LOC1.ClEnv);
	(*HEX3Aenv_232431).Nameitervar232368.ClPrc = LOC1.ClPrc;
	nimln(1083, "asyncdispatch.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = cb_232371; LOC2.ClEnv = HEX3Aenv_232431;
	LOC2.ClEnv? LOC2.ClPrc(LOC2.ClEnv):((TMP2070)(LOC2.ClPrc))();
	nimln(266, "macros.nim");
	nimln(1271, "asyncdispatch.nim");
	result = (*HEX3Aenv_232431).Retfuture232202;
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_macrosDatInit();
	stdlib_futureDatInit();
	stdlib_sequtilsDatInit();
	stdlib_timesDatInit();
	stdlib_posixDatInit();
	stdlib_osDatInit();
	stdlib_endiansDatInit();
	stdlib_oidsDatInit();
	stdlib_hashesDatInit();
	stdlib_mathDatInit();
	stdlib_tablesDatInit();
	stdlib_unsignedDatInit();
	stdlib_rawsocketsDatInit();
	stdlib_netDatInit();
	stdlib_selectorsDatInit();
	stdlib_asyncdispatchDatInit();
	stdlib_strtabsDatInit();
	stdlib_asyncnetDatInit();
	stdlib_uriDatInit();
	stdlib_asynchttpserverDatInit();
	stdlib_pcreDatInit();
	stdlib_rtarraysDatInit();
	stdlib_reDatInit();
	stdlib_socketsDatInit();
	stdlib_asyncioDatInit();
	stdlib_scgiDatInit();
	stdlib_cookiesDatInit();
	stdlib_mimetypesDatInit();
	jester_patternsDatInit();
	stdlib_htmlgenDatInit();
	jester_errorpagesDatInit();
	stdlib_cgiDatInit();
	jester_utilsDatInit();
	jester_jesterDatInit();
	templates_annotateDatInit();
	templates_templatesDatInit();
	HEX00_masterDatInit();
	HEX00_viewsDatInit();
	todoDatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_macrosInit();
	stdlib_futureInit();
	stdlib_sequtilsInit();
	stdlib_timesInit();
	stdlib_posixInit();
	stdlib_osInit();
	stdlib_endiansInit();
	stdlib_oidsInit();
	stdlib_hashesInit();
	stdlib_mathInit();
	stdlib_tablesInit();
	stdlib_unsignedInit();
	stdlib_rawsocketsInit();
	stdlib_netInit();
	stdlib_selectorsInit();
	stdlib_asyncdispatchInit();
	stdlib_strtabsInit();
	stdlib_asyncnetInit();
	stdlib_uriInit();
	stdlib_asynchttpserverInit();
	stdlib_pcreInit();
	stdlib_rtarraysInit();
	stdlib_reInit();
	stdlib_socketsInit();
	stdlib_asyncioInit();
	stdlib_scgiInit();
	stdlib_cookiesInit();
	stdlib_mimetypesInit();
	jester_patternsInit();
	stdlib_htmlgenInit();
	jester_errorpagesInit();
	stdlib_cgiInit();
	jester_utilsInit();
	jester_jesterInit();
	templates_annotateInit();
	templates_templatesInit();
	HEX00_masterInit();
	HEX00_viewsInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	todoInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, todoInit)(void) {
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("todo", "todo.nim")
	nimln(553, "jester.nim");
	nimln(272, "jester.nim");
	nimln(272, "jester.nim");
	LOC1 = 0;
	LOC1 = nosgetCurrentDir();
	LOC2 = 0;
	LOC2 = HEX2F_125499(LOC1, ((NimStringDesc*) &TMP2054));
	asgnRef((void**) (&settings_232201), newsettings_225237(((NU16) 5000), LOC2, ((NimStringDesc*) &TMP2055)));
	nimln(266, "macros.nim");
	serve_225251(match_232204, settings_232201);
	nimln(34, "todo.nim");
	runforever_171443();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, todoDatInit)(void) {
static TNimNode* TMP2056[10];
static TNimNode TMP129[11];
NTI232414.size = sizeof(TY232414);
NTI232414.kind = 18;
NTI232414.base = 0;
TMP2056[0] = &TMP129[1];
TMP129[1].kind = 1;
TMP129[1].offset = offsetof(TY232414, HEX3Astate);
TMP129[1].typ = (&NTI165711);
TMP129[1].name = ":state";
TMP2056[1] = &TMP129[2];
TMP129[2].kind = 1;
TMP129[2].offset = offsetof(TY232414, Response232207);
TMP129[2].typ = (&NTI222031);
TMP129[2].name = "response232207";
TMP2056[2] = &TMP129[3];
TMP129[3].kind = 1;
TMP129[3].offset = offsetof(TY232414, Request232206);
TMP129[3].typ = (&NTI222029);
TMP129[3].name = "request232206";
TMP2056[3] = &TMP129[4];
TMP129[4].kind = 1;
TMP129[4].offset = offsetof(TY232414, Retfuture232202);
TMP129[4].typ = (&NTI222047);
TMP129[4].name = "retFuture232202";
TMP2056[4] = &TMP129[5];
TMP129[5].kind = 1;
TMP129[5].offset = offsetof(TY232414, Nameitervar232368);
TMP129[5].typ = (&NTI170666);
TMP129[5].name = "nameIterVar232368";
TMP2056[5] = &TMP129[6];
TMP129[6].kind = 1;
TMP129[6].offset = offsetof(TY232414, Result232221);
TMP129[6].typ = (&NTI138);
TMP129[6].name = "result232221";
TMP2056[6] = &TMP129[7];
TMP129[7].kind = 1;
TMP129[7].offset = offsetof(TY232414, Patternmatchret232134);
TMP129[7].typ = (&NTI214399);
TMP129[7].name = "patternMatchRet232134";
TMP2056[7] = &TMP129[8];
TMP129[8].kind = 1;
TMP129[8].offset = offsetof(TY232414, Patternmatchret232137);
TMP129[8].typ = (&NTI214399);
TMP129[8].name = "patternMatchRet232137";
TMP2056[8] = &TMP129[9];
TMP129[9].kind = 1;
TMP129[9].offset = offsetof(TY232414, Patternmatchret232143);
TMP129[9].typ = (&NTI214399);
TMP129[9].name = "patternMatchRet232143";
TMP2056[9] = &TMP129[10];
TMP129[10].kind = 1;
TMP129[10].offset = offsetof(TY232414, Patternmatchret232140);
TMP129[10].typ = (&NTI214399);
TMP129[10].name = "patternMatchRet232140";
TMP129[0].len = 10; TMP129[0].kind = 2; TMP129[0].sons = &TMP2056[0];
NTI232414.node = &TMP129[0];
NTI232432.size = sizeof(TY232414*);
NTI232432.kind = 22;
NTI232432.base = (&NTI232414);
NTI232432.marker = TMP2058;
}

