/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/erikoleary/lib/Nim/lib -o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/views.o /Users/erikoleary/Documents/onion-nimrod/sampleweb/nimcache/views.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>
typedef struct TY231036 TY231036;
typedef struct todoitem231005 todoitem231005;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell45335 tcell45335;
typedef struct tcellseq45351 tcellseq45351;
typedef struct tgcheap47416 tgcheap47416;
typedef struct tcellset45347 tcellset45347;
typedef struct tpagedesc45343 tpagedesc45343;
typedef struct tmemregion27610 tmemregion27610;
typedef struct tsmallchunk26840 tsmallchunk26840;
typedef struct tllchunk27604 tllchunk27604;
typedef struct tbigchunk26842 tbigchunk26842;
typedef struct tintset26817 tintset26817;
typedef struct ttrunk26813 ttrunk26813;
typedef struct tavlnode27608 tavlnode27608;
typedef struct tgcstat47414 tgcstat47414;
typedef struct tbasechunk26838 tbasechunk26838;
typedef struct tfreecell26830 tfreecell26830;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  todoitem231005  {
NI Id;
NimStringDesc* Description;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45335  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45351  {
NI Len;
NI Cap;
tcell45335** D;
};
struct  tcellset45347  {
NI Counter;
NI Max;
tpagedesc45343* Head;
tpagedesc45343** Data;
};
typedef tsmallchunk26840* TY27622[512];
typedef ttrunk26813* ttrunkbuckets26815[256];
struct  tintset26817  {
ttrunkbuckets26815 Data;
};
struct  tmemregion27610  {
NI Minlargeobj;
NI Maxlargeobj;
TY27622 Freesmallchunks;
tllchunk27604* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26842* Freechunkslist;
tintset26817 Chunkstarts;
tavlnode27608* Root;
tavlnode27608* Deleted;
tavlnode27608* Last;
tavlnode27608* Freeavlnodes;
};
struct  tgcstat47414  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47416  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45351 Zct;
tcellseq45351 Decstack;
tcellset45347 Cycleroots;
tcellseq45351 Tempstack;
NI Recgclock;
tmemregion27610 Region;
tgcstat47414 Stat;
};
typedef NI TY26820[8];
struct  tpagedesc45343  {
tpagedesc45343* Next;
NI Key;
TY26820 Bits;
};
struct  tbasechunk26838  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26840  {
  tbasechunk26838 Sup;
tsmallchunk26840* Next;
tsmallchunk26840* Prev;
tfreecell26830* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27604  {
NI Size;
NI Acc;
tllchunk27604* Next;
};
struct  tbigchunk26842  {
  tbasechunk26838 Sup;
tbigchunk26842* Next;
tbigchunk26842* Prev;
NI Align;
NF Data;
};
struct  ttrunk26813  {
ttrunk26813* Next;
NI Key;
TY26820 Bits;
};
typedef tavlnode27608* TY27614[2];
struct  tavlnode27608  {
TY27614 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  tfreecell26830  {
tfreecell26830* Next;
NI Zerofield;
};
struct TY231036 {
  TGenericSeq Sup;
  todoitem231005 data[SEQ_DECL_SIZE];
};
N_NIMCALL(TY231036*, newseq_231031)(NI len_231035);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell45335*, usrtocell_49046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50604)(tcell45335* c);
N_NOINLINE(void, addzct_49017)(tcellseq45351* s, tcell45335* c);
N_NIMCALL(NimStringDesc*, HEX24_231069)(todoitem231005 item);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, index_231079)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_85425)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, layout_230014)(NimStringDesc* title, NimStringDesc* content);
STRING_LITERAL(TMP2041, "", 0);
STRING_LITERAL(TMP2042, "<a href=\"/remove/", 17);
STRING_LITERAL(TMP2044, "\">x</a>\012<span>", 14);
STRING_LITERAL(TMP2045, "</span>\012", 8);
STRING_LITERAL(TMP2046, "<ul>\012", 5);
STRING_LITERAL(TMP2047, "    <li>", 8);
STRING_LITERAL(TMP2048, "</li>\012", 6);
STRING_LITERAL(TMP2049, "(system.len|system.len|system.len|system.len|system.len|...)(a)"
" (system.==|system.==|system.==|system.==|system.==|system.==|sy"
"stem.==|system.==|system.==|system.==|system.==|system.==|system"
".==|system.==|system.==|system.==|system.==|system.==|system.==|"
"system.==|...)\012    L seq modified while iterating over it", 312);
STRING_LITERAL(TMP2050, "</ul>\012", 6);
STRING_LITERAL(TMP2051, "<div id=\"warning\">No TODO items</div>\012", 38);
STRING_LITERAL(TMP2052, "<form action=\"/add\" method=\"post\">\012    <label for=\"newItem\">New"
" Item:</label>\012    <input id=\"newItem\" name=\"newItem\">\012    <butt"
"on name=>Add</button>\012</form>\012", 157);
STRING_LITERAL(TMP2053, "TODO", 4);
NI nextid_231011;
TNimType NTI231005; /* TodoItem */
extern TNimType NTI108; /* int */
extern TNimType NTI149; /* string */
TY231036* todoitems_231065;
extern TFrame* frameptr_16442;
extern tgcheap47416 gch_47444;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16442 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16442;
	frameptr_16442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16442 = (*frameptr_16442).prev;
}

static N_INLINE(tcell45335*, usrtocell_49046)(void* usr) {
	tcell45335* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45335*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell45335))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50604)(tcell45335* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_49017((&gch_47444.Zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		tcell45335* c;
		nimln(251, "gc.nim");
		nimln(251, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_49046(src);
		nimln(169, "gc.nim");
		(*c).Refcount += 8;
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		tcell45335* c;
		nimln(254, "gc.nim");
		nimln(254, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_49046((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).Refcount -= 8;
			nimln(168, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_50604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI64)((*src).Sup.len + 1));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_231069)(todoitem231005 item) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	nimfr("$", "views.nim")
	result = 0;
	nimln(266, "macros.nim");
	result = copyString(((NimStringDesc*) &TMP2041));
	nimln(15, "views.nim");
	result = resizeString(result, 17);
appendString(result, ((NimStringDesc*) &TMP2042));
	nimln(15, "views.nim");
	nimln(15, "views.nim");
	nimln(266, "macros.nim");
	LOC1 = 0;
	LOC1 = nimIntToStr(item.Id);
	LOC2 = 0;
	LOC2 = nsuStrip(LOC1, NIM_TRUE, NIM_TRUE);
	result = resizeString(result, LOC2->Sup.len + 0);
appendString(result, LOC2);
	nimln(15, "views.nim");
	result = resizeString(result, 14);
appendString(result, ((NimStringDesc*) &TMP2044));
	nimln(15, "views.nim");
	nimln(15, "views.nim");
	nimln(266, "macros.nim");
	LOC3 = 0;
	LOC3 = nsuStrip(item.Description, NIM_TRUE, NIM_TRUE);
	result = resizeString(result, LOC3->Sup.len + 0);
appendString(result, LOC3);
	nimln(15, "views.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TMP2045));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, index_231079)(void) {
	NimStringDesc* result;
	nimfr("index", "views.nim")
	result = 0;
	nimln(21, "views.nim");
	{
		nimln(21, "views.nim");
		nimln(21, "views.nim");
		if (!(0 < todoitems_231065->Sup.len)) goto LA3;
		nimln(266, "macros.nim");
		result = copyString(((NimStringDesc*) &TMP2041));
		nimln(22, "views.nim");
		result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TMP2046));
		{
			todoitem231005 item_231222;
			NI i_231226;
			NI l_231228;
			memset((void*)(&item_231222), 0, sizeof(item_231222));
			nimln(2986, "system.nim");
			i_231226 = 0;
			nimln(2987, "system.nim");
			nimln(2987, "system.nim");
			l_231228 = todoitems_231065->Sup.len;
			{
				nimln(2988, "system.nim");
				while (1) {
					NimStringDesc* LOC8;
					nimln(2988, "system.nim");
					if (!(i_231226 < l_231228)) goto LA7;
					nimln(2989, "system.nim");
					if ((NU)(i_231226) >= (NU)(todoitems_231065->Sup.len)) raiseIndexError();
					item_231222.Id = todoitems_231065->data[i_231226].Id;
					item_231222.Description = todoitems_231065->data[i_231226].Description;
					nimln(22, "views.nim");
					result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TMP2047));
					nimln(22, "views.nim");
					nimln(22, "views.nim");
					LOC8 = 0;
					LOC8 = HEX24_231069(item_231222);
					result = resizeString(result, LOC8->Sup.len + 0);
appendString(result, LOC8);
					nimln(22, "views.nim");
					result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TMP2048));
					nimln(2990, "system.nim");
					i_231226 = addInt(i_231226, 1);
					nimln(2991, "system.nim");
					{
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						nimln(2991, "system.nim");
						if (!!((todoitems_231065->Sup.len == l_231228))) goto LA11;
						nimln(2991, "system.nim");
						failedassertimpl_85425(((NimStringDesc*) &TMP2049));
					}
					LA11: ;
				} LA7: ;
			}
		}
		nimln(22, "views.nim");
		result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TMP2050));
	}
	goto LA1;
	LA3: ;
	{
		nimln(266, "macros.nim");
		result = copyString(((NimStringDesc*) &TMP2041));
		nimln(30, "views.nim");
		result = resizeString(result, 38);
appendString(result, ((NimStringDesc*) &TMP2051));
	}
	LA1: ;
	nimln(34, "views.nim");
	result = resizeString(result, 157);
appendString(result, ((NimStringDesc*) &TMP2052));
	nimln(42, "views.nim");
	nimln(42, "views.nim");
	result = layout_230014(((NimStringDesc*) &TMP2053), result);
	goto BeforeRet;
	BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_viewsInit)(void) {
	nimfr("views", "views.nim")
	nimln(11, "views.nim");
	nextid_231011 = 1;
	nimln(12, "views.nim");
	asgnRefNoCycle((void**) (&todoitems_231065), newseq_231031(0));
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_viewsDatInit)(void) {
static TNimNode* TMP2039[2];
static TNimNode TMP2030[3];
NTI231005.size = sizeof(todoitem231005);
NTI231005.kind = 18;
NTI231005.base = 0;
NTI231005.flags = 2;
TMP2039[0] = &TMP2030[1];
TMP2030[1].kind = 1;
TMP2030[1].offset = offsetof(todoitem231005, Id);
TMP2030[1].typ = (&NTI108);
TMP2030[1].name = "id";
TMP2039[1] = &TMP2030[2];
TMP2030[2].kind = 1;
TMP2030[2].offset = offsetof(todoitem231005, Description);
TMP2030[2].typ = (&NTI149);
TMP2030[2].name = "description";
TMP2030[0].len = 2; TMP2030[0].kind = 2; TMP2030[0].sons = &TMP2039[0];
NTI231005.node = &TMP2030[0];
}

